### ISSUE TITLE
Application crash after closing the razorpay view

### ISSUE THREAD

**Issue by AnkitaKansal** [razorpay/react-native-razorpay#100]
Application is crashing while i press back button or forcefully close razorpay view by pressing top right corner close button or after payment success.

"react-native": "0.55.4"

@iThink32

**Comment by iThink32** [comment]
I think there is something wrong in the way you have integrated it as no other client has reported this anyway please watch our integration videos 

https://razorpay.com/docs/ios/integration-videos/

and double check if you have followed all the steps else I will help you resolve it.

**Comment by iThink32** [comment]
closing this issue for now , reopen if you need any further assistance.

**Comment by NorinMp143** [comment]
> Application is crashing while i press back button or forcefully close razorpay view by pressing top right corner close button or after payment success.
> 
> "react-native": "0.55.4"
> 
> @iThink32

i had same problem with following versions
react-native 0.64.2
react-native-razorpay 2.2.7
