### ISSUE TITLE
[Android] adding a 3 digit hex code crashes razor pay on android

### ISSUE THREAD

**Issue by essuraj** [razorpay/react-native-razorpay#105]
`theme: { color: "#fff" }` works fine on IOS and crashes on android... no way to diagnose.. either fix or document the quirk

**Comment by Mayur-Wadpalliwar** [comment]
@essuraj Could you please share the complete crash logs?

**Comment by essuraj** [comment]
`react-native log-android` showed no errors. the app just stops working... when i changed the `#fff` to `#ffffff` it worked

**Comment by Mayur-Wadpalliwar** [comment]
@essuraj Please use the complete hex code in that case. We will take this up in our next release
