### ISSUE TITLE
dyld: Library not loaded: @rpath/libswiftCore.dylib 

### ISSUE THREAD

**Issue by meetyourdev** [razorpay/react-native-razorpay#106]
**Error : dyld: Library not loaded: @rpath/libswiftCore.dylib
Reason: image not found**

Followed the react-native integration video  mentioned on razorpay ios docs [here](https://razorpay.com/docs/ios/integration-videos/#integrating-the-sdk-using-react-native)

**Things already done :** 
1) Followed all steps mentioned in the video
2) Executed script SelectDefaultXcode.sh as mentioned in the video.
2) Added Razorpay framework from node_modules/react-native-razorypay/ios to Embedded Binaries
3) Set Build Setting/ Build Option/ Allow Embed Swift Standard Libraries to Yes
4) Clean. Build.

**Running on Xcode 9.2 with Swift 4.0.3 
OS : Sierra**

I also tried to integrate with framework that support swift 3.1

razorpay/react-native-razorpay github docs states : 
Note: This release is meant for Xcode 9.3 as it uses a framework compiled in Swift 4.1.This will not work in Xcode 9.2 as you will get a "dlyd error : framework not found error".In case you are using an older version of Xcode and need Swift 3.1 visit the following link and download the respective framework.

Downloaded Razorpay(with bit code enabled) 1.0.21 - Swift 3.1 from [here](https://razorpay.com/docs/ios/#step-1-importing-the-library) and replaced the framework in node_modules/react-native-razorypay/ios. Added it  in Embedded Binaries as well and did a clean run. It throws

**error: The following binaries use incompatible versions of Swift:
/Users/meetpatel/Desktop/code/reactnative/ios/build/Build/Products/Debug-iphonesimulator/Registration.app/Frameworks/Razorpay.framework/Razorpay**

I cannot upgrade my xcode to 9.3 as i am running sierra and cannot update to High Sierra due to my hardware limitation.

**Comment by iThink32** [comment]
@meetyourdev we do not support Xcode 9.2 as we have moved to Swift 4.1.I request you to free up some space on your machine and move to High Sierra.

**Comment by meetyourdev** [comment]
@iThink32 Razorpay Framework v1.0.21 is compiled with Swift 3.1, will that work in Xcode 9.2 as it has Swift 4.0.3 ?

**Comment by iThink32** [comment]
@meetyourdev no it will only work on versions prior to Xcode 9.0

**Comment by Balasnest** [comment]
**Facing same in 2.0.9.**
Xcode: **9.3.1** and **9.4**
```
dyld: Library not loaded: @rpath/libswiftCore.dylib
  Referenced from: /.../Library/Developer/CoreSimulator/Devices/A9B1B68A-8A86-4C89-8370-388E470B9F64/data/Containers/Bundle/Application/C074D995-2DE8-48A3-8143-81FF11F4EBAC/mfine.app/Frameworks/Razorpay.framework/Razorpay
  Reason: image not found
```

**React Native Environment Info:**
    
    System:
      OS: macOS High Sierra 10.13.6
      CPU: x64 Intel(R) Core(TM) i7-4770HQ CPU @ 2.20GHz
      Memory: 61.57 MB / 16.00 GB
      Shell: 5.3 - /bin/zsh
    
     Binaries:
      Node: 8.9.4 - /usr/local/bin/node
      Yarn: 1.3.2 - /usr/local/bin/yarn
      npm: 4.6.1 - /usr/local/bin/npm
      Watchman: 4.9.0 - /usr/local/bin/watchman
    
    SDKs:
      iOS SDK:
        Platforms: iOS 11.3, macOS 10.13, tvOS 11.3, watchOS 4.3
    
     IDEs:
      Android Studio: 3.0
      Xcode: 9.3.1
    
     npmPackages:
      react: 16.4.1 => 16.4.1 
      react-native: 0.56.0 => 0.56.0 
    
     npmGlobalPackages:
      react-native-checkbox: 2.0.0
      react-native-cli: 2.0.1
      react-native-datepicker: 1.6.0
      react-native-git-upgrade: 0.2.7

**Comment by sivakumar-cf** [comment]
Got the same error On Xcode 10.2
You might be required to support Swift 5 as well.
I am using this library from pod 'razorpay-pod'
```
  dyld: Library not loaded: @rpath/libswiftCore.dylib
  Referenced from: /Users/xxxx/Library/Developer/CoreSimulator/Devices/B482F16E-E739-43F7-ACEA-62C22E64F1C0/data/Containers/Bundle/Application/5B25C106-382B-46E6-B086-65B330100916/xxxxx.app/Frameworks/Razorpay.framework/Razorpay
  Reason: image not found
```

**Comment by sairamragi** [comment]
facing the following issue 


dyld: Library not loaded: @rpath/libswiftCore.dylib
  Referenced from: /XXXXXXXXXXX/XXXXX/Frameworks/Razorpay.framework/Razorpay
  Reason: image not found
(lldb) 

after updating to Xcode 10.2 

My application is built using IONIC 3 

when I build using Terminal it's building but


 when I'm trying to run on simulator its not working and giving the above-mentioned error.

**Comment by vikaskhandekar001** [comment]
I am getting below error . i have referred to integration video and did all the things as said, but still i am getting error.

Xcode version:Version 10.1 (10B61)
react-native-razorpay version:2.1.23

dyld: Library not loaded: @rpath/libswiftCore.dylib
  Referenced from: /********/Frameworks/Razorpay.framework/Razorpay
  Reason: image not found

**Comment by pronav** [comment]
Have you set `Always Embed Swift Standard Binaries` setting to yes, and `Razorpay.framework` is present under `Embedded Binaries` section?

**Comment by vikaskhandekar001** [comment]
yes,i have. i have done everything as instructed in integration video .

**Comment by vikaskhandekar001** [comment]
i am still struggling with the same issue ...
