### ISSUE TITLE
Card payment redirects to different page 

### ISSUE THREAD

**Issue by essuraj** [razorpay/react-native-razorpay#107]
Card payment redirects to different page instead of returning razorpay id
Cant find any documentation on how to proceed.
![image](https://user-images.githubusercontent.com/1737617/45340943-36087780-b5b6-11e8-98a6-4aa3d851a0c8.png)

**Comment by iThink32** [comment]
@essuraj hey it is because you are using a demo key , use a live key and you will not see this page.

**Comment by essuraj** [comment]
im using the test mode key from my account..

**Comment by Mayur-Wadpalliwar** [comment]
@essuraj This is the expected behavior. Once you click on success / failure, the respective handler function will be called.
