### ISSUE TITLE
Module compiled with Swift 4.1 cannot be imported by the Swift 4.2 compiler: .../Framework/Razorpay.framework/Modules/Razorpay.swiftmodule/x86_64.swiftmodule

### ISSUE THREAD

**Issue by pritamhinger** [razorpay/react-native-razorpay#110]
* **Common to Both platforms :-**

  - [x] I have gone through the README (https://github.com/razorpay/react-native-razorpay)
  - [x] I have searched for a similar issue (https://github.com/razorpay/react-native-razorpay/issues)
  - [x] I am using the latest version of our framework (https://github.com/razorpay/react-native-razorpay/releases)
  - [x] I have cleaned my project.

* **Specific to iOS Users :-**

  - [x] I have modified the module map as specified in the readme (https://github.com/razorpay/react-native-razorpay)
  - [x] I have deleted the contents of the derived data folder and rebuild it.

## IDE Specs

Xcode 10
![screen shot 2018-09-20 at 5 29 20 pm](https://user-images.githubusercontent.com/6961351/45816930-bfc4ed00-bcfa-11e8-95dc-90d1839f0c30.png)

1.0.22

## Retro Steps

- Create a sample project.
- Add Razorpay using Cocoapod or by importing library
- Compile it

## Steps taken by me to solve it
- I tried using swift toolchain to switch compiler to 4.1
- With Swift 4.1 Toolchain enabled on Xcode 10, I am getting the error "Could not find module RazorpayCommonCrypto".
- I tried running the SelectDefaultXcode.sh script but since Xcode10 is the only Xcode installed on my machine to it didn't help me either.

## Screenshots 

![screen shot 2018-09-20 at 5 23 25 pm](https://user-images.githubusercontent.com/6961351/45816972-e84ce700-bcfa-11e8-908c-68b577b4abd0.png)

**Comment by iThink32** [comment]
We are aware of this issue , it is because Xcode 10 supports Swift 4.2 and above and our framework is compiled with Swift 4.1.We are making a release on September 28th for this , please wait till then.

**Comment by pritamhinger** [comment]
Thanks, @iThink32 for the update. I will wait till then.
