### ISSUE TITLE
React/RCTEventEmitter.h not found in iOS

### ISSUE THREAD

**Issue by Balasnest** [razorpay/react-native-razorpay#112]
* **Specific to iOS :-**
Getting React/RCTEventEmitter.h not found in iOS error while building. 

## IDE Specs

Razorpay : ^2.0.0
Environment:
  OS: macOS High Sierra 10.13
  Node: 8.9.4
  Yarn: 1.3.2
  npm: 4.6.1
  Watchman: 4.9.0
  Xcode: Xcode 9.2 Build version 9C40b
  Android Studio: 3.0 AI-171.4443003

Packages: (wanted => installed)
  react: 16.0.0 => 16.0.0
  react-native: 0.51.0 => 0.51.0

http://prntscr.com/ky26qm

**Comment by vamshi9666** [comment]
how did it resolve ?

**Comment by Nautiyalsachin** [comment]
Update it to the latest version of react-native-razorpay. Also use cocoapods for the Auto Linking.
