### ISSUE TITLE
After installation got the below error.can anyone  help? 

### ISSUE THREAD

**Issue by rajkishoreandia** [razorpay/react-native-razorpay#117]
Loading dependency graph...jest-haste-map: @providesModule naming collision:
  Duplicate module name: Sample
  Paths: /Users/uniquecreations/Desktop/latest-app/donate-us-pay/node_modules/react-native-razorpay/node_modules/react-native/Libraries/Sample/package.json collides with /Users/uniquecreations/Desktop/latest-app/donate-us-pay/node_modules/react-native/Libraries/Sample/package.json

This warning is caused by a @providesModule declaration with the same name across two different files.
jest-haste-map: @providesModule naming collision:

**Comment by iThink32** [comment]
@rajkishoreandia please update to the latest version of our package and try again.

**Comment by iThink32** [comment]
@rajeevrai its a derived data issue , delete node modules and install it again and make sure your installing the latest version of react - native - razorpay.
If you look closely at our package we don't even have a node module folder

**Comment by rajkishoreandia** [comment]
after removing and reinstalling also i got the same error the issue is actually i have react-native package inside my node module and one more react-native-node module is inside react-native-razorpay node modules.so its giving duplication error

**Comment by iThink32** [comment]
@rajkishoreandia this is a react-native issue , it is not related to razorpay , but yes you should blacklist files to make it work.Please check on other forums for an appropriate solution.

**Comment by Balasnest** [comment]
@rajkishoreandia Me too facing this exact issue.  Did you resolve this?

**Comment by santhosh77h** [comment]
@iThink32 this issue still exists by removing react-native-razorpay if I run my application it works fine.
so i guess it may be issue may be from razorpay and even my package.json under react-native-razorpay has `  "dependencies": {
    "react": "16.5.0",
    "react-native": "0.57.1"
  },`.
Do you have any solution for this?

**Comment by santhosh77h** [comment]
@iThink32 react-native-razorpay has a dependency on react-native but I have read somewhere that is not good practice because of that we were getting this [https://github.com/facebook/react-native/issues/15789](error)

**Comment by santhosh77h** [comment]
@iThink32 I think `react-native` should be `devDepenency` not under `dependencies` because of which user has a different version then what is mentioned in your `package.json` it throws that Ambiguous error telling that there are multiple react-native versions available

**Comment by iThink32** [comment]
@santhosh77h ok so specifying devDependancy does not add react-native to the directory containing the package installed which intern resolves the "ambiguous issue" is what your saying right?

ive also read this link
https://stackoverflow.com/questions/18875674/whats-the-difference-between-dependencies-devdependencies-and-peerdependencies

ok thanks will try this out.

**Comment by santhosh77h** [comment]
yes, you are correct.....

**Comment by iThink32** [comment]
@santhosh77h thanks for the heads up and im assuming that your issue has been fixed.Closing this issue reopen if issue persists.
