### ISSUE TITLE
dyld: Symbol not found: _$SBOWV

### ISSUE THREAD

**Issue by essuraj** [razorpay/react-native-razorpay#125]
Razor pay 2.0.13 .... xcode 9 

The app is stuck on launch screen in iOS.. android works fine
```
dyld: Symbol not found: _$SBOWV
  Referenced from: /Users/capadmin/Library/Developer/CoreSimulator/Devices/9113AFD2-CA19-4F1A-A54C-D1975173A7A6/data/Containers/Bundle/Application/A8E17B45-FEB1-40D9-B611-BB3D840CE532/[].app/Frameworks/Razorpay.framework/Razorpay
  Expected in: /Users/capadmin/Library/Developer/CoreSimulator/Devices/9113AFD2-CA19-4F1A-A54C-D1975173A7A6/data/Containers/Bundle/Application/A8E17B45-FEB1-40D9-B611-BB3D840CE532/[].app/Frameworks/libswiftCore.dylib
 in /Users/capadmin/Library/Developer/CoreSimulator/Devices/9113AFD2-CA19-4F1A-A54C-D1975173A7A6/data/Containers/Bundle/Application/A8E17B45-FEB1-40D9-B611-BB3D840CE532/[].app/Frameworks/Razorpay.framework/Razorpay
```

I might be wrong but even when i downgrade to 2.0.9 i get the latest Razorpay.framework 1.0.23 in node_modules.. which i think isnt working with xcode 9... what can i do?

**Comment by essuraj** [comment]
any suggestion would be nice.

**Comment by essuraj** [comment]
Yup..... i replaced ios directory with old framework and it works .. this is breaking all ios builds as you are downloading latest IOS sdk on any version.....

**Comment by iThink32** [comment]
hey @essuraj please go through the readme first , this release is meant for Xcode 10 and above only and you are supposed to add the new framework both in linked binaries and embed frameworks section.

**Comment by essuraj** [comment]
@iThink32 ...have done that... version 2.0.9 is also downloading latest ios sdk 1.0.23 ... which is breaking my build

**Comment by iThink32** [comment]
@essuraj you are supposed to run our latest framework on Xcode 10 i.e 2.0.13 on Xcode 10.

**Comment by essuraj** [comment]
@iThink32 We are not ready to move to XCode 10 as react-native still has issues..  even if i downgrade your library, its still downloading the latest sdk.... currently im replacing contents of  ios folder in react-native-razorpay from an old, unupdated yarn install from another machine i have. which has 2.09.
