### ISSUE TITLE
cocoa pod integration support added for iOS integration

### ISSUE THREAD

**Issue by dayitv89** [razorpay/react-native-razorpay#126]
It is almost generic that react native lib which are providing native libraries supports, provides integration option with cocoa pods  for iOS project as recommend option. While community says cocoa pods integration is much cleaner and safer way to integrate the decencies instead of `react-native link`. 

I'm eagerly waiting to have pod integration support.

**Comment by iThink32** [comment]
@dayitv89 well it is something I must also look into but nonetheless thanks for your inputs but keeping the current situation of react-native for Xcode 10 in mind the focus is more on providing a stable version to clients.Once react-native releases a stable version of Xcode 10 , well consider this as an alternative.
