### ISSUE TITLE
Blank Window is shows while calling razorpay.open()

### ISSUE THREAD

**Issue by bonhappetee** [razorpay/react-native-razorpay#130]
Hi, 

I'm using latest **pod 'razorpay-pod', '1.0.24'** on iOS, swift 4.2. When I start payment using razorpay.open(options, displayController: self), some screen opens with title authorise, then everything goes blank, with no error, and no option to navigate anywhere else.

Please resolve this issues asap, or tell me what i'm doing wrong!

**Comment by iThink32** [comment]
@bonhappetee where are you writing this line? can you provide more details?

**Comment by bonhappetee** [comment]
I'm writing this line in a viewController on a button click.

**Comment by bonhappetee** [comment]
I just realized that i've asked this question on wrong place. I'm not implementing it on react native. I'm implementing in swift 4.2 in xCode. But the problem remains that same. Should I ask this question again in the pod section?

**Comment by iThink32** [comment]
@bonhappetee thought so , can you tell me whether you rootViewController is a navigation controller?

**Comment by bonhappetee** [comment]
Yes, the viewController that i'm calling this method from is inside a NavigationController.

**Comment by iThink32** [comment]
@bonhappetee then call it without the displayController property , it should ideally not cause any issue but anyway try this.

**Comment by bonhappetee** [comment]
Okay, now it's working. But when I tried earlier, it wasn't. BTW, both call - with or without displayController, are doing exactly the same thing.

**Comment by iThink32** [comment]
@bonhappetee there is something fishy which I'm not able to debug with the information you provided.
Ideally if you have a navController as your rootViewController you don't need to use the displayController property , it is only used when your navigation consists of a tab bar controller or any other controller as your rootController in which we use the displayController property to check whether or not it is embedded inside a navController , if so we push onto that or present on to that.

**Comment by bonhappetee** [comment]
There's another issue, if I cancel the payment on the very first screen, your sdk is hiding my navigationController when it comes back! leaving me with option to navigate anywhere else. But when the payment is successful, then the naviationController remains the same when it comes back.

**Comment by bonhappetee** [comment]
with no* option

**Comment by iThink32** [comment]
@bonhappetee yes that is a known issue we will be fixing it in the next release.

**Comment by bonhappetee** [comment]
At the very root of my app, there's a TabBarController only. But this module, where i'm using the payment option, is inside a different navigationController, that I open modally, like a separate module.

**Comment by iThink32** [comment]
@bonhappetee are you modally presenting a navigation controller?

**Comment by bonhappetee** [comment]
yes, it is the starting point of my store module in the app, that i open modally.

**Comment by iThink32** [comment]
@bonhappetee got the reason , look at your console , you'll see an error message that says attempting to present navigation controller ....... if you try to use displayController but nonetheless we will be making another release that checks if you're display controller has a navigation controller if so it will push on it else will present , let me know when you face any other issue.Closing for now.
