### ISSUE TITLE
"JavaScript" in pop-up title

### ISSUE THREAD

**Issue by sjenit** [razorpay/react-native-razorpay#135]
Please change the title of the pop-up with some appropriate message. Currently, it shows **"JavaScript"** as a title which is irrelevant for users.

![razorpay_issue](https://user-images.githubusercontent.com/7440055/47268232-e9786a80-d56b-11e8-90be-27b649c6162c.jpg)

**Comment by iThink32** [comment]
please update to our latest version and reopen if issue persists.
