### ISSUE TITLE
Update android permission --> RECEIVE_SMS

### ISSUE THREAD

**Issue by DiksonSamuel** [razorpay/react-native-razorpay#137]
I got a mail from google play console stating  "In October, we announced updates to our Permissions policy that will limit which apps are allowed to request Call Log and SMS permissions"

Only razorpay plugin uses "RECEIVE_SMS"

Please update react-native-razorpay permissions for android

**Comment by ramuachala** [comment]
Please make sure the build works for xCode 9

**Comment by iThink32** [comment]
@ramuachala we have stopped support for Xcode 9 , as mentioned in the readme going forward only the latest version of Swift will be supported.

**Comment by ramuachala** [comment]
@iThink32 But react-native doesn't support xCode 10 yet.. how do you expect us to use it?

**Comment by iThink32** [comment]
@ramuachala it does , we have made a release for it a month back , react-native for Xcode 10 is not stable right now that's why an update right away is not recommended but a lot of people have used our package and it is stable.

**Comment by yashwant-dangi** [comment]
I am using Latest Version available at this time i.e. - 2.1.3 but still, I am getting a warning from the google play team about **SMS and Call log permissions** and my app is rejected in Internal Testing Track. I checked the SDK and this permission is still present there. **android.permission.RECEIVE_SMS**
