### ISSUE TITLE
Duplicate module name: react-native

### ISSUE THREAD

**Issue by vkandk** [razorpay/react-native-razorpay#139]
ERROR:
Duplicate module name: react-native
Paths: ..\<project-name>\node_modules\react-native-razorpay\node_modules\react-native\package.json 
collides with 
..\<project-name>\node_modules\react-native\package.json
This error is caused by a @providesModule declaration with the same name across two different files.
---------------------------------------------------------------------------------
Application details ->

React Native AWS Mobile Hub App - 
package.json:
{...
"react": "16.5.0",
"react-native": " 0.57.1",
"react-native-razorpay": "^2.0.16",
...
}

build.gradle:
buildscript {
    repositories {
        google()
        jcenter()
        gradlePluginPortal()
    }
    dependencies {
        classpath 'com.android.tools.build:gradle:3.2.1'

        // NOTE: Do not place your application dependencies here; they belong
        // in the individual module build.gradle files
    }
}

allprojects {
    repositories {
        mavenLocal()
        jcenter()
        maven { url "https://jitpack.io" }
        maven { url "https://maven.google.com" }
        maven {
            // All of React Native (JS, Obj-C sources, Android binaries) is installed from npm
            url "$rootDir/../node_modules/react-native/android"
        }
    }
}

android/app/build.gradle:

android {
    compileSdkVersion 27
    buildToolsVersion "28.0.3"
    defaultConfig {
        applicationId "<package-name>"
        minSdkVersion 19
        targetSdkVersion 27
        versionCode 29
        versionName "<Version-Name>"
        vectorDrawables.useSupportLibrary = true
    }

dependencies {
   implementation project(':react-native-view-pdf')
    implementation project(':react-native-svg')
    implementation project(':react-native-image-crop-picker')
    implementation project(':amazon-cognito-identity-js')
    implementation project(':react-native-fetch-blob')
    implementation project(':react-native-vector-icons')
    implementation project(':react-native-razorpay')
    implementation fileTree(dir: "libs", include: ["*.jar"])
    implementation "com.android.support:appcompat-v7:25.0.0"
    implementation "com.facebook.react:react-native:+"  // From node_modules
}

**Comment by iThink32** [comment]
@vkandk the ideal solution is blacklisting the node modules folder in react-native-razorpay.But even if you remove node modules it will work.

**Comment by jfreak** [comment]
Tried blacklisting the node modules folder in react-native-razorpay still having the same issue
```
 "react": "16.6.1",
 "react-native": "0.57.7"
```

**Comment by iThink32** [comment]
@jfreak delete your derived data ,  close your metro bundler , clean and build.
If all fails you can delete the node modules folder in react-native-razorpay and try.

**Comment by GaudamThiyagarajan** [comment]
create rn-cli.config.js in your root folder and blacklist the node_modules from react-native-razorpay.

```
const blacklist = require('metro/src/blacklist');

module.exports = {
  // getTransformModulePath() {
  //   return require.resolve('./customTransformer');
  // },
  getBlacklistRE() {
    return blacklist([
      /node_modules\/react-native-razorpay\/node_modules\/.*/,
    ]);
  },
};

```

**Comment by iThink32** [comment]
@jfreak there are two permanent solutions for this :
- blacklisting which is working for a lot of people including me , you have to figure out why it isn't working
- move the dependencies in the package.json of react-native-razorpay to devDependencies (yet to try out but according to my research it is the case of this issue).Have a look at this link

https://stackoverflow.com/questions/18875674/whats-the-difference-between-dependencies-devdependencies-and-peerdependencies

**Comment by perminder-klair** [comment]
having same issue guys! hope it will be resolved soon.

**Comment by iThink32** [comment]
@perminder-klair the solution is posted above , please follow it.

**Comment by direwolf424** [comment]
@jfreak Did you get any solution as i am also getting the same error.

@iThink32 Do we need to pass the config file like this 
`react-native run-android --config rn-cli.config.js`

**Comment by GaudamThiyagarajan** [comment]
You don't have to pass the config file. It takes by default if you place it in the root folder. [check here](https://facebook.github.io/react-native/docs/understanding-cli)

**Comment by iThink32** [comment]
@direwolf424 have a look at the example folder in this repo , it'll help you out.Ive used blacklisting there.

**Comment by iThink32** [comment]
@jfreak cool.

**Comment by iThink32** [comment]
closing this issue.Reopen if required.

**Comment by itsarvindh** [comment]
Blacklisting node_modules in react-native-razorpay wouldn't create prob while in production ? As blacklisting solves the duplicate module name problem. But what about in production is it safe to do that ? Can i use this method to continue or is there any other good solution ?

**Comment by iThink32** [comment]
@itsarvindh blacklisting helps in avoiding files being compiled to ultimately create an executable , it has no effect after an executable has been created.
