### ISSUE TITLE
yarn add react-native-razorpay updates my project's yarn.lock

### ISSUE THREAD

**Issue by GaudamThiyagarajan** [razorpay/react-native-razorpay#144]
Before razorpay installation
react native@55.x and metro@0.30.x and babel@6.x.x 

After razorpay sdk installation in yarn.lock we get two react-native of different versions
on react-native-razorpay/master we are getting two versions
react-native@55.x and react-native@0.57.0 

on react-native-razorpay/2.0.10 we are getting two versions
react-native@55.x and react-native@>=0.55.0

Our own metro bundler and babel are getting updated to razorpay's package.json
How to avoid these unnecessary updates

**Comment by GaudamThiyagarajan** [comment]
Updating from 0.55 to 0.57 is not a simple task. We have to look upgrade related to babel@7 and other  dependency changes is there a simpler way to support 0.55

**Comment by GaudamThiyagarajan** [comment]
I forked your repo and downgraded the react to 0.55.4 and react to 16.3.1 and used that. This package doesn't need react native 0.57.x

**Comment by iThink32** [comment]
@GaudamThiyagarajan the fact behind this is react-native on Xcode 10 is unstable , they are still making fixes for it , it is highly recommended that you use the latest version of react-native as it contains a lot of Xcode 10 fixes.

**Comment by GaudamThiyagarajan** [comment]
Since we are working with only react-native for android would it still be a problem?

**Comment by iThink32** [comment]
@GaudamThiyagarajan I don't think so.
