### ISSUE TITLE
Razorpay sdk support for 32 bit IOS devices

### ISSUE THREAD

**Issue by navdeepKaurTrignodev** [razorpay/react-native-razorpay#148]
Hi,
The documentation for react-native-razorpay states that it supports only 64 bit architecture on ios devices. I am using this library in my app and would like to provide support for 32 bit devices as well. So is there any workaround for the same?

**Comment by iThink32** [comment]
@navdeepKaurTrignodev  the only way is by using an older architecture but that is highly not recommended as it will not contain latest fixes.Moreover it does not sound logical from our perspective to support 32-bit devices keeping in mind that iOS itself stopped supporting 32-bit apps from iOS 11.
