### ISSUE TITLE
iOS Archiving "bitcode bundle" issue

### ISSUE THREAD

**Issue by atulmy** [razorpay/react-native-razorpay#154]
When Archiving for iOS, following error is generated:

```
ld: bitcode bundle could not be generated because '/node_modules/react-native-razorpay/ios/Razorpay.framework/Razorpay' was built without full bitcode. All frameworks and dylibs for bitcode must be generated from Xcode Archive or Install build file '/node_modules/react-native-razorpay/ios/Razorpay.framework/Razorpay' for architecture armv7
clang: error: linker command failed with exit code 1 (use -v to see invocation)
````

Xcode: 10.1
React Native: 0.58.3
react-native-razorpay: 2.0.19

CC: @iThink32

**Comment by atulmy** [comment]
@iThink32 
I was able to archive before upgrading to React Native: 0.58.3

I also have the script and bitcode enabled for both main project and RazorpayCheckout.xcodeproj:

<img width="443" alt="screenshot 2019-02-05 at 1 02 19 pm" src="https://user-images.githubusercontent.com/685786/52258796-688c8580-2946-11e9-8815-5479c8a0fb0d.png">
<img width="886" alt="screenshot 2019-02-05 at 1 01 25 pm" src="https://user-images.githubusercontent.com/685786/52258789-632f3b00-2946-11e9-8ae5-cedd59587347.png">

**Comment by iThink32** [comment]
@atulmy ideally archiving should not depend on react-native version.Can you cross check and see if your missing something?

**Comment by atulmy** [comment]
@iThink32 I did check and re-tried installing the framework following along with the videos for installation and archiving. Still no luck. All other 3rd party libraries in the project are working fine with updated React Native version except Razorpay. However in the development mode it works fine, so there must be an issue/bug within the library with archiving.

**Comment by iThink32** [comment]
@atulmy see there is no code change between debug and archive mode , now since your saying that it is failing to archive on the latest react-native version means that there is something that has changed on that version causing archive to fail.Moreover all our frameworks are built with bitcode enabled.Nonetheless make sure that you have not set build active architecture as yes for any project (main or razorpay).
I suggest you to to try archiving our example project with the same steps given in the video and let me know if you still face any issue as we will have a common base to cross verify.

**Comment by atulmy** [comment]
> it is failing to archive on the latest react-native version means that there is something that has changed on that version causing archive to fail.
Yes, that's where I need help with. Razorpay does not support latest RN?

**Comment by iThink32** [comment]
@atulmy we have not received any issues with the latest version of RN , moreover if it compiles successfully it means that there is no source code issues , this is clearly a build setting issue so please try our archiving our example app on the latest version and let me know if you still face any issues.

**Comment by iThink32** [comment]
@atulmy hey just check with the example app , if you face issues we can have a hangouts call and ill help you fix it , cool?

**Comment by atulmy** [comment]
Unfortunately due to continuous issues with Razorpay iOS integration, we have decided to find an alternative payment gateway integration meanwhile. Thank you for your support.

**Comment by iThink32** [comment]
@atulmy as far as my knowledge goes this is your first issue raised with us , nonetheless if ever decide to switch back you are always welcome.

**Comment by iThink32** [comment]
@atulmy to answer your question the example in this repo is currently using the latest version of rn to cross verify.

**Comment by Jibin2015** [comment]
@iThink32 I am also facing the same issue.

I have installed the latest razorpay node module using yarn and followed manual linking given below:

1) In XCode, in the project navigator, right click Libraries ➜ Add Files to [your project's name]

2) Go to node_modules ➜ react-native-razorpay and add RazorpayCheckout.xcodeproj

3) In XCode, in the project navigator, select your project. Add libRazorpayCheckout.a to your project's Build Phases ➜ Link Binary With Libraries

4) Run your project (⌘+R)

5) In case you get a symbols not found error , go to settings of the main project , find framework search paths and add the following $(PROJECT_DIR)/../node_modules/react-native-razorpay/ios/

6) Also make sure the razorpay framework is added in the embedded binaries section and you have Always Embed Swift Standard Binaries set to yes in build settings.

I created a fresh react native project and tried this one but still not able to archive the build. It is working fine in debug mode.

Any help would be appreciated!

**Comment by nikhilboranaarit** [comment]
> @iThink32 I am also facing the same issue.
> 
> I have installed the latest razorpay node module using yarn and followed manual linking given below:
> 
> 1. In XCode, in the project navigator, right click Libraries ➜ Add Files to [your project's name]
> 2. Go to node_modules ➜ react-native-razorpay and add RazorpayCheckout.xcodeproj
> 3. In XCode, in the project navigator, select your project. Add libRazorpayCheckout.a to your project's Build Phases ➜ Link Binary With Libraries
> 4. Run your project (⌘+R)
> 5. In case you get a symbols not found error , go to settings of the main project , find framework search paths and add the following $(PROJECT_DIR)/../node_modules/react-native-razorpay/ios/
> 6. Also make sure the razorpay framework is added in the embedded binaries section and you have Always Embed Swift Standard Binaries set to yes in build settings.
> 
> I created a fresh react native project and tried this one but still not able to archive the build. It is working fine in debug mode.
> 
> Any help would be appreciated!
RNV : "react-native": "0.57.8",
"react-native-razorpay": "^2.0.19",
![screenshot 2019-02-05 at 6 14 38 pm](https://user-images.githubusercontent.com/39380554/52460342-ccee5580-2b8f-11e9-978c-6590d1af88a5.png)

im also facing the same issue and have placed a support request few days ago. "Your ticket number is #369371." still no response.

**Comment by iThink32** [comment]
@nikhilboranaarit @Jibin2015 have you tries the steps in this video?
https://youtu.be/HVGUBRot7VA

**Comment by nikhilboranaarit** [comment]
@iThink32, yes its enable, and I have tried both the script, but it didn't work.

**Comment by iThink32** [comment]
@nikhilboranaarit ok , are you free for a hangouts call?

**Comment by iThink32** [comment]
@nikhilboranaarit @Jibin2015 have a look at this link
https://medium.com/@heitorburger/static-libraries-frameworks-and-bitcode-6d8f784478a9
try setting -fembed-bitcode in the release mode of Other C flags of RazorpayCheckout.project and your main project.
Users of cocoa pods will not face this issue.

**Comment by atulmy** [comment]
<img width="683" alt="screenshot 2019-02-08 at 6 57 00 pm" src="https://user-images.githubusercontent.com/685786/52481093-95a19800-2bd3-11e9-801c-47f250c69593.png">

<img width="562" alt="screenshot 2019-02-08 at 6 58 27 pm" src="https://user-images.githubusercontent.com/685786/52481096-976b5b80-2bd3-11e9-9f4a-556ab716a43f.png">

Does not work. Still same error.

**Comment by iThink32** [comment]
@atulmy ok give us a day or two , will look into this and get back to you.

**Comment by iThink32** [comment]
@atulmy also make sure you set the setting on the project level not on the target level.

**Comment by atulmy** [comment]
Also send us screenshots with your suggestions.

**Comment by iThink32** [comment]
@atulmy have a look at the link , it is very well explained but nonetheless we will work on it and get back to you guys.

**Comment by atulmy** [comment]
> @atulmy ok give us a day or two , will look into this and get back to you.
@iThink32 any update?

**Comment by nikhilboranaarit** [comment]
@iThink32 we can have a call or Team Viewer session regarding this issue today.

**Comment by iThink32** [comment]
@nikhilboranaarit sure can you give me your gmail id?

**Comment by iThink32** [comment]
@nikhilboranaarit @Jibin2015 @atulmy we have fixed this issue from our end and released a new version on all our supported platforms. Please Update to version 2.0.20.

**Comment by Jibin2015** [comment]
Sure! Will try it & let you know the feedback and thanks for the support.

**Comment by Jibin2015** [comment]
@iThink32 Thank you so much. It worked for me.

**Comment by iThink32** [comment]
closing as this issue is fixed.

**Comment by ShrutiThakur01** [comment]
Hi ,

I am facing same issue and unable to release the app in Appstore. App is already in App Store and i want to release new version now. This issue is in my latest build . I am able to build the product and its also running properly on iOS devices.
When i select product==> archive then its showing as build failed.

ld: bitcode bundle could not be generated because '/Users/XXX/XXX/XXX/ios/Flutter/Flutter.framework/Flutter' was built without full bitcode. All frameworks and dylibs for bitcode must be generated from Xcode Archive or Install build file '/Users/XXX/XXX/XXX/ios/Flutter/Flutter.framework/Flutter' for architecture armv7

clang: error: linker command failed with exit code 1 (use -v to see invocation)

Please help.

Thanks,
shruti

**Comment by lalkrishna** [comment]
> @nikhilboranaarit @Jibin2015 @atulmy we have fixed this issue from our end and released a new version on all our supported platforms. Please Update to version 2.0.20.

how we can solve this issue on building framework? Im experiencing the same with another framework.

**Comment by cuirhong** [comment]
Before 'Archive'
```
flutter build ios --release
```
continue 'Archive'
