### ISSUE TITLE
Android 4.4: Payment option not working

### ISSUE THREAD

**Issue by Balasnest** [razorpay/react-native-razorpay#157]
Will this work `"react-native-razorpay": "2.0.18"` in android 4.4 version? Its not opening payment page. But getting OTP to my number.

```
   ext {
      buildToolsVersion = "27.0.3"
      minSdkVersion = 19
      compileSdkVersion = 27
      targetSdkVersion = 27
      supportLibVersion = "27.1.1"
     }
    subprojects {
        afterEvaluate {project ->
            if (project.hasProperty("android")) {
                android {
                    compileSdkVersion 27
                    buildToolsVersion '27.0.3'
                }
            }
        }
    }
```

1. what is the minSDK Version support?
2. In which lower version start works for android?

I have checked the same in RZP sample app from playstore. It's not opening the payment screen.

**Comment by Balasnest** [comment]
@sumedht @umanghome Is RZP working in Android 4.4? Are you able to see the payment page?

**Comment by sumedht** [comment]
@Balasnest Razorpay will only work on the devices which supports TLS 1.2 or devices above API level 19

**Comment by Balasnest** [comment]
@sumedht  okay. But there should be a meaningful message need to convey to the user for this case. How can we do this?

**Comment by vivekshindhe** [comment]
Closing this issue due to no response from your side. Please feel free to either re-open the issue or create a new issue if you have any additional queries.
