### ISSUE TITLE
No response after payment success/failure

### ISSUE THREAD

**Issue by mahesh-varkala** [razorpay/react-native-razorpay#160]
RN version 0.57.8.
react  16.6.3
react-native-razorpay  2.0.20 (tried previous version also)

ENV: Android 

Able to open the payment page and make a successful payment. But not getting payment Id. Not even getting an error/exception.

Used same code with live key. 
Kindly help me with the problem @iThink32 @mb-14  @hariramsvnit  @AbhinavArora95  @pronav

**Comment by Anujmoglix** [comment]
Is it working ?
