### ISSUE TITLE
dyld: Library not loaded: @rpath/libswiftCore.dylib error On Xcode 10.2

### ISSUE THREAD

**Issue by sivakumar-cf** [razorpay/react-native-razorpay#163]
Getting crash at app launch On Xcode 10.2
You might be required to support Swift 5 as well.
I am using this library from pod 'razorpay-pod'
```
  dyld: Library not loaded: @rpath/libswiftCore.dylib
  Referenced from: /Users/xxxx/Library/Developer/CoreSimulator/Devices/B482F16E-E739-43F7-ACEA-62C22E64F1C0/data/Containers/Bundle/Application/5B25C106-382B-46E6-B086-65B330100916/xxxxx.app/Frameworks/Razorpay.framework/Razorpay
  Reason: image not found
```

_Originally posted by @sivakumar-cf in https://github.com/razorpay/react-native-razorpay/issues/106#issuecomment-476589969_

**Comment by lokeshpayani7** [comment]
im also getting same issue after updating the latest XCODE 10.2

**Comment by philly25** [comment]
So looks like updating razorpay-pod version to 1.1.0 fixes the problem.

Just update your pods with `pod update`.

**Comment by sivakumar-cf** [comment]
Thanks, @philly25 will try
