### ISSUE TITLE
Razorpay dyId: library not loaded: @rpath/libswiftCore.dylib

### ISSUE THREAD

**Issue by saketverma008** [razorpay/react-native-razorpay#171]
dyld: Library not loaded: @rpath/libswiftCore.dylib
  Referenced from: /Users/*****/Library/Developer/CoreSimulator/Devices/31D95D6C-C8B7-4A63-A6FC-495CF7A074C8/data/Containers/Bundle/Application/72692746-9754-4DA1-B3B5-6644D184C97C/******.app/Frameworks/Razorpay.framework/Razorpay
  Reason: image not found

Razorpay: 2.0.20
Xcode: 10.2
React-native: 0.59
OS: 10.14.4

**Comment by kashishgrover** [comment]
Is there any update on this? I'm facing the same issue

**Comment by AbhinavArora95** [comment]
Hi apologise for the delay. We have released a new framework compiled in Swift 5 for Xcode 10.2 a few days back. We will be updating the framework in react-native.
