### ISSUE TITLE
iOS App Thinning issue

### ISSUE THREAD

**Issue by atulmy** [razorpay/react-native-razorpay#176]
I'm facing issues after uploading the archive to App Store. The archiving is successful however I received following email:

**Subject**: App Store Connect: Processing stopped for
**Body**
> While processing your iOS app, errors occurred in the app thinning process, and your app couldn’t be thinned. If your app contains bitcode, bitcode processing may have failed. Because of these errors, this build of your app will not be able to be submitted for review or placed on the App Store. For information that may help resolve this issue, see Tech Note 2432.

Generating a Production Ad-hoc build you can see the following error:
```
ipatool failed with an exception: #<CmdSpec::NonZeroExcitException: Command exited with pid 32911 exit 1:
/Applications/Xcode.app/Contents/Developer/usr/bin/bitcode-build-tool -v -t /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin --sdk /Applications/Xcode.app/Contents/Developer/Platforms/iPhoneOS.platform/Developer/SDKs/iPhoneOS12.2.sdk -o /var/folders/g0/b2xhk07s5fd1prhtxjzl2v0r0000gp/T/ipatool20190412-32687-1w4y6d4/thinned-out/armv7/Payload/example.app/Frameworks/Razorpay.framework/Razorpay --generate-dsym /var/folders/g0/b2xhk07s5fd1prhtxjzl2v0r0000gp/T/ipatool20190412-32687-1w4y6d4/thinned-out/armv7/Payload/example.app/Frameworks/Razorpay.framework/Razorpay.dSYM --strip-swift-symbols /var/folders/g0/b2xhk07s5fd1prhtxjzl2v0r0000gp/T/ipatool20190412-32687-1w4y6d4/thinned-in/armv7/Payload/example.app/Frameworks/Razorpay.framework/Razorpay
Stdout:
    Debug: SDK path: /Applications/Xcode.app/Contents/Developer/Platforms/iPhoneOS.platform/Developer/SDKs/iPhoneOS12.2.sdk
```
Development: Successful
Archiving: Successful
Publishing: Error

Xcode: 10.2
react-native: 0.59.4
react-native-razorpay: 2.0.20

CC: @pronav @iThink32

**Comment by atulmy** [comment]
@pronav @AbhinavArora95 @iThink32 any update on this? This issue is blocking our app release.

**Comment by atulmy** [comment]
@pronav @AbhinavArora95 @iThink32 any update on this? This issue is blocking our app release.

**Comment by atulmy** [comment]
@pronav @AbhinavArora95 @iThink32 any update on this? This issue is blocking our app release.

**Comment by pronav** [comment]
Can you try archiving locally to check if it's successful? Are you able to create .ipa build?

**Comment by prasad456** [comment]
@pronav @atulmy any update on this? This issue is blocking our app release
Are you build ipa file?

**Comment by pronav** [comment]
Which xcode and razorpay plugin version are you using? can you share the exact error you faced?

**Comment by RishavKumar-3796** [comment]
@pronav Why is this closed ?
I am also facing this same issue and this is the error response.

Assertion failed: Expected 4 archs in otool output:
/var/folders/ql/jt0twk5s2_9gzfzhzzy7gmxw0000gn/T/IDEDistributionOptionThinning.~~~ffvS09/Payload/FrendyAppDesign.app/Frameworks/Razorpay.framework/Razorpay:

Mach header
      magic cputype cpusubtype  caps    filetype ncmds sizeofcmds      flags
MH_MAGIC_64  X86_64        ALL  0x00       DYLIB    32       4544   NOUNDEFS DYLDLINK TWOLEVEL NO_REEXPORTED_DYLIBS
Load command 0

**Comment by vijendrapatidar** [comment]
ipatool failed with an exception: #<CmdSpec::NonZeroExitException: $ /Applications/Xcode.app/Contents/Developer/usr/bin/python3 /Applications/Xcode.app/Contents/Developer/usr/bin/bitcode-build-tool -v -t /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin -L /var/folders/sd/0fv3f63541g9lzncclc5wmnw0000gn/T/ipatool20221130-60955-1nk42qt/thinned-out/arm64/Payload/name.app/Frameworks --sdk /Applications/Xcode.app/Contents/Developer/Platforms/iPhoneOS.platform/Developer/SDKs/iPhoneOS15.5.sdk -o /var/folders/sd/0fv3f63541g9lzncclc5wmnw0000gn/T/ipatool20221130-60955-1nk42qt/thinned-out/arm64/Payload/name.app/Frameworks/Razorpay.framework/Razorpay --generate-dsym /var/folders/sd/0fv3f63541g9lzncclc5wmnw0000gn/T/ipatool20221130-60955-1nk42qt/thinned-out/arm64/Payload/name.app/Frameworks/Razorpay.framework/Razorpay.dSYM --strip-swift-symbols /var/folders/sd/0fv3f63541g9lzncclc5wmnw0000gn/T/ipatool20221130-60955-1nk42qt/thinned-in/arm64/Payload/name.app/Frameworks/Razorpay.framework/Razorpay
Status: pid 61607 exit 1
Stdout:
 
 
 Any help

**Comment by rajeshdgeekyants** [comment]
@pronav I am facing similar issue while generating AdHoc ipa from the Archive.

```
ipatool failed with an exception: #<CmdSpec::NonZeroExitException: $ /Applications/Xcode.app/Contents/Developer/usr/bin/python3 /Applications/Xcode.app/Contents/Developer/usr/bin/bitcode-build-tool -v -t /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin -L /var/folders/sk/nmvyy4ws26ngp_8b5853s1jw0000gn/T/ipatool20221226-15345-1nr6evp/thinned-out/arm64/Payload/myfojo.app/Frameworks --sdk /Applications/Xcode.app/Contents/Developer/Platforms/iPhoneOS.platform/Developer/SDKs/iPhoneOS15.5.sdk -o /var/folders/sk/nmvyy4ws26ngp_8b5853s1jw0000gn/T/ipatool20221226-15345-1nr6evp/thinned-out/arm64/Payload/myfojo.app/Frameworks/Razorpay.framework/Razorpay --generate-dsym /var/folders/sk/nmvyy4ws26ngp_8b5853s1jw0000gn/T/ipatool20221226-15345-1nr6evp/thinned-out/arm64/Payload/myfojo.app/Frameworks/Razorpay.framework/Razorpay.dSYM --strip-swift-symbols /var/folders/sk/nmvyy4ws26ngp_8b5853s1jw0000gn/T/ipatool20221226-15345-1nr6evp/thinned-in/arm64/Payload/myfojo.app/Frameworks/Razorpay.framework/Razorpay
Status: pid 18572 exit 1
Stdout:
```

react-native-razorpay: 2.2.8
react-native: 0.68.5
