### ISSUE TITLE
Build error Xcode 10.2: Incompatible Swift

### ISSUE THREAD

**Issue by sivakumar-cf** [razorpay/react-native-razorpay#177]
Getting the following build error on XCode 10.2.
I am using the react-native-razorpay version 2.1.0

`error: The following binaries use incompatible versions of Swift:
xxxx/Build/Products/iphonesimulator/xxx.app/Frameworks/Razorpay.framework/Razorpay`

**Comment by pronav** [comment]
Are you using swift5 or swift4.2?

**Comment by sivakumar-cf** [comment]
I am using swift 5 which is included in xCode 10.2.

**Comment by sandeep666** [comment]
Even I'm getting the same error after updating xCode to 10.2

**Comment by codebymani** [comment]
<img width="640" alt="Screenshot 2019-05-03 at 3 37 11 PM" src="https://user-images.githubusercontent.com/9837941/57131269-82106280-6db9-11e9-9703-7d1513f28c34.png">

Facing the same issue while bumping up Xcode to 10.2.1 and react-native-razorpay to 2.1.23.
Any Fix ??

**Comment by saketverma008** [comment]
error: binaries use incompatible versions of Swift..
Facing the same issue with react-native-razorpay 2.1.23. Expecting a quick fix.

**Comment by sivakumar-cf** [comment]
@pronav Any update on this?

**Comment by master96** [comment]
@codebymani any luck on issue ?

**Comment by pronav** [comment]
Can you verify if `Razorpay-swift.h` file included in `Razorpay.framework` starts with following line:

```
#include <TargetConditionals.h>
```

Secondly, have you added script to strip out unneeded architectures from binary?

**Comment by sivakumar-cf** [comment]
Yes, I have added the script to strip out unneeded architectures while archiving the app, but here I cannot build the app in development mode.

**Comment by sivakumar-cf** [comment]
@pronav  Any solution on this, waiting for a long time?

**Comment by ChintanAcharya** [comment]
If you've multiple xcode installed, make sure that version 10.2 is selected in Xcode command line tools in Preferences > Locations.

![image](https://user-images.githubusercontent.com/7722412/58465773-ff7b8880-8155-11e9-849b-a51e19ff8979.png)

**Comment by sivakumar-cf** [comment]
It is worked, Thanks for the help

**Comment by rawris** [comment]
I'm still facing this issue, I'm using only 1 xcode (10.2) with swift 5.1 and I have the same error

`error: The following binaries use incompatible versions of Swift: xxxx/Build/Products/iphonesimulator/xxx.app/Frameworks/Razorpay.framework/Razorpay`

**Comment by pronav** [comment]
We're looking into swift 5.1 support and will update here.

**Comment by rawris** [comment]
so can you suggest any other way to integrate razorpay in our React Native app? I need to integrate it for a client.

**Comment by master96** [comment]
any temporary fix untill team is working on swift 5.1 support

**Comment by master96** [comment]
React Native Environment Info:
    System:
      OS: macOS 10.14.5
      CPU: (4) x64 Intel(R) Core(TM) i5-5350U CPU @ 1.80GHz
      Memory: 28.34 MB / 8.00 GB
      Shell: 3.2.57 - /bin/bash
    Binaries:
      Node: 12.2.0 - /usr/local/bin/node
      npm: 6.9.0 - /usr/local/bin/npm
      Watchman: 4.9.0 - /usr/local/bin/watchman
    SDKs:
      iOS SDK:
        Platforms: iOS 12.2, macOS 10.14, tvOS 12.2, watchOS 5.2
      Android SDK:
        API Levels: 23, 26, 27, 28
        Build Tools: 28.0.3
    IDEs:
      Android Studio: 3.4 AI-183.6156.11.34.5522156
      Xcode: 10.2.1/10E1001 - /usr/bin/xcodebuild
    npmPackages:
      react: 16.5.0 => 16.5.0
      react-native: 0.57.0 => 0.57.0
    npmGlobalPackages:
      react-native-cli: 2.0.1

this is system info

**Comment by rawris** [comment]
Hi,

I just rechecked my swift version and It is `Apple Swift version 5.0.1 (swiftlang-1001.0.82.4 clang-1001.0.46.5)` which is the same swift version mentioned in Razorpay-Swift.h. any suggestions? 

This is the complete error

`
error: The following binaries use incompatible versions of Swift:
/Users/<username>/Library/Developer/Xcode/DerivedData/<App Name>/Build/Products/Debug-iphonesimulator/<app/>Frameworks/Razorpay.framework/Razorpay
/Users/<username>/Library/Developer/Xcode/DerivedData/<App Name>/Build/Products/Debug-iphonesimulator/<app.app>/<App>
`

**Comment by master96** [comment]
Download latest Razorpay.framework from Razorpay website with swift 5.0  and replace the one from node modules. This fixed error for me @rawris  @codebymani

**Comment by rawris** [comment]
Hi @master96 

Can you share the link with us? just so we use the same framework as you

**Comment by pronav** [comment]
This is the link for latest framework: https://rzp-mobile.s3.amazonaws.com/ios/checkout/1.2.0/RazorpayBitcodeX10.framework.zip

However just using latest `react-native-razorpay` plugin should've worked in first place.

**Comment by pronav** [comment]
We'll release swift-5.1 compatible framework once stable version for swift-5.1 is released by apple.

**Comment by rawris** [comment]
Hi @pronav 

I'm using swift 5.0 still I'm getting this error.

**Comment by master96** [comment]
> Hi @pronav
> 
> I'm using swift 5.0 still I'm getting this error.

I can confirm 

 "react-native-razorpay": "^2.0.18"
and 
https://rzp-mobile.s3.amazonaws.com/ios/checkout/1.2.0/RazorpayBitcodeX10.framework.zip
works fine with swift 5.0

**Comment by rawris** [comment]
> > Hi @pronav
> > I'm using swift 5.0 still I'm getting this error.
> 
> I can confirm
> 
> "react-native-razorpay": "^2.0.18"
> and
> https://rzp-mobile.s3.amazonaws.com/ios/checkout/1.2.0/RazorpayBitcodeX10.framework.zip
> works fine with swift 5.0

I'm using ^2.1.23 version. I'm downgrading it to 2.0.18 and will see how it works out

**Comment by Balasnest** [comment]
Facing this in xcode 11.3.1 and swfit version used in framework is 4.2

Any workaround for this?

**Comment by Nautiyalsachin** [comment]
Which react-native-razorpay are you using? Can you share the package version here? Thanks.
