### ISSUE TITLE
Not taking local Image path

### ISSUE THREAD

**Issue by sathvik12345** [razorpay/react-native-razorpay#178]
if i am giving local image path the image is not loading, but if  load image from network it is working fine

react-native: 0.50.4

rect-native-razorpay: 2.0.20

**Comment by pronav** [comment]
Try passing image as base64 string

**Comment by sathvik12345** [comment]
do i need to convert the image to base64 and pass on ?

**Comment by sathvik12345** [comment]
i tried convert the .png to base64 and passed to it but still its not working

**Comment by pronav** [comment]
You can either pass local image as `UIImage` instance. If passing string, it should either be in base64 format or a url from internet.

**Comment by sathvik12345** [comment]
base64 is working but `UIImage` instance is not working if give local path to it.

```
let options = {
      description: 'Credits towards consultation',
      UIImage: 'app/images/logo.png',
      currency: 'INR',
      key: 'rzp_test_5nvpgJkz0ruqSJ',
      amount: '5000',
      name: 'name',
      prefill: {
        email: email,
        contact: mobile,
        name: name
      },
      theme: { color: '#F37254' }
    };
```

**Comment by pronav** [comment]
By UIImage instance, I mean passing reference to image under the same key, i.e. image. something like this:

```
image: UIImage.init(contentsOfFile: imagePath)
...other options as before
```

**Comment by SanjaySargam** [comment]
@pronav 
getting this error
UIImage not recognised
