### ISSUE TITLE
New version fails too

### ISSUE THREAD

**Issue by GeekRishabh** [razorpay/react-native-razorpay#179]
With xcode 10.2 , React native 57.8 & also on 58.3 It is not working the build issue is mentioned below

<img width="687" alt="Screenshot 2019-04-17 at 12 15 35 PM" src="https://user-images.githubusercontent.com/23093075/56267070-67789100-610b-11e9-80c2-162b0e138b20.png">

**Comment by philly25** [comment]
It works for real device, but simulator build fails.

**Comment by rajaishwary** [comment]
facing same issue. Any update on this @AbhinavArora95 ?

**Comment by pronav** [comment]
We have updated the plugin to support both simulator and real devices.

**Comment by GeekRishabh** [comment]
New version bump fixed this issue. Thanks @pronav
