### ISSUE TITLE
Not installed

### ISSUE THREAD

**Issue by PARAGJYOTI** [razorpay/react-native-razorpay#18]
npm i react-native-razorpay not working . 
Says './download-ios_sdk.sh' is not a command

**Comment by akshaybhalotia** [comment]
Hi @PARAGJYOTI , please let us know the following:
react version
react native version
npm version

**Comment by PARAGJYOTI** [comment]
Yaa sure dude . I am having too much problem in building the package . It
didn't installed due to the postinstall command
'./download_ios_framwork.sh' on package.json .
So I cloned the library on node-modules and tries to link it by
react-native link , but failed to build . Manuall installation also doesn't
help .

I will check my versions out and let you know after sometime.

On 09-Mar-2017 12:31 PM, "Akshay Bhalotia" <notifications@github.com> wrote:

Hi @PARAGJYOTI <https://github.com/PARAGJYOTI> , please let us know the
following:
react version
react native version
npm version

—
You are receiving this because you were mentioned.
Reply to this email directly, view it on GitHub
<https://github.com/razorpay/react-native-razorpay/issues/18#issuecomment-285271834>,
or mute the thread

**Comment by PARAGJYOTI** [comment]
React : 15.4.2
React native : 0.41.2
Npm : 3.10.8
Sdk version : 25

**Comment by PARAGJYOTI** [comment]
Hi Akshay ,
  I finally made it . Actually react-native-razorpay needs 24.0.0
build-tools , which i didn't installed . I finally figured out and it
worked like charm. I love your interface .
  Razorpay is most developer freindly gateway in India.

**Comment by akshaybhalotia** [comment]
@PARAGJYOTI Glad you figured it out. I'm closing the issue for now. Feel free to reopen if you face any problems.

**Comment by ArcadeRenegade** [comment]
Hi @PARAGJYOTI, I am having the same issue. Did you need to install the build-tools for iOS to fix it? Not sure what I can do since I am running Windows 10 for development right now.
