### ISSUE TITLE
Crash on iOS when adding a credit/debit card

### ISSUE THREAD

**Issue by shanawarhasnain** [razorpay/react-native-razorpay#180]
Razorpay crashes when I try to add a new CC/DC or entry cvv to a saved card on the second try.

Repro steps:

Scenario 1:
Initiate Razorpay -> Cards -> Add another card -> click on card number -> press back (Cards) -> Goto Cards -> Add another card -> Click on card numeber --> Application crashed with: Thread 1: EXC_BAD_ACCESS (code=1, address=0x20).

Scenario 2:
Initiate Razorpay -> Cards -> click on cvv of saved card -> press back (Cards) -> Goto Cards -> click on cvv of saved card --> Application crashed with: Thread 1: EXC_BAD_ACCESS (code=1, address=0x20).

Tried to update version of razorpay and react-native to no avail. This is causing the app release to get delayed.

**Comment by pronav** [comment]
We had released a new version yesterday, can you update and check again?

**Comment by haxplorer** [comment]
Any updates on this, Razorpay team?

**Comment by Nautiyalsachin** [comment]
Closing this issue due to the time elapsed. Please feel free to either re-open the issue or create a
new issue if you have any additional queries.
