### ISSUE TITLE
Build error with xcode 10.2

### ISSUE THREAD

**Issue by samuelwilso** [razorpay/react-native-razorpay#181]
Getting below error
compiled with newer version of Swift language (unknown ABI version 0x07) than previous files (unknown ABI version 0x06) file 

Xcode version : 10.2
RN: 59.5
Razorpay: 2.1.3

**Comment by pronav** [comment]
You need to use `react-native-razorpay` 2.1.23, and also make sure you select xcode 10.2 as cli tool in xcode > preferences > locations
![58465773-ff7b8880-8155-11e9-849b-a51e19ff8979](https://user-images.githubusercontent.com/734840/58529139-35247e00-81f7-11e9-9bb2-b0237469d6b0.png)

**Comment by vivekshindhe** [comment]
Closing this issue due to no response from your side. Please feel free to either re-open the issue or create a new issue if you have any additional queries.
