### ISSUE TITLE
minSdkVersion 16 cannot be smaller than version 19

### ISSUE THREAD

**Issue by KakarN** [razorpay/react-native-razorpay#183]
I am would like to integrate Razorpay into my react-native app. I have installed the razorpay package and have also linked successfully. 

However, when I try to run the app I am getting the following errors:

```
$ react-native run-android

info Starting JS server...
info Building and installing the app on the device (cd android && ./gradlew app:installDebug)...

> Configure project :react-native-razorpay
WARNING: The specified Android SDK Build Tools version (26.0.3) is ignored, as it is below the minimum supported version (28.0.3) for Android Gradle Plugin 3.3.1.
Android SDK Build Tools 28.0.3 will be used.
To suppress this warning, remove "buildToolsVersion '26.0.3'" from your build.gradle file, as each version of the Android Gradle Plugin now has a default version of the build tools.

> Task :app:processDebugManifest FAILED
/Users/kakarnyori/react-native-projects/RazorpayTest/android/app/src/debug/AndroidManifest.xml Error:
        uses-sdk:minSdkVersion 16 cannot be smaller than version 19 declared in library [com.razorpay:checkout:1.5.5] /Users/kakarnyori/.gradle/caches/transforms-1/files-1.1/checkout-1.5.5.aar/a23f27ddc59bc933dbac2f4019e7fbab/AndroidManifest.xml as the library might be using APIs not available in 16
        Suggestion: use a compatible library with a minSdk of at most 16,
                or increase this project's minSdk version to at least 19,
                or use tools:overrideLibrary="com.razorpay" to force usage (may lead to runtime failures)

See http://g.co/androidstudio/manifest-merger for more information about the manifest merger.


FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':app:processDebugManifest'.
> Manifest merger failed : uses-sdk:minSdkVersion 16 cannot be smaller than version 19 declared in library [com.razorpay:checkout:1.5.5] /Users/kakarnyori/.gradle/caches/transforms-1/files-1.1/checkout-1.5.5.aar/a23f27ddc59bc933dbac2f4019e7fbab/AndroidManifest.xml as the library might be using APIs not available in 16
        Suggestion: use a compatible library with a minSdk of at most 16,
                or increase this project's minSdk version to at least 19,
                or use tools:overrideLibrary="com.razorpay" to force usage (may lead to runtime failures)

* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output. Run with --scan to get full insights.

* Get more help at https://help.gradle.org

BUILD FAILED in 1s
22 actionable tasks: 1 executed, 21 up-to-date
error Could not install the app on the device, read the error above for details.
Make sure you have an Android emulator running or a device connected and have
set up your Android development environment:
https://facebook.github.io/react-native/docs/getting-started.html
error Command failed: ./gradlew app:installDebug. Run CLI with --verbose flag for more details.
```
I have been using Expo to develop mobile apps, and I am very new to Android development. Could you please tell me how can I fix this?

**Comment by ratnadeep007** [comment]
@KakarN I faced same issue today while using Razorpay react-native package.
open `build.gradle` file in android folder and change the value of `minSdkVersion` from 16 to 19.
Hope this resolves your issue. 😄 
![sdk-version-fix-razorpay](https://user-images.githubusercontent.com/17860233/57009026-bb0dd300-6c11-11e9-8593-db318f58b3f2.JPG)

**Comment by KakarN** [comment]
@ratnadeep007 That did it! Thanks.

**Comment by SaravanakumarSubramanian** [comment]
I have the same issue changing the minSDKVersion to 19 did not solve the issue for me

> Error: Command failed: ./gradlew app:installDebug -PreactNativeDevServerPort=8081
> /Users/**/android/app/src/debug/AndroidManifest.xml Error:
>         uses-sdk:minSdkVersion 16 cannot be smaller than version 19 declared in library [:react-native-razorpay] /Users/**/node_modules/react-native-razorpay/android/build/intermediates/library_manifest/debug/AndroidManifest.xml as the library might be using APIs not available in 16
>         Suggestion: use a compatible library with a minSdk of at most 16,
>                 or increase this project's minSdk version to at least 19,
>                 or use tools:overrideLibrary="com.razorpay.rn" to force usage (may lead to runtime failures)
> 
> FAILURE: Build failed with an exception

Razorpay gradle
`apply plugin: 'com.android.library'
repositories {
    mavenCentral()
}
def safeExtGet(prop, fallback) {
    rootProject.ext.has(prop) ? rootProject.ext.get(prop) : fallback
}

android {
    compileSdkVersion safeExtGet('compileSdkVersion', 28)


    defaultConfig {
        minSdkVersion 19
        targetSdkVersion safeExtGet('targetSdkVersion', 28)
        versionCode 1
        versionName "1.0"
    }
}

dependencies {
    implementation 'com.facebook.react:react-native:+'
    implementation 'com.razorpay:checkout:1.5.12'
}

`

**Comment by realabbas** [comment]
> I have the same issue changing the minSDKVersion to 19 did not solve the issue for me
> 
> > Error: Command failed: ./gradlew app:installDebug -PreactNativeDevServerPort=8081
> > /Users/**/android/app/src/debug/AndroidManifest.xml Error:
> > uses-sdk:minSdkVersion 16 cannot be smaller than version 19 declared in library [:react-native-razorpay] /Users/**/node_modules/react-native-razorpay/android/build/intermediates/library_manifest/debug/AndroidManifest.xml as the library might be using APIs not available in 16
> > Suggestion: use a compatible library with a minSdk of at most 16,
> > or increase this project's minSdk version to at least 19,
> > or use tools:overrideLibrary="com.razorpay.rn" to force usage (may lead to runtime failures)
> > FAILURE: Build failed with an exception
> 
> Razorpay gradle
> 
> ```
> apply plugin: 'com.android.library'
> repositories {
>     mavenCentral()
> }
> def safeExtGet(prop, fallback) {
>     rootProject.ext.has(prop) ? rootProject.ext.get(prop) : fallback
> }
> 
> android {
>     compileSdkVersion safeExtGet('compileSdkVersion', 28)
> 
> 
>     defaultConfig {
>         minSdkVersion 19
>         targetSdkVersion safeExtGet('targetSdkVersion', 28)
>         versionCode 1
>         versionName "1.0"
>     }
> }
> 
> dependencies {
>     implementation 'com.facebook.react:react-native:+'
>     implementation 'com.razorpay:checkout:1.5.12'
> }
> ```
You don't have to change the razorpay module build.gradle file. 

Change your project level **build.gradle file**

**Comment by realabbas** [comment]
Change your project level **build.gradle** file.

```
buildscript {
    ext {
        buildToolsVersion = "28.0.3"
        minSdkVersion = 19
        compileSdkVersion = 28
        targetSdkVersion = 28
    }
```

Change the minimum sdk version to 19

**Comment by pratham-stack** [comment]
Downgrade your version 'audioplayers: ^0.17.1' to 'audioplayers: ^0.16.1' in pubspec.yaml and pub get the dependencies of 'audioplayers: ^0.16.1'.
