### ISSUE TITLE
React Native RazorPay android Undefined|Undefiend showing when click pay Button

### ISSUE THREAD

**Issue by jairock97** [razorpay/react-native-razorpay#184]
i```
mport React, { Component } from 'react';
import {
  AppRegistry,
  StyleSheet,
  Text,
  View,
  TouchableHighlight,
  NativeModules,
  NativeEventEmitter
} from 'react-native';

import RazorpayCheckout from 'react-native-razorpay';

class example extends Component {

  render() {
    return (
      <View style={styles.container}>
      <TouchableHighlight onPress={() => {
        var options = {
          description: 'Credits towards consultation',
          image: 'https://i.imgur.com/3g7nmJC.png',
          currency: 'INR',
          key: 'rzp_test_1DP5mmOlF5G5ag',
          amount: '5000',
          external: {
            wallets: ['paytm']
          },
          name: 'foo',
          prefill: {
            email: 'akshay@razorpay.com',
            contact: '8955806560',
            name: 'Akshay Bhalotia'
          },
          theme: {color: '#F37254'}
        }
        RazorpayCheckout.open(options).then((data) => {
          // handle success
          alert(`Success: ${data.razorpay_payment_id}`);
        }).catch((error) => {
          // handle failure
          alert(`Error: ${error.code} | ${error.description}`);
        });
        RazorpayCheckout.onExternalWalletSelection(data => {
          alert(`External Wallet Selected: ${data.external_wallet} `);
        });
      }}>
      <Text style = {styles.text}>PAYx</Text>
      </TouchableHighlight>
      </View>
    );
  }

}

const styles = StyleSheet.create({
  container: {
    flex: 1,
    justifyContent: 'center',
    alignItems: 'center',
    backgroundColor: '#F5FCFF',
  },
  text: {
    fontSize: 20,
    fontWeight: 'bold',
  }
});

AppRegistry.registerComponent('SampleProject', () => example);
```
Its showing Error : Undefiend| Unefiend.

**Comment by anusrivas** [comment]
Hi @jairock97 ... any updates on this ... we also have a similar issue.

**Comment by cullsin** [comment]
Seems like a node module error. It's could not find the module RazorpayCheckout. Any help

**Comment by reomind** [comment]
same error here
any resolution @ChinmayaRazorpay  @vyrazorpay

**Comment by amrit-sahoo** [comment]
Hi, I am also getting the same error. But in some particular devices. I tested on Android 4.4. I run the example code got the error alert with error code and message as undefined | undefined. I have tested in 4-5 devices. Got this error in 2 devices.

**Comment by ashwingattani** [comment]
Anybody got any luck on this?

**Comment by PriyaKailash** [comment]
I am facing same error undefined (**"TypeError: null is not an object(evaluating '_reactNative.NativeModules.RazorpayCheckout.open')"**) in react-native( expo detach ) on windows. is their any solution

**Comment by Nautiyalsachin** [comment]
Hi @PriyaKailash, we don't support Expo as mentioned in [Readme](https://github.com/razorpay/react-native-razorpay#things-to-be-taken-care).

**Comment by Nautiyalsachin** [comment]
Hi everybody, please update your package to the latest one, i.e. react-native-razropay 2.1.32. 

Closing this issue due to time elapsed, feel free to reopen it or create a new issue for any other query.

**Comment by akhilsanker** [comment]
Hi @Nautiyalsachin,
Facing the same issue in 2.1.33. Any solution?

**Comment by raghava** [comment]
I followed Step-2 to 4 from https://razorpay.com/docs/payment-gateway/react-native-integration/standard/android/
That helped me resolve the issue.

**Comment by goblin645272** [comment]
> I followed Step-2 to 4 from https://razorpay.com/docs/payment-gateway/react-native-integration/standard/android/ That helped me resolve the issue.

I followed the steps still i am getting the issue
