### ISSUE TITLE
Cannot read property 'buildConfigurationList' of undefined

### ISSUE THREAD

**Issue by nirjack** [razorpay/react-native-razorpay#188]
Still facing the issue...

closing this issue , please reopen if you still face this issue.

_Originally posted by @iThink32 in https://github.com/razorpay/react-native-razorpay/issues/68#issuecomment-382641574_

**Comment by pronav** [comment]
Which Android SDK, React Native and Razorpay version are you using?

**Comment by vivekshindhe** [comment]
Closing this issue due to no response from your side. Please feel free to either re-open the issue or create a new issue if you have any additional queries.
