### ISSUE TITLE
Incompatible Swift version (unknown ABI version 0x07) 

### ISSUE THREAD

**Issue by knalliyappan** [razorpay/react-native-razorpay#189]
I'm getting the below error while run in iOS:

Razorpay compiled with newer version of Swift language (unknown ABI version 0x07) than previous files (unknown ABI version 0x06) 

clang: error: linker command failed with exit code 1 (use -v to see invocation)

Platform Version:
    react-native: "0.56.0",
    X code : 10.1

Attached the screenshot for your reference.
![ScreenShot](https://user-images.githubusercontent.com/48433441/58304740-20b93d80-7e13-11e9-9db0-8bf4d35932f4.png)

**Comment by pronav** [comment]
Try using version 2.0.20 of razorpay react native package, current one works with xcode10.2 only.

**Comment by knalliyappan** [comment]
In lower version razorpay react native package is possible to run in xcode 10.1?

**Comment by pronav** [comment]
Yes, it's possible

**Comment by pronav** [comment]
version 2.0.20 should work.

**Comment by knalliyappan** [comment]
I'm tried version 2.0.20 in xcode 10.1. Above mention error only occurs.

**Comment by pronav** [comment]
Can you verify if `Razorpay-swift.h` file starts with following:
```
// Generated by Apple Swift version 4.2.1
```

**Comment by knalliyappan** [comment]
It's working fine in version 2.0.20.
