### ISSUE TITLE
FrameWork not found Razorpay

### ISSUE THREAD

**Issue by getinfyKiranreddy** [razorpay/react-native-razorpay#190]
When I follow this razorpay documentation I did manual installations in IOS I got some thing error like framework not found in Razorpay 

I have added frame work path search path and frame work also, but still I got that error framework not found 

Xcode version : 10.2.1,
Razorpay : ^2.1.23,
React-native : 0.57

Can you help me out ?

**Comment by pronav** [comment]
Is `Razorpay.framework` present in embedded libraries section?

**Comment by getinfyKiranreddy** [comment]
yes 
Thanks It works
