### ISSUE TITLE
App crashes on launch with error dyld`__abort_with_payload:

### ISSUE THREAD

**Issue by prashantsingh0205** [razorpay/react-native-razorpay#191]
I followed the following instructions to integrate the package.
https://razorpay.com/docs/payment-gateway/integrations-guide/mobile/ios/standard/integration-videos/#integrate-the-sdk-using-react-native

Steps I followed:
- added project manually to Libraries
![Screenshot 2019-05-27 at 10 22 26 AM](https://user-images.githubusercontent.com/20293520/58432904-96b6e200-8069-11e9-99d5-6ff3ab0f5b31.png)

- added librazorpaycheckout.a to 'Link Binary With Libraries'
![Screenshot 2019-05-27 at 10 22 40 AM](https://user-images.githubusercontent.com/20293520/58432922-aa624880-8069-11e9-98bb-c500873c742b.png)

-added framework to 'Embedded Libraries'
![Screenshot 2019-05-27 at 10 21 51 AM](https://user-images.githubusercontent.com/20293520/58433006-fad9a600-8069-11e9-8fd6-d9bba9a275dd.png)

- Changed 'Always Embed Swift Standard Libraries' to Yes
![Screenshot 2019-05-27 at 10 20 18 AM](https://user-images.githubusercontent.com/20293520/58433030-0e850c80-806a-11e9-8a89-ccdba1da693a.png)

The project builds successfully but gets crashed after launch screen with the following error as seen in attached attached.

![Screenshot 2019-05-27 at 10 12 39 AM](https://user-images.githubusercontent.com/20293520/58432646-3ffcd880-8068-11e9-9bd0-11d0d1bccb77.png)

![Screenshot 2019-05-27 at 10 06 00 AM](https://user-images.githubusercontent.com/20293520/58432650-4723e680-8068-11e9-915d-82b42fd734c0.png)

Any configuration that I missed?

MacOS - 10.14
Xcode - 10.1 (10B61)
React Native - 0.59.6
React Native Razorpay - 2.1.23

**Comment by pronav** [comment]
You need to either update xcode to 10.2, or downgrade react-native-razorpay package to 2.0.20. Latest plugin version works is not compatible with xcode 10.1

**Comment by pronav** [comment]
Also, if you've multiple xcode installed, make sure that correct version is selected in Xcode command line tools in Preferences > Locations.

![58465773-ff7b8880-8155-11e9-849b-a51e19ff8979](https://user-images.githubusercontent.com/734840/58467582-9dbd1d80-8159-11e9-957f-150a2a9874dc.png)

**Comment by prashantsingh0205** [comment]
@pronav I was able to build and run the app successfully. It worked by using the version 2.0.20
Now I encountered issue while archive distribution. The archive was created successfully but when I validated I got the following error.

![Screenshot 2019-05-29 at 8 51 53 AM](https://user-images.githubusercontent.com/20293520/58527363-ed4e2880-81ef-11e9-9a0b-d71df2b28d7b.png)
 
I followed this article http://ikennd.ac/blog/2015/02/stripping-unwanted-architectures-from-dynamic-libraries-in-xcode/ as shown in https://razorpay.com/docs/ios/integration-videos/#create-an-app-archive 

Please help!

MacOS - 10.14
Xcode - 10.1 (10B61)
React Native - 0.59.6
React Native Razorpay - 2.0.20

**Comment by pronav** [comment]
Under build phases, stripping step should be last step, or at least be after "embed binaries" step

**Comment by pronav** [comment]
Also, can you post actual error from "show logs"?

**Comment by prashantsingh0205** [comment]
@pronav Thanks a ton!! Dragging it to the last did the work. Thank you once again!!

**Comment by Biplovkumar** [comment]
Plz provide solutions for this code signing error.
