### ISSUE TITLE
Unable to link manually as well

### ISSUE THREAD

**Issue by mdmoin7** [razorpay/react-native-razorpay#193]
React native link is not working, as per the documentation tried to link manually, but receiving below errors

* Where:
Build file '/Users/admin/Desktop/Projects/payment-app/android/app/build.gradle' line: 9

* What went wrong:
A problem occurred evaluating project ':app'.
> Could not find method compile() for arguments [project ':react-native-razorpay'] on object of type org.gradle.api.internal.artifacts.dsl.dependencies.DefaultDependencyHandler.

**Comment by prashantsingh0205** [comment]
@mdmoin7 for android it's recommended to do auto link using `react-native link react-native-razorpay`
Auto linking throws error in iOS mostly.

**Comment by mdmoin7** [comment]
Agreed with the fact that it's the Ios Creating the problem when I try to link using mac os. But as per the recommendation In that case manual linking has been suggested, which doesn't work either. I tried manual linking and building for Android but that also seems to be throwing an error, as you can see in my initial thread

**Comment by pronav** [comment]
Post the versions for react-native, razorpay plugin and andriod sdk you're using

**Comment by venky2604** [comment]
is autolinking supported  rn  0.60

**Comment by sumedht** [comment]
@venky2604 Currently we are using react-native v0.57. Autolinking is supported from v0.60

**Comment by Nautiyalsachin** [comment]
@venky2604 : Auto Linking is supported now in the latest version i.e. 2.1.32. 

Closing this issue due to the time elapsed. Please feel free to either re-open the issue or create a 
new issue if you have any additional queries.
