### ISSUE TITLE
Code signing "Razorpay.framework" failed.(React Native )

### ISSUE THREAD

**Issue by metizror** [razorpay/react-native-razorpay#194]
![Screenshot 2019-05-30 at 7 22 53 PM](https://user-images.githubusercontent.com/8925045/58637656-95f3a980-8310-11e9-8445-ee8b4bb913ee.png)

xcode 10.2
its working in device but while publish to app store it show this error.

please help

**Comment by pronav** [comment]
You need to add a step in build phases to strip out simulator architectures. You can copy-paste this code from various places over the internet, e.g. https://stackoverflow.com/questions/42641806/check-and-remove-unsupported-architecture-x86-64-i386-in-ipa-archive

Please note that this step should be after embed binary step.

**Comment by metizror** [comment]
@pronav Thanks its Works..

**Comment by Biplovkumar** [comment]
lipo -remove i386 Razorpay -o Razorpay && lipo -remove x86_64 Razorpay -o Razorpay

hi @pronav i run this command but still in app upload showing this error , i am stuck from 2 days.
![Screenshot 2019-08-28 at 10 05 24 AM](https://user-images.githubusercontent.com/30401136/63841069-bbd82b00-c99f-11e9-8931-1ca8c88dabcf.png)

My valid architecture is this :- 
![Screenshot 2019-08-28 at 12 57 39 PM](https://user-images.githubusercontent.com/30401136/63841099-cc88a100-c99f-11e9-9f91-0b6aa33b1980.png)

**Comment by Biplovkumar** [comment]
No reply came for this issue,which came in upload app on app store.
Silent community library.
