### ISSUE TITLE
App get crash in iPad

### ISSUE THREAD

**Issue by knalliyappan** [razorpay/react-native-razorpay#195]
App get crashed in iPad but working in iPhone and Android.

-> Added the warning: 
could not execute support code to read Objective-C class data in the process. This may reduce the quality of type information available.

Version:
react-native-razorpay = "2.1.20",
react-native =  "0.56.0",
Xcode = 10.1,

Attached the screenshot for references
![Screen Shot](https://user-images.githubusercontent.com/48433441/58640770-6b591f00-8317-11e9-8c0d-df4c68fa37eb.png)
:

**Comment by pronav** [comment]
plugin version 2.1.x works with xcode 10.2. For xcode 10.1, please downgrade razorpay plugin to version 2.0.20

**Comment by knalliyappan** [comment]
It's working fine in Version 2.0.20.
