### ISSUE TITLE
iPhone / iPad version 10.3 crashed.

### ISSUE THREAD

**Issue by knalliyappan** [razorpay/react-native-razorpay#196]
In iPhone / iPad version 10.3 devices get crashed in library line 
" [razorpay open:options]"

Xcode version : 10.1
react-native-razorpay: 2.0.20

**Comment by pronav** [comment]
Try setting "always embed swift standard libraries" under build settings to "yes"

**Comment by knalliyappan** [comment]
I have already enabled "always embed swift standard libraries" to YES.
But its works in iOS 11 & 12 versions, But only crashed in iOS less-than 10.3.
![Screen Shot 2019-06-07 at 3 20 52 PM copy](https://user-images.githubusercontent.com/48433441/59096859-9eb03500-8939-11e9-806d-15de1bcc9b55.png)

Attached the screen shot for your reference.

**Comment by Nautiyalsachin** [comment]
Closing this issue due to the time elapsed. Please feel free to either re-open the issue or create a 
new issue if you have any additional queries.
