### ISSUE TITLE
iOS payment.open always returns with error code 1. 

### ISSUE THREAD

**Issue by vogosamvelraja** [razorpay/react-native-razorpay#198]
We are trying to integrate razor pay with our application. 
We were using the android SDK which worked fine, When we tried to use the same config in React native sdk it throws with the error above.

This is blocking our release. Kindly give us your support.

**Comment by pronav** [comment]
Please post code you're using around open method.. are there any delay in error or it returns as soon as called?

**Comment by vogosamvelraja** [comment]
@pronav  Thanks for the quick response. It worked now. It was a configuration problem I guess.
