### ISSUE TITLE
app crashes in production in  app review  process

### ISSUE THREAD

**Issue by vikaskhandekar001** [razorpay/react-native-razorpay#200]
xcode version:10.2.1
react-native-razorpay:2.1.23
react-native:0.58.5

App is working fine in development but it crashes (launch screen) in apple's review process.

i have added run script code inside build phase and  always embedded libraries are also set to "yes"   as you have suggested
below is the screenshot of error:

![Screenshot 2019-06-17 at 12 15 16 PM](https://user-images.githubusercontent.com/32407723/59583804-044eaf00-90fa-11e9-92f4-c000bcc62f97.png)

**Comment by pronav** [comment]
Please see https://github.com/razorpay/react-native-razorpay/issues/194#issuecomment-497368029 if it helps. You need to strip out simulator architectures before shipping app.

**Comment by vikaskhandekar001** [comment]
i am not getting error while archieving . when  apple is reviewing our app it is getting crashed on launchscreen .
 i have added run script and added code for it inside build phase. 
![Screenshot 2019-06-17 at 12 59 58 PM](https://user-images.githubusercontent.com/32407723/59586171-e4ba8500-90ff-11e9-8f6f-b2d0d0027b66.png)

**Comment by pronav** [comment]
`Razorpay.framework` is added multiple times in your project - can you remove duplicates?

**Comment by vikaskhandekar001** [comment]
i have kept Razorpay.framework which is inside the library and deleted other .will this work?

**Comment by pronav** [comment]
Yeah - use the one added by react-native plugin only.

**Comment by vikaskhandekar001** [comment]
now after uploading  build i am getting 
"this build is invalid" error
description:
ITMS-90562: Invalid Bundle - One or more dynamic libraries that are referenced by your app are not present in the dylib search path.

**Comment by vikaskhandekar001** [comment]
razorpay.framework is appearing twice in your integration video as well one inside of project and second one is in library section  and it is working fine.
can you send your contact details so we can resolve it earliest?

**Comment by pronav** [comment]
sure, contact me at pranav.gupta@razorpay.com

**Comment by rawris** [comment]
Hi @pronav 

Can I also contact you on your e-mail regarding an issue with this library?

**Comment by pronav** [comment]
Sure @rawris

**Comment by vikaskhandekar001** [comment]
i have taken new release but still apple rejected my app saying it  crashed on launchscreen .they have given me log of crash .which is here [https://codeshare.io/5zJbBO](https://codeshare.io/5zJbBO)

**Comment by bestkanthed** [comment]
I am have the same issue!

**Comment by Nautiyalsachin** [comment]
Closing this issue due to the time elapsed. Please feel free to either re-open the issue or create a 
new issue if you have any additional queries.
