### ISSUE TITLE
Do not find .podspec file

### ISSUE THREAD

**Issue by sujalbinno** [razorpay/react-native-razorpay#202]
I want to use react-native-razorpay from cocoa pod but I do not find any .podspec file in react-native-razorpay folder.

**Comment by pronav** [comment]
You can install it using npm

**Comment by sujalbinno** [comment]
I want to move RazorpayCheckout.xcodeproj project from "Library" folder to inside Pod 
Usually all library have its own .podspec file (like RazorpayCheckout,podspec) using it I can specify podspecification path in my pod file and when I run "pod  install" it will take reference of react-native-razorpay from the node_module

**Comment by sivakumar-cf** [comment]
Hi after upgrade to react-native 0.60+, all dependency project moved under cocoapods, so please add the podspec file for auto-linking. Refer here https://github.com/react-native-community/cli/blob/master/docs/autolinking.md

**Comment by Nautiyalsachin** [comment]
Hi @sujalbinno, @sivakumar-cf : We have updated our Razorpay package to 2.1.32, which supports Autolinking please updated it to that and let me know your response.
