### ISSUE TITLE
Assemble not working with :react-native:0.20.+.

### ISSUE THREAD

**Issue by raikva-curefit** [razorpay/react-native-razorpay#204]
facing this error while assembling for curefit app.

  > Could not resolve com.facebook.react:react-native:0.20.+.
    Required by:
        project :app > project :react-native-razorpay
     > Failed to list versions for com.facebook.react:react-native.

Please update react-native version to the latest.

from implementation 'com.facebook.react:react-native:0.20.+'
to  implementation 'com.facebook.react:react-native:+'

It has only changes in RazorpayPackage class. Everything should be fine.

**Comment by sumedht** [comment]
@raikva-curefit It's updated in latest version.
