### ISSUE TITLE
Min SDK version issue

### ISSUE THREAD

**Issue by pateljaykesh** [razorpay/react-native-razorpay#214]
hello

I am getting following error.

Manifest merger failed : uses-sdk:minSdkVersion 16 cannot be smaller than version 19 declared in library [com.razorpay:checkout:1.5.2] 

As we go with minsdk version 19 then app not working for older devices. 

Kindly help on this.

Thanks

**Comment by venky2604** [comment]
I have the same issue in rn 0.60.5

**Comment by SaravanakumarSubramanian** [comment]
I have the same issue changing the minSDKVersion to 19 did not solve the issue for me

Error: Command failed: ./gradlew app:installDebug -PreactNativeDevServerPort=8081
/Users//android/app/src/debug/AndroidManifest.xml Error:
uses-sdk:minSdkVersion 16 cannot be smaller than version 19 declared in library [:react-native-razorpay] /Users//node_modules/react-native-razorpay/android/build/intermediates/library_manifest/debug/AndroidManifest.xml as the library might be using APIs not available in 16
Suggestion: use a compatible library with a minSdk of at most 16,
or increase this project's minSdk version to at least 19,
or use tools:overrideLibrary="com.razorpay.rn" to force usage (may lead to runtime failures)

FAILURE: Build failed with an exception

Razorpay gradle

apply plugin: 'com.android.library'
repositories {
    mavenCentral()
}
def safeExtGet(prop, fallback) {
    rootProject.ext.has(prop) ? rootProject.ext.get(prop) : fallback
}

android {
    compileSdkVersion safeExtGet('compileSdkVersion', 28)


    defaultConfig {
        minSdkVersion 19
        targetSdkVersion safeExtGet('targetSdkVersion', 28)
        versionCode 1
        versionName "1.0"
    }
}

dependencies {
    implementation 'com.facebook.react:react-native:+'
    implementation 'com.razorpay:checkout:1.5.12'
}

**Comment by venky2604** [comment]
try changing minSdkVersion to 19  only in the outermost build.gradle. Do not change Razorpay gradle
