### ISSUE TITLE
Razor pay not working in react native >=0.60

### ISSUE THREAD

**Issue by lohithananda** [razorpay/react-native-razorpay#219]
Since react native link(native library)command is not working now in latest versions even if we link this library it's gives error as native module not imported. and we need pods to use it in iOS.

**Comment by varunsdcet** [comment]
Use this npm i  react-native-razorpay@2.0.18

**Comment by HarshitMadhav** [comment]
@varunsdcet Thanks it is working for me now!

**Comment by varunsdcet** [comment]
@lohithananda what are problem you facing if its urgent please install npm i react-native-razorpay@2.0.18 otherwise you wait untill any update its worked for me.

**Comment by Anujmoglix** [comment]
Hi , I am getting issue 
Haste module naming collision , duplicate module name : react-animated

**Comment by ChintanAcharya** [comment]
@Anujmoglix What version of react-native-razorpay are you on?

**Comment by varunsdcet** [comment]
> Hi , I am getting issue
> Haste module naming collision , duplicate module name : react-animated
Please go to nodemodule then react-native rajorpay then you see there is nodemodule inside this.please remove this

**Comment by varunsdcet** [comment]
@Anujmoglix your issue is solved or not

**Comment by Anujmoglix** [comment]
yes , It is fixed .

**Comment by IamDhana** [comment]
Is this issue fixed in the latest version or still we need to use the 2.0.18 version of react-native?

**Comment by mamta-deswal** [comment]
Razor pay not working in react-native version 0.61.5. Android app crash on razorpayCheckout.open.
 var options = {
      description: 'Credits towards consultation',
      currency: 'INR',
      key_id: 'my key id',
      amount: '5000',
      email: 'mamta.d55@test.com',
      contact: '999999999',
      method: 'netbanking',
      bank: 'HDFC'
  
    }
    RazorpayCheckout.open(options).then((data) => {
      // handle success
      alert(`Success: ${data.razorpay_payment_id}`);
    }).catch((error) => {
      // handle failure
      alert(`Error: ${error.code} | ${error.description}`);
    });

**Comment by knifedge** [comment]
I am facing same issue as @mamta-deswal. Any solution ?

**Comment by Nautiyalsachin** [comment]
Hi Guys, we have updated our package to 2.1.32 which supports Auto linking and it also supports 0.60+ react-native versions. Please follow the updated readme. 

Closing this issue due to the time elapsed. Please feel free to either re-open the issue or create a 
new issue if you have any additional queries.
