### ISSUE TITLE
Always getting  dyld: Library not loaded: @rpath/libswiftCore.dylib

### ISSUE THREAD

**Issue by rameshkec85** [razorpay/react-native-razorpay#221]
dyld: Library not loaded: @rpath/libswiftCore.dylib
  Referenced from: /Users/ramesh-android-dev/Library/Developer/CoreSimulator/Devices/60D884D8-C0A2-4199-8BE0-BA1DCBA8F6FF/data/Containers/Bundle/Application/50BDFA33-B6B2-4E52-8AED-DCFF328C553A/TestRazorPay.app/Frameworks/Razorpay.framework/Razorpay
  Reason: image not found

Since 2 days i have been trying to run sample project by following manual steps and automatic linking. 

xCode: 10.1
react-native: 0.60.5
"react-native-razorpay": "^2.1.30",

Can anyone help me on this ?

**Comment by Nautiyalsachin** [comment]
Please follow these steps to resolve :- 

1. Check if is there any framework available in **Project** > **Target** > **Frameworks, Libraries, and Embedded Content.**. If its not already added then add it from YOUR_PROJECT_DIR/plugins/com.razorpay.cordova/src/ios/Razorpay.framework
to your embedded binaries phase.
2. If Razorpay.Framework is available then Change Embed to **Embed & Sign** from **Do Not Embed**
In build settings make sure that you have set Always Embed Swift Standard Libraries to yes.

**Comment by nirunisha123** [comment]
I am also getting this problem.

**Comment by tejas-freo** [comment]
I am also facing the same issue. I Have tried the steps mentioned above still, the  issue persist

**Comment by Nautiyalsachin** [comment]
We have released the latest version react-native-razorpay 2.1.32 which supports Auto Linking. 

Closing this issue due to the time elapsed. Please feel free to either re-open the issue or create a
new issue if you have any additional queries.
