### ISSUE TITLE
razor pay carshing app  in iOS react-native

### ISSUE THREAD

**Issue by nirunisha123** [razorpay/react-native-razorpay#224]
dyld: Library not loaded: @rpath/Razorpay.framework/Razorpay
  Referenced from: /var/containers/Bundle/Application/346257FF-098C-48D3-93C4-920465BB8DCC/mindhouse.app/mindhouse
  Reason: image not found

**Comment by neonsec** [comment]
facing the same issue on React Native 0.61.2

**Comment by prateekchachra** [comment]
+1

**Comment by Nautiyalsachin** [comment]
Try updating Razorpay plugin and also ensure that you have the framework added in **Frameworks, Libraries, and Embed Content** under **Target settings** - **General**. Change Embed status from - **'Do not Embed'** to **'Embed & Sign'**.

**Comment by amalantony** [comment]
@Nautiyalsachin I don't find an option called RazorPay framework in the list to add under Frameworks, Libraries, and Embed Content. I've tried adding libRazorpayCheckout.a to the list but I get the image not found error. 

![image](https://user-images.githubusercontent.com/1932506/70421678-44cb2c00-1a90-11ea-8a21-cbc47dc3171f.png)

**Comment by amalantony** [comment]
Okay, got this issue resolved.

 Basically in **Frameworks, Libraries, and Embed Content** under **Target settings - General** click on `+`.  In the popup, click on Add Other -> Add Files. Then navigate to `node_modules/react-native-razorpay /ios` and select the Razorpay.framework folder. Then do the build again with Command - r. 

This should fix the issue.

**Comment by Nautiyalsachin** [comment]
Also, try to install the latest version of react-native-razorpay, it enables Auto-linking.
