### ISSUE TITLE
Invariant Violation: Native module cannot be null.

### ISSUE THREAD

**Issue by sandeepsingh91** [razorpay/react-native-razorpay#227]
Unhandled JS Exception: Invariant Violation: Module AppRegistry is not a registered callable module (calling runApplication)

**Comment by yurkagon** [comment]
Any ideas?

**Comment by misaalturakhia** [comment]
You need to run react-native link react-native-razorpay

**Comment by chandrasekarvogo** [comment]
what is the solution

**Comment by maskedTitan** [comment]
@chandrasekarvogo As mentioned above you'd have to manually link razorpay using `react-native link react-native-razorpay`
