### ISSUE TITLE
 linker command failed with exit code 1 (use -v to see invocation)

### ISSUE THREAD

**Issue by devashishsethia** [razorpay/react-native-razorpay#228]
>
Hi,

I'm getting the following error when trying to build my project.

<img width="698" alt="Screenshot 2019-10-24 at 1 21 30 PM" src="https://user-images.githubusercontent.com/17251082/67464602-4320e280-f661-11e9-8774-85dfe78bfa31.png">

<img width="753" alt="Screenshot 2019-10-24 at 2 11 46 PM" src="https://user-images.githubusercontent.com/17251082/67468513-41a6e880-f668-11e9-88a0-e98fc4d1c084.png">

I'm using xcode11. Please help.

**Comment by srinivaassunil** [comment]
Hi,
Facing same issue in Xcode 11.2.1. Getting the same error but with ` for architecture armv7`. Please help

**Comment by Nautiyalsachin** [comment]
Hi @srinivaassunil, @devashishsethia: Please try our updated package for solving this issue.  react-native-razorpay -2.1.32.

Closing this issue due to the time elapsed. Please feel free to either re-open the issue or create a
new issue if you have any additional queries.
