### ISSUE TITLE
Not working on ios after intallation

### ISSUE THREAD

**Issue by dharmusharma1981** [razorpay/react-native-razorpay#23]
"react": "16.0.0-alpha.6",
 "react-native": "0.43.3",

Im trying to add the example code  on ios but after linkin ,
when i try to execute the open code 

nuthing happens 

Need help in integration of razor pay
and feel like framework file is not updated with npm

**Comment by dharmusharma1981** [comment]
On Manual Installation

  "_OBJC_CLASS_$_CTTelephonyNetworkInfo", referenced from:
clang: error: linker command failed with exit code 1 (use -v to see invocation)

seemslike linking is broken

**Comment by dharmusharma1981** [comment]
Okie so after installing manual latest .framework  files
I got and got a  build error

'Razorpay/ExternalWalletSelectionProtocol.h' file not found

seems like this repo  xcode project is not updated with latest framework





#import <Razorpay/ExternalWalletSelectionProtocol.h>

**Comment by dharmusharma1981** [comment]
'/Users/Dharmu/Library/Developer/Xcode/DerivedData/NightSpot-ezhvskyqpdhlzcfolnvexaxverao/Build/Products/Debug-iphoneos/libRazorpayCheckout.a(RazorpayCheckout.o)' does not contain bitcode. You must rebuild it with bitcode enabled (Xcode setting ENABLE_BITCODE), obtain an updated library from the vendor, or disable bitcode for this target. for architecture arm64
clang: error: linker command failed with exit code 1 (use -v to see invocation)

**Comment by dharmusharma1981** [comment]
these lib is really broken and i havent got response from any one 
so may be u shd delete this repo

**Comment by captn3m0** [comment]
@dharmusharma1981 We are looking into this issue.

**Comment by dharmusharma1981** [comment]
Thanks 
Well We are almost done with our ecommerce app only thing left is payment gateway integration 
Let me know if you need more info from my side

**Comment by dharmusharma1981** [comment]
any updates on this issue

**Comment by ArcadeRenegade** [comment]
Hi Razorpay team, we would really appreciate any help on this issue. It works great on Android but we just need it to get it to work on iOS and we will be good. We plan to deploy within a month.

**Comment by captn3m0** [comment]
Our iOS lead ( @akshaybhalotia) is currently unavailable, which is why this has been taking longer than expected. However, @pronav is looking into the issue, and we expect to have this resolved soon on iOS.

**Comment by pronav** [comment]
@dharmusharma1981 I've put up bitcode enabled framework over here: https://github.com/razorpay/razorpay-ios-sample-app/releases/tag/v0.15.0

Error seems to be there because this library downloads non-bitcode version by default. Can you check using bitcode version using manual install method?

**Comment by dharmusharma1981** [comment]
Thanks 
@pronav  Definately I will give a try with above bit code framework and manual installation .
WIll let u know If i face any issue 

Thanks for looking into this

**Comment by dharmusharma1981** [comment]
Hi @pronav 
 Tried manual Installation with the link provided above 

i m still getting this error

Build/Products/Debug-iphoneos/libRazorpayCheckout.a(RazorpayCheckout.o)' does not contain bitcode. You must rebuild it with bitcode enabled (Xcode setting ENABLE_BITCODE), obtain an updated library from the vendor, or disable bitcode for this target. for architecture arm64
clang: error: linker command failed with exit code 1 (use -v to see invocation)

**Comment by pronav** [comment]
@dharmusharma1981 DId you download bitcode enabled version from above link, and not the other one?

Also, can you check by disabling bitcode setting in your project, to make sure this is the only error.

**Comment by dharmusharma1981** [comment]
@pronav Yes The same File 
Let me try to disable the bitcode setting

**Comment by dharmusharma1981** [comment]
Okie after disabling the bit code Setting on my project It compiled and install on my device ,
However When i m trying to call 

RazorpayCheckout.open(options).then((data) => {

}

Nuthing happened no razor pay lazy loading ui open

**Comment by pronav** [comment]
Checking it.

**Comment by dharmusharma1981** [comment]
Thanks @pronav

**Comment by akshaybhalotia** [comment]
Hey @dharmusharma1981 , I went over the issue with @pronav and found that there seem to be steps missing from your iOS setup. I would highly recommend going over this section: <https://github.com/razorpay/react-native-razorpay#additional-steps-for-linking-ios-sdk>.

I tested this for the latest and a couple of previous react native versions but it worked fine for me. Looks like a problem particular to your setup so closing the issue.

If the need still be, we can have a TeamViewer session on Monday. Please drop an email to support(at)razorpay.com with your phone number to coordinate.

**Comment by dharmusharma1981** [comment]
Do U guys have any idea about it

Undefined symbols for architecture x86_64:
  "_OBJC_CLASS_$_CTTelephonyNetworkInfo", referenced from:
      objc-class-ref in Razorpay(RazorpayLogging.o)
ld: symbol(s) not found for architecture x86_64
clang: error: linker command failed with exit code 1 (use -v to see invocation)

**Comment by AbhinavArora95** [comment]
@akhilkoinex  Could you please elaborate, whether you are receiving the same error or is it something else ? Are you using Swift or Objective C ? Also, what minimum iOS version are you building for ?

**Comment by akhilkoinex** [comment]
@AbhinavArora95 I am facing the same issue as described in the thread. Using Obj-C. iOS 8

**Comment by Mayur-Wadpalliwar** [comment]
Could you please download the mentioned frameworks manually and add  them to your project and let us know?

CoreTelephony.framework in Frameworks 
SystemConfiguration.framework in Frameworks

**Comment by akhilkoinex** [comment]
Okay. Will keep you posted.


*Akhil James*
Software Engineer, Koinex
+91 906 123 9977 <+91+906+123+9977> | blog.akhiljames.com
<http://www.facebook.com/IAmAkhilJames>
<http://in.linkedin.com/in/akhiljames>
<http://www.twitter.com/IAmAkhilJames> <http://github.com/akhiljames>
<http://angel.co/akhil-james>

On Wed, Nov 1, 2017 at 11:53 AM, Mayur Wadpalliwar <notifications@github.com
