### ISSUE TITLE
dyld: Library not loaded: @rpath/Razorpay.framework/Razorpay image not found

### ISSUE THREAD

**Issue by tejas-freo** [razorpay/react-native-razorpay#231]
My Xcode Version 11.2 (11B52) Swift version 5.1.2 react-native-razorpay version 2.1.31. I have followed all the steps of adding framework and enabling the swift libraries yet having the same issue. Kindly suggest the solution

**Comment by Nautiyalsachin** [comment]
For Xcode 11, ensure that you have the framework added in Frameworks, Libraries, and Embed Content under Target settings - General. Change Embed status from - 'Do not Embed' to 'Embed & Sign'.

**Comment by tejas-freo** [comment]
> For Xcode 11, ensure that you have the framework added in Frameworks, Libraries, and Embed Content under Target settings - General. Change Embed status from - 'Do not Embed' to 'Embed & Sign'.

Thanks issue is fixed
