### ISSUE TITLE
Payment Failed with following response 

### ISSUE THREAD

**Issue by SaravananRath** [razorpay/react-native-razorpay#233]
{
'code': 0, 
'details': {'name': '*****', 'email': '********', 'contact': '**********'}, 
'description': 'Webview error The operation couldn’t be completed. (NSURLErrorDomain error -999.)'
}

Could anyone explain the reason for failure?

**Comment by Nautiyalsachin** [comment]
Can you give us more details here as it still looks incomplete, You can add pieces of information like package version, package name, platform name, also passed options in open method for replicating the issue.

**Comment by Nautiyalsachin** [comment]
Closing this issue due to the time elapsed. Please feel free to either re-open the issue or create a
new issue if you have any additional queries.

**Comment by shivanitp** [comment]
Hello 
in RazorpayCheckout test mode if we select failed payment in last it's not closing the razor pay screen nand not given any response 
here is my code 
 var options = {
            description: pageProps.orderDetail.id ? `Order ID - ${pageProps.orderDetail.id.toUpperCase()}` : pageProps.orderDetail.refServiceOrderId,
            image: `${apiBaseUri}images/common/logo-small.png`,
            currency: 'INR',
            key: RAZORPAY_KEY,
            amount: amount * 100,
            name: 'DusMinute',
            prefill: {
                email: pageProps.user.email,
                contact: pageProps.user.mobile,
                name: pageProps.user.name,
                //   method: 'netbanking',
                method
            },
            theme: { color: PRIMARY_COLOR },
        }

        RazorpayCheckout.open(options).then((data) => {
            // handle success
            console.log("razorpay Success:", data);
           
        }).catch((error) => {
            // handle failure
            console.log(`razorpay Error : ${error} | ${error.description}`);
        });
        
 can you help me on this 
React native version - 0.63.4
razorpay vesion - 2.2.4

**Comment by manjeetcars24** [comment]
Happening to us on iOS testing builds, we are showing error directly from razorpay
<img width="390" alt="Screenshot 2023-01-18 at 7 10 21 PM" src="https://user-images.githubusercontent.com/121548313/213186391-92b04c48-6637-4f88-966b-f77caee3dddd.png">

**Comment by neeraj-singh-toneop** [comment]
still facing the same issue on IOS device, whereas its working on Android.
Any solution found for this issue?
`Error message:- {"code": 0, "description": "Webview error The operation couldn’t be completed. (NSURLErrorDomain error -999.)", "details": {"contact": "+91******", "email": "support******.com", "name": ""}}`

**Comment by shhivam** [comment]
Facing the same error with `"react-native-razorpay": "^2.3.0",`

**Comment by sahibhussain** [comment]
i am facing this issue on ios native sdk

**Comment by rohitcomfygen** [comment]
still facing the same issue on IOS device, whereas its working on Android.
Any solution found for this issue?
Error message:- {"code": 0, "description": "Webview error The operation couldn’t be completed. (NSURLErrorDomain error -999.)", "details": {"contact": "+91******", "email": "support******.com", "name": ""}}

**Comment by rameshyallappa** [comment]
i am facing this issue on ios working fine on android with "react-native-razorpay": "^2.3.0" version, please help with the solution.
![IMG_5671](https://github.com/user-attachments/assets/7c62a316-a9ac-4ce7-ba65-bbd534fb5296)
