### ISSUE TITLE
Getting a Blank Screen for a while before rendering razorpay content

### ISSUE THREAD

**Issue by sdasari2** [razorpay/react-native-razorpay#235]
After `RazorpayCheckout.open`, the modal opens and displays white screen for a while before showing razorpay checkout. Is it possible to improve the performance or at least is there a way to add a spinner so that user feels something is loading instead of a blank white screen.

Please checkout the below video.
![ezgif com-video-to-gif](https://user-images.githubusercontent.com/14313474/69000345-1cd71700-089c-11ea-8d73-f2ffc011b149.gif)

**Comment by sdasari2** [comment]
Any updates on this..?

**Comment by developerashish01** [comment]
any update?

**Comment by karan-gujral** [comment]
I added a Loader on top of the screen to show the user some activity. The loader plays for a static 5 secs and disappears. Improves the user expirience (in most cases). Can't find any other better way to handle this.

**Comment by smahajan28** [comment]
Hi devs!
What`s the status of this issue.. White screen for a Long time looking so odd. Please fix it asap!

**Comment by prataprish007** [comment]
please provide update on this.

**Comment by Nautiyalsachin** [comment]
Working on it. We are going to release a new version with the Auto linking enabled.

**Comment by Nautiyalsachin** [comment]
This issue is been solved with v 2.1.33 release. After updating your package you will be able to see the loader.
