### ISSUE TITLE
[Need clarification] Why is the discrepancy between module names and module import

### ISSUE THREAD

**Issue by AshishCd** [razorpay/react-native-razorpay#236]
I have used razorpay integration around 5-6 months ago and it was react-native-razorpay while currently on npm it is react-native-customui. Can anyone clarify why it is like that ? is there any updates in react-native-customui ?

It's a bit confusing module name.

![image](https://user-images.githubusercontent.com/39944703/69524662-8e921d80-0f8c-11ea-824b-1324a586847e.png)

**Comment by Nautiyalsachin** [comment]
Well both packages are different, and **react-native-customui** is under maintenance right now, you can follow [this link](https://www.npmjs.com/package/react-native-razorpay) for installing and updating your package and make it more future proof. Also, we have released the latest package 2.1.32 with Auto linking. 

We would really like to hear from you about that.

**Comment by CHANDRAMOHANnegi** [comment]
use this Doc

https://razorpay.com/docs/payment-gateway/react-native-integration/custom/
