### ISSUE TITLE
Pay button is missing in payment gateway

### ISSUE THREAD

**Issue by srinivas-learnyst** [razorpay/react-native-razorpay#237]
On proceeding to payment, the pay button is not displayed
<img width="960" alt="payButton_Razorpay" src="https://user-images.githubusercontent.com/53288430/70023638-17790c80-15be-11ea-8e03-418243993243.png">

**Comment by Nautiyalsachin** [comment]
Hi @srinivas-learnyst : Can you give me more details here, also add the steps to replicate this issue.

Also can you give us the passed options here.

**Comment by srinivas-learnyst** [comment]
This used to happen in the older version, in the recent update the same issue occurs when a user makes a payment using "PREFERRED PAYMENT METHODS".
I have attached the screenshot for your reference.
Note: I am currently using the gateway in test mode.

![Screenshot (4)](https://user-images.githubusercontent.com/53288430/74523982-355ed800-4f44-11ea-8c05-3423e3ccc30b.png)

**Comment by umanghome** [comment]
@srinivas-learnyst, can you drop an email to umang.galaiya@razorpay.com? I need more details to be able to reproduce this.

**Comment by vivekshindhe** [comment]
Closing this issue due to no response from your side. Please feel free to either re-open the issue or create a new issue if you have any additional queries.
