### ISSUE TITLE
Failed to verify bitcode: Linker option verification failed for bundle

### ISSUE THREAD

**Issue by prateekchachra** [razorpay/react-native-razorpay#238]
There's an error occuring while trying to build an IPA archive in XCode.

error: Linker option verification failed for bundle /var/folders/gp/n_......./Razorpay.arm64.xar (unrecognized arguments: -platform_version iOS 10.0.0 13.0.0)

I'm using XCode 10 with react-native version 0.60.3 and react-native-razorpay 2.1.30. Our release is stuck because of this issue, please help.

**Comment by rfaturahman25** [comment]
same trouble here

**Comment by Nautiyalsachin** [comment]
Hi guys, please update your Xcode to the latest version i.e. - Xcode 11.3. As in react-native-razorpay supports the latest version of Swift and your Xcode is outdated for that, if you want to support the older version of swift, then try to install older packages. 

Best way to solve this issue will be updating your Xcode. Let me know if you guys still facing some issue.

**Comment by Nautiyalsachin** [comment]
Closing this issue due to the time elapsed. Please feel free to either re-open the issue or create a
new issue if you have any additional queries.
