### ISSUE TITLE
RN 0.60+ autolinking support for IOS

### ISSUE THREAD

**Issue by IntelliJAbhishek** [razorpay/react-native-razorpay#239]
This library working fine with android in projects that created with RN 0.60+ but on IOS we need to link via react-native link react-native-razorpay. I guess it can be done using podspec file which other libs do.

Is there any plan for support autolinking ios?

**Comment by maskedTitan** [comment]
Hi Abhishek, 

Yes, currently for iOS you'd have to manually link our framework using `react-native link react-native-razorpay`
We are working on making this automated as well post which the above step of manual linking can be avoided.
