### ISSUE TITLE
Payment Amount Is Not Proper Show 

### ISSUE THREAD

**Issue by MITDD6338** [razorpay/react-native-razorpay#240]
![paymentShow1](https://user-images.githubusercontent.com/31823903/70910090-fa6c2100-2034-11ea-8b9b-932533c7e913.png)

Hello @razorpay 
**payment Screen is  failing for some Value** like 
I click on pay now and pass on the amount String Format 
but when Open Razor pay screen my actual  amount is not show 
and the wrong amount show.
I get no payment failed message with no description of the error and I will be navigated back to
the initial screen of the payment

**I am passing on 200 amount but Razorpay Open the Screen wrong data show** 

![worng data dispaly](https://user-images.githubusercontent.com/31823903/70910721-4c617680-2036-11ea-9a5b-3ffa526937aa.png)

How can I Solved them 
@razorpay 

    "react": "16.8.3",
    "react-native": "0.59.10",
"react-native-razorpay": "^2.1.24",

**Comment by khushal87** [comment]
Any solution ? @MITDD6338

**Comment by vivekshindhe** [comment]
this is the prefill page where we ask the user to enter their e-mail IDs and mobile number. On clicking proceed it should show you the right amount. Also, please ensure that the amount in the payload is in paisa. Ex: Entering 200 in the payload will create a transaction of 2rs. 20000 will result in 200. @khushal87

**Comment by jdarshan5** [comment]
> 

Passing the correct details in prefill did not resolve this problem for me, Can this be due to test key which we are passing into the key field?

**Comment by vivekshindhe** [comment]
@jdarshan5 can you send the payload object you are sending to the package?

**Comment by jdarshan5** [comment]
@vivekshindhe 
here it is
`name: 'name',
description: 'description',
amount: 'amount in string format',
currency: 'INR',
key: 'rzp_test_xxxxxxxxxxxxxx',
order_id: 'orderid'
prefill: {
email: 'blah@blah.com',
contact: 1212121212,
name: 'Blah Blah',
},`

Versions:
"react-native": "^0.63.4"
"react-native-razorpay": "^2.2.9"
