### ISSUE TITLE
React Native IOS not working - No podspec file was found

### ISSUE THREAD

**Issue by IamDhana** [razorpay/react-native-razorpay#241]
**Version**
React Native 0.61.2
react-native-razorpay 2.1.31

**Steps Followed**

- npm install react-native-razorpay --save

- react-native link react-native-razorpay

- cd ios && pod install

**Getting the following error**

[!] use_native_modules! skipped the react-native dependency 'react-native-razorpay'. No podspec file was found.
    - Check to see if there is an updated version that contains the necessary podspec file
    - Contact the library maintainers or send them a PR to add a podspec. The react-native-webview podspec is a good example of a package.json driven podspec. See
    https://github.com/react-native-community/react-native-webview/blob/master/react-native-webview.podspec
    - If necessary, you can disable autolinking for the dependency and link it manually. See
    https://github.com/react-native-community/cli/blob/master/docs/autolinking.md#how-can-i-disable-autolinking-for-unsupported-library

**Working fine in android platform**

**Comment by ppritesh** [comment]
Same issue for me

**Comment by tejas-freo** [comment]
Same issue for me any solutions for this?

**Comment by ppritesh** [comment]
create new file into  node_modules/react-native-razorpay/**react-native-razorpay.podspec**

then copy and paste following code into react-native-razorpay.podspec
```
require 'json'

package = JSON.parse(File.read(File.join(__dir__, 'package.json')))

Pod::Spec.new do |s|
  s.name         = package['name']
  s.version      = package['version']
  s.summary      = package['description']
  s.license      = package['license']

  s.authors      = package['author']
  s.homepage     = package['homepage']
  s.platform     = :ios, "9.0"

  s.source       = { :git => "https://github.com/razorpay/react-native-razorpay.git", :tag => "v#{s.version}" }
  s.source_files  = "ios/**/*.{h,m}"

  s.dependency 'React'
end
```
then try

**Comment by ppritesh** [comment]
create a new file into node_modules/react-native-razorpay/**react-native-razorpay.podspec**

copy and paste the following code into react-native-razorpay.podspec file.

```
require 'json'

package = JSON.parse(File.read(File.join(__dir__, 'package.json')))

Pod::Spec.new do |s|
  s.name         = package['name']
  s.version      = package['version']
  s.summary      = package['description']
  s.license      = package['license']

  s.authors      = package['author']
  s.homepage     = package['homepage']
  s.platform     = :ios, "9.0"

  s.source       = { :git => "https://github.com/react-native-community/react-native-webview.git", :tag => "v#{s.version}" }
  s.source_files  = "ios/**/*.{h,m}"

  s.dependency 'React'
end
```
then try

**Comment by Nautiyalsachin** [comment]
@tejas-freo: We are releasing a new version after few days, which will include the support for 0.60 and above. 

https://github.com/razorpay/react-native-razorpay/issues/202

**Comment by naman101** [comment]
> @tejas-freo: We are releasing a new version after few days, which will include the support for 0.60 and above.
> 
> #202

@Nautiyalsachin Do we have an ETA on this?

**Comment by tejas-freo** [comment]
Working fine thanks for help

**Comment by Nautiyalsachin** [comment]
@naman101, I have integrated the changes into master. You can install this package from here.
This packages is still needs to be published on npm. 
Let me know if you still unable to integrate it or face any issues.

**Comment by Nautiyalsachin** [comment]
We have published a new package version to nom

[![NPM](https://nodei.co/npm/react-native-razorpay.png?downloads=true)](https://nodei.co/npm/react-native-razorpay/).
