### ISSUE TITLE
Undefined symbol: _OBJC_CLASS_$__TtC8Razorpay8Razorpay

### ISSUE THREAD

**Issue by sid-metiz** [razorpay/react-native-razorpay#243]
I am Using XCode 11 and Having Issue like this

**Comment by Nautiyalsachin** [comment]
Can you follow these steps which are mentioned here  https://github.com/razorpay/react-native-razorpay/issues/63

**Comment by sid-metiz** [comment]
Yes i follow
Still same issue

**Comment by sid-metiz** [comment]
Can you help me using team viewer for resolving this issue?

**Comment by sid-metiz** [comment]
Hii any Update?

**Comment by Nautiyalsachin** [comment]
Can you tell me what all steps you followed to integrate Razorpay in your project ?

**Comment by sid-metiz** [comment]
At the final i solved error.. But In Simulator have error but its working in real devices..

**Comment by cursivedgreat** [comment]
> At the final i solved error.. But In Simulator have error but its working in real devices..

Can you list the step to solve this issue ?
