### ISSUE TITLE
How would I go about implementing custom checkout?

### ISSUE THREAD

**Issue by naman101** [razorpay/react-native-razorpay#246]
I would like to implement custom checkout, i.e, have my own UI and then redirect to the respective payment gateways/websites/apps, is that possible?

**Comment by Nautiyalsachin** [comment]
Hey Naman,

Can you help me understand your use case for using Custom UI (what does Razorpay's Standard Checkout not provide). In case you would still like to go through with Custom here's how you do it: 

You can get the current package for Custom UI from here - https://www.npmjs.com/package/react-native-customui 

Follow these steps mentioned here - 

https://github.com/razorpay/react-native-razorpay/wiki/Manual-Installation-Steps. Just replace the package name with Custom UI. 

Also for more details you can follow this link - 

https://razorpay.com/docs/payment-gateway/react-native-integration/custom/

Let me know if you still face some issue.

**Comment by naman101** [comment]
@Nautiyalsachin Thanks.

We would just like to implement our own UI for checkout instead of showing the razorpay dialog.

Does the npm package not support automatic linking?

**Comment by Nautiyalsachin** [comment]
Not for Custom-UI, you can always go for Razorpay's Standard Checkout. We have released the latest version 2.1.32 and it is supported with Auto linking.

**Comment by CHANDRAMOHANnegi** [comment]
use this Doc

https://razorpay.com/docs/payment-gateway/react-native-integration/custom/
