### ISSUE TITLE
UI went wrong on Top-notch iPhones 

### ISSUE THREAD

**Issue by karthikmandava7** [razorpay/react-native-razorpay#247]
* **Specific to iOS Users:-**
Everything working fine only issue with UI in Top-notch phones for iOS Devices. Is there any updated SDK for this?

**Comment by Nautiyalsachin** [comment]
@karthikmandava7: Can you tell me more details for replicating this issue ?

1. Which iOS version are you using ?
2. Is it a simulator or a physical device ?
3. Which version are you using for Razorpay package? 

Also try to update your package to the latest one and follow [sample code](https://github.com/razorpay/react-native-razorpay/blob/master/example/SampleProject/App.js) for open method.

**Comment by karthikmandava7** [comment]
1. iOS 13 and 11.2.
2. in Both.

**Comment by karthikmandava7** [comment]
@Nautiyalsachin any update on this?

**Comment by Nautiyalsachin** [comment]
Custom UI is still in maintenance, we will update you as soon as it's fixed.

**Comment by karthikmandava7** [comment]
@Nautiyalsachin But this will not able to cancel the transaction on Top-notch iPhones. Can you suggest any temporary solution for this as we are releasing our new React Native App within 3 days.

**Comment by karthikmandava7** [comment]
@Nautiyalsachin Any updates on this?

**Comment by Nautiyalsachin** [comment]
@karthikmandava7 : I am still not able to replicate this issue. Can you please try to replicate it on the [Sample App](https://github.com/razorpay/react-native-razorpay/tree/master/example/SampleProject). Also please use the latest version of the package i.e. 2.1.3.

**Comment by vivekshindhe** [comment]
Closing this issue due to no response from your side. Please feel free to either re-open the issue or create a new issue if you have any additional queries.

**Comment by CHANDRAMOHANnegi** [comment]
![razorpay_hdfc_ios](https://user-images.githubusercontent.com/32297380/117180671-0c995b80-adf2-11eb-9d21-7ba365fbaf31.png)

**Comment by Nautiyalsachin** [comment]
Hi @CHANDRAMOHANnegi, can you try using the latest version of react-native-customui v2.1.8. We recently have released a fix for this, let me know how that works for you. Thanks.
