### ISSUE TITLE
error: no such file or directory /libRazorpayCheckout.a

### ISSUE THREAD

**Issue by ankitkumar003** [razorpay/react-native-razorpay#248]
Razorpay Version: 2.1.32
Xcode: 11.2.1

Error: clang: error: no such file or directory: '/Users/ankit/Library/Developer/Xcode/DerivedData/Panasonic_MTP_RN-hfrkrwdcstywuqgdvsifxtbhscqz/Build/Products/Debug-iphonesimulator/libRazorpayCheckout.a'
Command Ld failed with a nonzero exit code

Almost tried everything, framework path, Always Embed Libraries, linking process.
Although, removing "libRazorpayCheckout.a" file from Frameworks, libraries and embedded content, removes the error but it doesn't resolve the purpose.

**Comment by Nautiyalsachin** [comment]
Hi, @ankitkumar003 Have you tried with Auto linking option? Also, try to download the latest Xcode i.e. 11.3 and try it again.

**Comment by ankitkumar003** [comment]
Not sure but I think Xcode 11.3 won't make any difference but will try that too..

Auto linking - Yes, Tried Automatic process but No luck...

Actually this project is not using pod file, so I have followed these steps, given on official site 
https://razorpay.com/docs/payment-gateway/react-native-integration/standard/#step-2---link-the-sdk-with-react

**Comment by Nautiyalsachin** [comment]
@ankitkumar003 : We are updating our documentation soon, try to update your Xcode to the latest as the Swift version is not matching with the framework Swift version.

**Comment by Nautiyalsachin** [comment]
@ankitkumar003: We have updated our documentation with the new integration steps, feel free to use it.
