### ISSUE TITLE
Build Error

### ISSUE THREAD

**Issue by dharmusharma1981** [razorpay/react-native-razorpay#25]
Undefined symbols for architecture x86_64:
  "_OBJC_CLASS_$_CTTelephonyNetworkInfo", referenced from:
      objc-class-ref in Razorpay(RazorpayLogging.o)
ld: symbol(s) not found for architecture x86_64
clang: error: linker command failed with exit code 1 (use -v to see invocation)

**Comment by dharmusharma1981** [comment]
I used bit code enabled Framework file by downloading using below link
https://github.com/razorpay/razorpay-ios-sample-app/releases/tag/v0.15.0

**Comment by pronav** [comment]
@dharmusharma1981 Can you add `CoreTelephony.framework` to your project?

**Comment by dharmusharma1981** [comment]
@pronav  did That same Now it is building 

Thanks

**Comment by dharmusharma1981** [comment]
Thanks  I see every thing working fine after  adding the required framework thanks guys closing the issue

**Comment by jaspal747** [comment]
I just received the same error. 
Why don't you add this step to the iOS instructions?

> Under "Link Binary With Libraries" in the "Build Phases" tab of your project settings, add CoreTelephony.framework and SystemConfiguration.framework.
