### ISSUE TITLE
dyld: Library not loaded: @rpath/libswiftCore.dylib

### ISSUE THREAD

**Issue by sohel-khan** [razorpay/react-native-razorpay#250]
`dyld: Library not loaded: @rpath/libswiftCore.dylib
  Referenced from: /Users/rohanray/Library/Developer/CoreSimulator/Devices/4DA0DFCB-510E-445E-9F06-5C4BBF8DDCD0/data/Containers/Bundle/Application/6B2004D6-5E51-4E4D-8547-306A20DEEB49/HotelBooking.app/Frameworks/Razorpay.framework/Razorpay
  Reason: image not found`

Versions:
xcode: Version 10.1 
IOS: Version 10.13.6
"react-native-razorpay": "^2.1.32"
"react-native": "0.61.4"

@Nautiyalsachin Please look into the above error asap, I have followed all steps Still getting error.

**Comment by Nautiyalsachin** [comment]
Hi @sohel-khan, Can you try to update your Xcode to the latest version and follow the same process again.

**Comment by Nautiyalsachin** [comment]
Closing this issue due to the time elapsed. Please feel free to either re-open the issue or create a
new issue if you have any additional queries.
