### ISSUE TITLE
ld:framework not found razorpay_flutter 

### ISSUE THREAD

**Issue by sarikonda1** [razorpay/react-native-razorpay#251]
![Screenshot 2020-02-26 at 6 25 50 PM](https://user-images.githubusercontent.com/20814709/75347099-10645080-58c6-11ea-956c-310e5f91a4b9.png)

Unable to find packages for razorpay_flutter in ios folder.
i tried every solution from this link(https://github.com/razorpay/react-native-razorpay/issues/149) but not found any solution please help me out from this problem.

**Comment by Nautiyalsachin** [comment]
@sarikonda1 : This repo is for react-native-razorpay. Not for [razorpay-flutter](https://github.com/razorpay/razorpay-flutter). Please take a reference from there issue, it can mess up your code more. 

Also, try to update your Xcode and try to integrate it again. I'll suggest you, try creating a sample app or try the example code from [here](https://github.com/razorpay/razorpay-flutter/tree/master/example).
