### ISSUE TITLE
Undefined symbol: _OBJC_CLASS_$_GeneratedPluginRegistrant while building flutter app in ios

### ISSUE THREAD

**Issue by sarikonda1** [razorpay/react-native-razorpay#252]
![Screenshot 2020-02-26 at 8 01 24 PM](https://user-images.githubusercontent.com/20814709/75354443-fb41ee80-58d2-11ea-99cc-164b29bdc60c.png)

Undefined symbols for architecture arm64:
"_OBJC_CLASS_$_GeneratedPluginRegistrant", referenced from:
objc-class-ref in AppDelegate.o
ld: symbol(s) not found for architecture arm64
clang: error: linker command failed with exit code 1 (use -v to see invocation)
unable to build in mac can please help me out.

**Comment by Nautiyalsachin** [comment]
@sarikonda1 : Please raise these issues on [razorpay-flutter](https://github.com/razorpay/razorpay-flutter). 

Also as asked in the issue template can you share all the details so that we can have an overall idea about your system configuration and it can be an already raised issue?

**Comment by sarikonda1** [comment]
> @sarikonda1 : Please raise these issues on [razorpay-flutter](https://github.com/razorpay/razorpay-flutter).
> 
> Also as asked in the issue template can you share all the details so that we can have an overall idea about your system configuration and it can be an already raised issue?

what kind of details you need?

**Comment by Nautiyalsachin** [comment]
@sarikonda1  : Here are the asked details - 

* **Common to Both platforms :-**

  - [ ] I have gone through the README (https://github.com/razorpay/react-native-razorpay)
  - [ ] I have searched for a similar issue (https://github.com/razorpay/react-native-razorpay/issues)
  - [ ] I am using the latest version of our framework (https://github.com/razorpay/react-native-razorpay/releases)
  - [ ] I have cleaned my project.
  - [ ] I have gone through FAQ's (https://github.com/razorpay/react-native-razorpay/wiki/FAQ's)


* **Specific to iOS Users:-**

  - [ ] I have modified the module map as specified in the readme (https://github.com/razorpay/react-native-razorpay)
  - [ ] I have deleted the contents of the derived data folder and rebuild it.



## IDE Specs




## Retro Steps


## Screenshots

**Comment by Nautiyalsachin** [comment]
Closing this issue due to the time elapsed. Please feel free to either re-open the issue or create a
new issue if you have any additional queries.
