### ISSUE TITLE
Facing an issue pasted Below after doing Archive and failed to Distribute App.

### ISSUE THREAD

**Issue by raju7878** [razorpay/react-native-razorpay#253]
* **Common to Both platforms :-**

  - [ ] I have gone through the README (https://github.com/razorpay/react-native-razorpay)
  - [ ] I have searched for a similar issue (https://github.com/razorpay/react-native-razorpay/issues)
  - [ ] I am using the latest version of our framework (https://github.com/razorpay/react-native-razorpay/releases)
  - [ ] I have cleaned my project.
  - [ ] I have gone through FAQ's (https://github.com/razorpay/react-native-razorpay/wiki/FAQ's)

* **Specific to iOS Users :-**

  - [ ] I have modified the module map as specified in the readme (https://github.com/razorpay/react-native-razorpay)
  - [ ] I have deleted the contents of the derived data folder and rebuild it.

**Comment by raju7878** [comment]
<img width="733" alt="Screenshot 2020-03-05 at 5 01 32 PM" src="https://user-images.githubusercontent.com/59197667/75977959-7888e700-5f03-11ea-9f0c-0d530ba65144.png">
Facing this error after doing Archive successfully and  when Distributing app.

**Comment by Nautiyalsachin** [comment]
Can you try this solution mentioned [here](https://stackoverflow.com/questions/48921424/why-verify-your-bundle-identifier-org-cocoapods-alamofire-is-correct)?

**Comment by Nautiyalsachin** [comment]
Closing this issue due to the time elapsed. Please feel free to either re-open the issue or create a
new issue if you have any additional queries.
