### ISSUE TITLE
Library not loaded

### ISSUE THREAD

**Issue by Imfaizan** [razorpay/react-native-razorpay#254]
Versions:
xcode: Version 11.3.1
IOS: Version 13.3.1
"react-native-razorpay": "^2.1.32"
"react-native": "0.61.5"

Getting below error when i try to run from x-code to real device integration through usb. ****Works fine on simulator**. ****Issue comes only when we run on real device through usb.**

d****yld: Library not loaded: @rpath/Razorpay.framework/Razorpay

  Referenced from: /private/var/containers/Bundle/Application/E1340AC0-1A4C-443C-8B46-DA85DA3D3328/Wemilk.app/Wemilk

  Reason: no suitable image found.  Did find:

	/private/var/containers/Bundle/Application/E1340AC0-1A4C-443C-8B46-DA85DA3D3328/Wemilk.app/Frameworks/Razorpay.framework/Razorpay: code signature invalid for '/private/var/containers/Bundle/Application/E1340AC0-1A4C-443C-8B46-DA85DA3D3328/Wemilk.app/Frameworks/Razorpay.framework/Razorpay'

	/private/var/containers/Bundle/Application/E1340AC0-1A4C-443C-8B46-DA85DA3D3328/Wemilk.app/Frameworks/Razorpay.framework/Razorpay: stat() failed with errno=25

	/private/var/containers/Bundle/Application/E1340AC0-1A4C-443C-8B46-DA85DA3D3328/Wemilk.app/Frameworks/Razorpay.framework/Razorpay: code signature invalid for '/private/var/containers/Bundle/Application/E1340AC0-1A4C-443C-8B46-DA85DA3D3328/Wemilk.app/Frameworks/Razorpay.framework/Razorpay'

	/private/var/containers/Bundle/Application/E1340AC0-1A4C-443C-8B46-DA85DA3D3328/Wemilk.app/Frameworks/Razorpay.framework/Razorpay: stat() failed with errno=1

	/private/var/containers/Bundle/Application/E1340AC0-1A4C-443C-8B46-DA85DA3D3328/Wemilk.app/Frameworks/Razorpay.framework/Razorpay: code signature invalid for '/private/var/containers/Bundle/Application/E1340AC0-1A4C-443C-8B46-DA85DA3D3328/Wemilk.app/Frameworks/Razorpay.framework/Razorpay'

	/private/var/containers/Bundle/Application/E1340AC0-1A4C-443C-8B46-DA85DA3D3328/Wemilk.app/Frameworks/Razorpay.framework/Razorpay: stat() failed with errno=1

**Comment by Nautiyalsachin** [comment]
Hi @Imfaizan : Can you try the solutions from this link as mentioned [here](https://github.com/Alamofire/Alamofire/issues/3051). Let me know if it works for you.

**Comment by Imfaizan** [comment]
Thanks @Nautiyalsachin for the link and your quick response. It appears the issue is with free apple's developer account. It works fine on paid developer account. I didn't try useFramework solution  from below link though. But its working fine on Paid Apple Developer's Account.  https://github.com/Alamofire/Alamofire/issues/3051#issuecomment-580139830https://github.com/Alamofire/Alamofire/issues/3051#issuecomment-580139830
