### ISSUE TITLE
Country code issue on Razorpay checkout page

### ISSUE THREAD

**Issue by harshalijain** [razorpay/react-native-razorpay#255]
## IDE Specs
Platform - Android 
"react-native-razorpay": "^2.1.25",

We are facing an issue in Razorpay checkout recently related to contact number

When we do a razorpay checkout and pass following prefill details apart from other details:

```
const options = {
      //other options
currency: 'INR',
      prefill: {
        email: "some@example.com",
        contact: "09876598765",
        name: "XYZ"
      },
    };
RazorpayCheckout.open(options) ...
```
On checkout page, phone number is modified to be displayed as 
+09876598765 instead of +919876598765. And after making payment, an error is displaying that says "Country code provided in contact is invalid"

 **Although when I click on Edit contact information page, it gets modified to +919876598765 automatically.**

It was working fine few days ago, but now we are observing this issue on old versions on production as well without any changes made. 

##SCREENSHOTS
![Screenshot_20200311-174536](https://user-images.githubusercontent.com/10045610/76416376-ff850600-63c0-11ea-83bb-bd7c632abee1.png)

After payment

![Screenshot_20200311-174548](https://user-images.githubusercontent.com/10045610/76416382-014ec980-63c1-11ea-99e9-696e102c1fd4.png)

**Comment by imtiyazzzz** [comment]
I am also facing the same issue

**Comment by rajkumarc2000** [comment]
I am also facing the same issue when trying to send money through razorpay

**Comment by umanghome** [comment]
This has been fixed.
