### ISSUE TITLE
Use of undeclared identifier 'Razorpay' in RazorpayCheckout.m

### ISSUE THREAD

**Issue by roshansingh21** [razorpay/react-native-razorpay#256]
* **Common to Both platforms :-**

  - [x] I have gone through the README (https://github.com/razorpay/react-native-razorpay)
  - [x] I have searched for a similar issue (https://github.com/razorpay/react-native-razorpay/issues)
  - [x] I am using the latest version of our framework (https://github.com/razorpay/react-native-razorpay/releases)
  - [x] I have cleaned my project.
  - [x] I have gone through FAQ's (https://github.com/razorpay/react-native-razorpay/wiki/FAQ's)

* **Specific to iOS Users :-**

  - [ ] I have modified the module map as specified in the readme (https://github.com/razorpay/react-native-razorpay)
  - [ ] I have deleted the contents of the derived data folder and rebuild it.

## IDE Specs
 Xcode Version (iOS): Version 11.4 (11E146)

Razorpay Package Version: 2.1.32

## Retro Steps

1. npm i react-native-razorpay
2. changing the platform in Podfile to 10.0
3. cd ios && pod install
4. run-ios or build from Xcode
## Screenshots 

<img width="2032" alt="Screenshot 2020-04-03 at 15 34 11" src="https://user-images.githubusercontent.com/28808859/78354069-c9eec980-75c8-11ea-96b8-c2be51a00fc3.png">

 error: use of undeclared identifier 'Razorpay'
        Razorpay *razorpay = [Razorpay initWithKey:keyID
        ^
/Users/roshan/react-native/mynyfy-seller-mobile/node_modules/react-native-razorpay/ios/RazorpayCheckout.m:28:19: error: use of undeclared identifier 'razorpay'
        Razorpay *razorpay = [Razorpay initWithKey:keyID
                  ^
/Users/roshan/react-native/mynyfy-seller-mobile/node_modules/react-native-razorpay/ios/RazorpayCheckout.m:28:31: error: use of undeclared identifier 'Razorpay'
        Razorpay *razorpay = [Razorpay initWithKey:keyID
                              ^
/Users/roshan/react-native/mynyfy-seller-mobile/node_modules/react-native-razorpay/ios/RazorpayCheckout.m:30:10: error: use of undeclared identifier 'razorpay'
        [razorpay setExternalWalletSelectionDelegate:self];
         ^
/Users/roshan/react-native/mynyfy-seller-mobile/node_modules/react-native-razorpay/ios/RazorpayCheckout.m:32:10: error: use of undeclared identifier 'razorpay'
        [razorpay open:options];
         ^
/Users/roshan/react-native/mynyfy-seller-mobile/node_modules/react-native-razorpay/ios/RazorpayCheckout.m:41:1: warning: implementing deprecated method [-Wdeprecated-implementations]
- (void)onPaymentError:(int)code
^
In module 'Razorpay' imported from /Users/roshan/react-native/mynyfy-seller-mobile/node_modules/react-native-razorpay/ios/RazorpayCheckout.m:13:

**Comment by Nautiyalsachin** [comment]
Hi @roshansingh21: We are releasing a new version v2.1.33 for resolving this issue, it will be live soon.

**Comment by roshansingh21** [comment]
@Nautiyalsachin Thanks!
