### ISSUE TITLE
Unable to build iOS project, Xcode stucks while compiling react-native-razorpay module

### ISSUE THREAD

**Issue by jitendralakhmani-proptiger** [razorpay/react-native-razorpay#258]
* **Common to Both platforms :-**

  - [x] I have gone through the README (https://github.com/razorpay/react-native-razorpay)
  - [x] I have searched for a similar issue (https://github.com/razorpay/react-native-razorpay/issues)
  - [x] I am using the latest version of our framework (https://github.com/razorpay/react-native-razorpay/releases)
  - [x] I have cleaned my project.
  - [x] I have gone through FAQ's (https://github.com/razorpay/react-native-razorpay/wiki/FAQ's)

* **Specific to iOS Users :-**

  - [x] I have modified the module map as specified in the readme (https://github.com/razorpay/react-native-razorpay)
  - [x] I have deleted the contents of the derived data folder and rebuild it.

**Comment by Nautiyalsachin** [comment]
Hi @jitendralakhmani-proptiger, Can you give me some more details or share some logs. Also, I will suggest you share the asked details whenever you create any issue. Feel free to try the sample app first before integrating it into your project.

**Comment by jitendralakhmani-proptiger** [comment]
@Nautiyalsachin Thanks for responding. But I am unable to build my project (not even a new RN project with RN version 0.62 or 0.61) in iOS. It stucks while compiling library "react-native-razorpay" while building.. And then it gets stucks forever. I tried to build the sample project of lib, but I cant find a razorpay dependency in its package.json, so its gives error. unable to resolve react-native-razorpay from App.js file. And after adding dependency in package manually and installing pods. I get same issue.
Btw, I am using 
Xcode 10.3
RN versions used- 0.60 / 0.61 / 0.62
Node v11.9.0

**Comment by Nautiyalsachin** [comment]
Hi @jitendralakhmani-proptiger, can you update your Xcode to 11+? It will be best if you try updating that too.

**Comment by irishabhyadav90** [comment]
Hi, im facing the same issue,  xcode build stucks while building react-native-razorpay

**Comment by jitendralakhmani-proptiger** [comment]
@irishabhyadav90 what Xcode version are you using?

**Comment by irishabhyadav90** [comment]
> @irishabhyadav90 what Xcode version are you using?

im using Xcode version 10.3
and my React-native version in 0.61.5

**Comment by jitendralakhmani-proptiger** [comment]
@irishabhyadav90 Yes, It worked by updating Xcode to 11.4. But I believe this lib should work for Xcode 10.4 as well.

**Comment by Nautiyalsachin** [comment]
@jitendralakhmani-proptiger, This won't work on Xcode 10.3, From now onwards we are supporting Xcode 11+. Please always prefer the latest XCode for development. 

Closing this issue, feel free to reopen if the Xcode update does not solve it.

**Comment by jitendralakhmani-proptiger** [comment]
> @jitendralakhmani-proptiger, This won't work on Xcode 10.3, From now onwards we are supporting Xcode 11+. Please always prefer the latest XCode for development.
> 
> Closing this issue, feel free to reopen if the Xcode update does not solve it.

I believe this must be mentioned somewhere in Readme or Docs.
