### ISSUE TITLE
Bit Code 

### ISSUE THREAD

**Issue by dharmusharma1981** [razorpay/react-native-razorpay#26]
So Im able to make razor pay run on ios emulator  but when i try to install that on phone i get this build error
iphoneos/libRazorpayCheckout.a(RazorpayCheckout.o)' does not contain bitcode. You must rebuild it with bitcode enabled (Xcode setting ENABLE_BITCODE), obtain an updated library from the vendor, or disable bitcode for this target. for architecture arm64

I downloaded the bit code version file  file from and did the manual installtion 
https://github.com/razorpay/razorpay-ios-sample-app/releases/tag/v0.15.0
and 
http://downloads.razorpay.com/Razorpay.framework-0.15.0-bitcode.zip

Both dint gives the same compiling 

However it works if i set the enabled bit code setting to false on project build setting

**Comment by dharmusharma1981** [comment]
Well I fixed it by enabling the bit code on razorpay xcode project level and the above files worked fine

**Comment by sagark1510** [comment]
@dharmusharma1981 I got the same error and tried doing what you mentioned but still having same issue.
