### ISSUE TITLE
App is crashing on android phone when getting success response, getting failure response or canceling the payment page.

### ISSUE THREAD

**Issue by Reactongraph** [razorpay/react-native-razorpay#267]
## Description

Please provide a clear and concise description of what the bug is. Include screenshots if needed.
Please test using the latest React Native Razorpay plugin release to make sure your issue has not already been fixed. 

## Razorpay Package Version :
Open `Package.json`. > Copy `react-native-razorpay` version here. 

## Xcode Version (iOS) :
Open Xcode > Go to `About Xcode` > copy the Xcode version here.

## Java and Gradle Version (android) :
Specify your Java and Gradle version.

## Steps To Reproduce
Provide a detailed list of steps that reproduce the issue.

1.
2.

## Code example, screenshot, or link to a repository:
Please provide a link to a repository on GitHub, or provide a minimal code example that reproduces the problem.
You may provide a screenshot of the application if you think it is relevant to your bug report.
Here are some tips for providing a minimal example: https://stackoverflow.com/help/mcve

**Comment by sanjeevkse** [comment]
Did you find any solution?

**Comment by vivekshindhe** [comment]
@sanjeevkse could you please fill out the template? That helps us a lot when it comes to debugging issues like this.

**Comment by vivekshindhe** [comment]
Closing this issue due to no response from your side. Please feel free to either re-open the issue or create a new issue if you have any additional queries.
