### ISSUE TITLE
App is crashing on android phone when getting success response, getting failure response or canceling the payment page.

### ISSUE THREAD

**Issue by Reactongraph** [razorpay/react-native-razorpay#268]
Here is my configuration ===>

"react": "16.11.0",
"react-native": "0.62.0",
"react-native-razorpay": "^2.1.33"

Android Version: 5.1
Device: Oppo F1 S

How to replicate:

Created Order Id

then here is my front-end code

const RazorPayOptions = {
      description: "Your total amount to pay:",
      // currency: "INR",
      key: "----my key=---",
      order_id: "--myorder id here----"
    };
    Razorpay.open(RazorPayOptions)
      .then(async data => {
        // handle success
        await console.log(`Success: `, data);
      })
      .catch(async error => {
        // handle failure
        await console.log(`Error:== `, error);
      });

**Comment by sanjeevkse** [comment]
[267](https://github.com/razorpay/react-native-razorpay/issues/267) duplicate issue.
