### ISSUE TITLE
Size of SDK

### ISSUE THREAD

**Issue by sudonitesh** [razorpay/react-native-razorpay#272]
After adding this package, the apk size increased more than 9mb. Is there any way to reduce the size? As the package size is 10.8mb.

**Comment by Nautiyalsachin** [comment]
Please provide more specific details like build environment, also sometimes it increases because of the internal react-native dependencies. Also try to update to our latest react-native plugin version, that might solve this issue. 

Closing this issue now, feel free to re-open or add more comments.
