### ISSUE TITLE
handle modal dismiss

### ISSUE THREAD

**Issue by ArcadeRenegade** [razorpay/react-native-razorpay#28]
hi, is it possible to create a handler for when the RazorPay checkout modal is dismissed? i tried passing a function as options.modal.ondismiss but it does not seem to run.

**Comment by akshaybhalotia** [comment]
Modal dismiss will return error code 2. You can handle it in the error handler.

**Comment by ArcadeRenegade** [comment]
It will trigger the error handler on modal close sometimes but not always.

**Comment by ArcadeRenegade** [comment]
On Android. BTW.

**Comment by akshaybhalotia** [comment]
It should _always_ be calling the error handler. Could you let us know the steps to reproduce the scenario when it doesn't?

cc @mb-14
