### ISSUE TITLE
Unable to build project with react-native-razorpay in iOS, 'RazorpayCheckout' has different definitions in different modules; first difference is defined here found 1 referenced protocol

### ISSUE THREAD

**Issue by abthkr** [razorpay/react-native-razorpay#286]
## Description
Project does not build in iOS with ```react-native-razorpay```

* **Specific to iOS Users :-**
- [x] I have tried updating Razorpay pod to the latest version by using 'pod update'.

## Razorpay Package Version :
2.1.36

## Xcode Version (iOS) :
Version 12.0 beta 3 (12A8169g)

## Razorpay-pod version (iOS) :
- razorpay-pod (1.1.6)

### What you did:

I created a fresh new project, which ran successfully  and then performed
```npm i react-native-razorpay```,
and ```pod install``` in ios folder.

### What happened:

![Screenshot 2020-08-05 at 12 27 35 PM](https://user-images.githubusercontent.com/14905647/89381635-197c0800-d717-11ea-9edb-cdd7a537191a.png)

I did not install any dependency apart from ```react-native-razorpay```, it just fails in XCode during
build phase, producing this error:

### 'RazorpayCheckout' has different definitions in different modules; first difference is defined here found 1 referenced protocol
which points to ```RazorpayCheckout.h```

## Steps To Reproduce
Provide a detailed list of steps that reproduce the issue.

1. ```npx react-native init Tresdo```
2. ```npm i react-native-razorpay```
3. ```cd ios && pod install```
4. Opened ```Tresdo.xcworkspace``` in Xcode, cleaned project, then build

**Comment by Nautiyalsachin** [comment]
Hi @abthkr, Can you try with a stable Xcode version, react-native is having some issue with XCode 12 (beta).

**Comment by abthkr** [comment]
> Hi @abthkr, Can you try with a stable Xcode version, react-native is having some issue with XCode 12 (beta).

Thanks, that worked

**Comment by Arun-paramasivam** [comment]
Hi,
I am using Xcode 12.0 stable version(updated today). I face the same issue. Tried clearing cache and building and quitting Xcode but none worked. It was working on the 11.7 version of the Xcode. How to resolve it?

**Comment by niyasmhdth** [comment]
Facing same issue Arun-paramasivam, Xcode in stable version, but still facing same issue, switching to 11.7 works

**Comment by pm-sharma** [comment]
Facing the same issue. Does anyone find the solution for Xcode 12?

**Comment by sumedht** [comment]
@Nautiyalsachin
