### ISSUE TITLE
App crashes when doing react-native run-android

### ISSUE THREAD

**Issue by benjaminlogan420** [razorpay/react-native-razorpay#287]
## Description
Hi ! After installing the package and doing "react-native run-android", app is getting crashed. It is throwing an error "**java.lang.RuntimeException: Unable to load script. Make sure you're either running a Metro server (run 'react-native start') or that your bundle 'index.android.bundle' is packaged correctly for release.**" Please note that I am not running the app for release, I am just running the app in debug mode. 

However, I was able to run the app by generating the index.android.bundle file, but it ran the app in release mode. This was not what I wanted, because I can't test the app in release mode. 

For a workaround, I changed the gradle version in **project/build.gradle to '3.4.2' from '3.5.3' and it worked in debug mode**. However, I think it may not be the best solution as it may create problems for other dependencies. Kindly look into this asap.

React-Native version: 0.63.2,  
react-native-razorpay: 2.1.36

**Comment by JayeshPatil-Dev** [comment]
Same issue.

**Comment by ambujap94** [comment]
We have tried and can not reproduce the issue at our end. Also, it does not seem to be an issue with the Razorpay SDK.
Please declare the minSdkVersion accordingly, if not declared.

**Comment by vivekshindhe** [comment]
@benjaminlogan420 @JayeshPatil-Dev did it solve the issue for you guys?

**Comment by vivekshindhe** [comment]
Closing this issue due to no response from your side. Please feel free to either re-open the issue or create a new issue if you have any additional queries.
