### ISSUE TITLE
Razorpay Payment Window Not Open

### ISSUE THREAD

**Issue by sourabhkheterpal** [razorpay/react-native-razorpay#29]
Hello,
App runs fine and Payment screen comes when i tried it by creating new react native app, But when i am trying to include in my App, its not showing me razorpay payment screen and no error is coming in console.

I am using https://github.com/wix/react-native-navigation for navigation purpose, i think due to this it malfunctioned. can any one help me in this? 
I have no knowledge in Android/iOS.

react-native 0.44.0
react 16.0.0-alpha.6
react-native-navigation 1.1.79
react-native-razorpay 1.2.1

ENV: ANDROID

Thanks.

**Comment by sourabhkheterpal** [comment]
@akshaybhalotia:  **For produce this case**: You can install react-native-navigation demo app from here https://github.com/JuneDomingo/movieapp and add razorpay at home screen for test. Payment window not open.

Thanks.

**Comment by sourabhkheterpal** [comment]
@akshaybhalotia  @mb-14  : Guys, can you please help regarding this?

**Comment by mb-14** [comment]
@sourabhkheterpal This issue occurs because the `react-native-navigation` library uses the `support.v4` version of FragmentActivity which does not play well with our SDK. We will be release a fix for this in the next week.

**Comment by sourabhkheterpal** [comment]
@mb-14 : Thanks. Please update when you fix this.

**Comment by sourabhkheterpal** [comment]
Thanks... It works.
