### ISSUE TITLE
UPI (PhonePe, Google Pay) integration not working

### ISSUE THREAD

**Issue by rajeshmarotu** [razorpay/react-native-razorpay#295]
## Description
Redirection to UPI apps like Google Pay and PhonePe are not working.

When PhonePe is selected for redirection, it is showing "something went wrong" alert box.

## Razorpay Package Version :
2.2.0

## Java and Gradle Version (android) :
java version "1.8.0_181"
gradle version 3.4.0

### What you did:
Followed react native integration docs.

### What happened:
![Screenshot_20200923-145442](https://user-images.githubusercontent.com/31095629/93994220-48286d80-fdad-11ea-94c7-c36304ddab95.png)

**Comment by gourabghosh1** [comment]
@rajeshmarotu please share your merchant id ?

**Comment by gourabghosh1** [comment]
@rajeshmarotu Its possible that, due to some configuration mismatch on your account level , this error is throwing . We have to check that , so kindly share us the Merchant id or the payment for the same , so that we can check internally.

**Comment by ashokkumar88** [comment]
@gourabghosh1 We are having same issue with Paytm also. When selecting Paytm from UPI Apps it is showing "You have entered an incorrect UPI ID". The UPI ID showing as upi@razorpay.  For these to work in UPI Apps Paytm, Phonepe need to enabled in our account?

**Comment by vivekshindhe** [comment]
@ashokkumar88 the UPI ID is set on the merchant dashboard on the website. If that's not set up it'll take the default value. Also, upi@razorpay is not a valid UPI ID and hence the error. Could you please check in your account and add the UPI ID where you'd want to collect the payment? It should start working then.

**Comment by sumedht** [comment]
@ashokkumar88 have u tried by passing valid UPI ID?Are u still facing this issue?

**Comment by ashokkumar88** [comment]
@vivekshindhe @sumedht I checked in the release build and it is working fine as expected.

**Comment by sumedht** [comment]
thanks, @ashokkumar88 for updating. Closing this ticket

**Comment by Chillkrt** [comment]
Hii  
I'm finding some issues while redirection for upi !!!!
![WhatsApp Image 2021-07-14 at 11 43 01 AM](https://user-images.githubusercontent.com/75985773/127109685-29500186-9ab3-4af6-96f0-4eb8b07077ac.jpeg)

**Comment by 04amitpanchal** [comment]
@ashokkumar88 How can we set UPI id in razor pay dashboard.

**Comment by ashokkumar88** [comment]
@04amitpanchal My UPI id issue was in the debug build. In the release build it is working fine. The UPI id is set by Razorpay and it is not configurable from dashboard. Though you can create Virtual accounts with custom UPI ids from Smart Collect page. Or you can request them for a custom UPI id.
