### ISSUE TITLE
com.razorpay.AnalyticsConstants error after install these package

### ISSUE THREAD

**Issue by mitalpatel5944** [razorpay/react-native-razorpay#298]
* **Common to Both platforms :-**

  - [ ] I have gone through the README (https://github.com/razorpay/react-native-razorpay)
  - [ ] I have searched for a similar issue (https://github.com/razorpay/react-native-razorpay/issues)
  - [ ] I am using the latest version of our framework (https://github.com/razorpay/react-native-razorpay/releases)
  - [ ] I have cleaned my project.
  - [ ] I have gone through FAQ's (https://github.com/razorpay/react-native-razorpay/wiki/FAQ's)

* **Specific to iOS Users :-**

  - [ ] I have modified the module map as specified in the readme (https://github.com/razorpay/react-native-razorpay)
  - [ ] I have deleted the contents of the derived data folder and rebuild it.

**Comment by sumedht** [comment]
@mitalpatel5944
Can u share more log/error of this? Try to clear cache & re-integrate the latest version of SDK

**Comment by Nautiyalsachin** [comment]
Closing this issue due to no response, feel free to reopen or add comments.
