### ISSUE TITLE
After sucees or fail payment application force close. react-native 0.63.2

### ISSUE THREAD

**Issue by mitalpatel5944** [razorpay/react-native-razorpay#299]
## Description
Please provide a clear and concise description of what the bug is. Include screenshots if needed.
Please test using the latest React Native Razorpay plugin release to make sure your issue has not already been fixed. 

* **Specific to iOS Users :-**
- [ ] I have tried updating Razorpay pod to the latest version by using 'pod update'.

## Razorpay Package Version :
Open `Package.json`. > Copy `react-native-razorpay` version here. 

## Xcode Version (iOS) :
Open Xcode > Go to `About Xcode` > copy the Xcode version here.

## Razorpay-pod version (iOS) :
Go to your project path > Go to folder named `ios`  > open 'podfile.lock' file > search for 'razorpay-pod' > copy the line here 

## Java and Gradle Version (android) :
Specify your Java and Gradle version.

## Steps To Reproduce
Provide a detailed list of steps that reproduce the issue.

1.
2.

## Code example, screenshot, or link to a repository:
Please provide a link to a repository on GitHub, or provide a minimal code example that reproduces the problem.
You may provide a screenshot of the application if you think it is relevant to your bug report.
Here are some tips for providing a minimal example: https://stackoverflow.com/help/mcve

**Comment by adsalihac** [comment]
Anybody get solution .

**Comment by Nautiyalsachin** [comment]
Hi @mitalpatel5944, @adsalihac Can you share some logs, this error is not helping in debugging this issue.

**Comment by adsalihac** [comment]
@Nautiyalsachin 
Close payment screen
{"description":"{\"error\":{\"code\":\"BAD_REQUEST_ERROR\",\"description\":\"Payment processing cancelled by user\",\"source\":\"customer\",\"step\":\"payment_authentication\",\"reason\":\"payment_cancelled\"}}","code":0,"error":{"reason":"payment_cancelled","step":"payment_authentication","source":"customer","description":"Payment processing cancelled by user","code":"BAD_REQUEST_ERROR"}}

**Comment by adsalihac** [comment]
@Nautiyalsachin  solved my issue , i used another upi payment package , [https://www.npmjs.com/package/react-native-upi-payment)] , removed this package , razorpay working fine , but i  couldn't understand what the issue . thank you .
