### ISSUE TITLE
App Rejection Warning from Play Store

### ISSUE THREAD

**Issue by emanu7478** [razorpay/react-native-razorpay#300]
Hi, Iam using Razorpay plugin in my React native project. But when I tried to upload my app in play store, I had received a rejection warning mail as like shown below

**Intent Redirection**
Your app(s) are vulnerable to Intent Redirection.
To address this issue, follow the steps in this Google Help Center article.

I'am using `"react-native-razorpay": "^2.2.1"`  version

I had tried #291  but it doesn't resolved my issue. 

Please suggest any solution for this issue ?

**Comment by vivekshindhe** [comment]
@emanu7478 Can you please confirm you cleared the cached version of the npm package?? We've seen that this is one of the reasons we see this problem still exists. If not, could you please clear the cached version and integrate fresh and let us know??

**Comment by sumedht** [comment]
@emanu7478 any update on this?

**Comment by emanu7478** [comment]
> @emanu7478 Can you please confirm you cleared the cached version of the npm package?? We've seen that this is one of the reasons we see this problem still exists. If not, could you please clear the cached version and integrate fresh and let us know??

**Comment by emanu7478** [comment]
Issue Resolved

**Comment by faisalmushtaq007** [comment]
@emanu7478  please tell me how???
