### ISSUE TITLE
Fix Conflict on npm install react-native-razorpay

### ISSUE THREAD

**Issue by kartavyaparekh96** [razorpay/react-native-razorpay#302]
npm ERR! code ERESOLVE
npm ERR! ERESOLVE unable to resolve dependency tree
npm ERR! 
npm ERR! While resolving: byFarmerz@0.0.1
npm ERR! Found: react-native@0.62.2
npm ERR! node_modules/react-native
npm ERR!   react-native@"0.62.2" from the root project
npm ERR! 
npm ERR! Could not resolve dependency:
npm ERR! peer react-native@"^0.57.1" from react-native-razorpay@2.2.1
npm ERR! node_modules/react-native-razorpay
npm ERR!   react-native-razorpay@"*" from the root project
npm ERR! 
npm ERR! Fix the upstream dependency conflict, or retry
npm ERR! this command with --force, or --legacy-peer-deps
npm ERR! to accept an incorrect (and potentially broken) dependency resolution.
npm ERR! 
npm ERR! See /Users/kartavya/.npm/eresolve-report.txt for a full report.

npm ERR! A complete log of this run can be found in:
npm ERR!     /Users/kartavya/.npm/_logs/2020-11-10T08_02_19_249Z-debug.log
s

**Comment by Nautiyalsachin** [comment]
Hey @kartavyaparekh96, the above logs are not helping for resolving the issue, please create a new issue with asked details and don't remove them or the issue will also be closed.
