### ISSUE TITLE
Unable to take iOS Signed Build

### ISSUE THREAD

**Issue by ratheeshramachandran** [razorpay/react-native-razorpay#307]
React-Native : 0.63.0
Razorpay: 2.2.1
Podfile iOS version 10.0

App work fine with emulator. But when I tried to take a signed build got following issue.

tries with this script too . (http://ikennd.ac/blog/2015/02/stripping-unwanted-architectures-from-dynamic-libraries-in-xcode/)

<img width="748" alt="Screenshot 2020-12-03 at 11 42 37 AM" src="https://user-images.githubusercontent.com/762990/100972688-30b0f200-355f-11eb-9fae-f0afafe098e8.png">

**Comment by Nautiyalsachin** [comment]
Hi @ratheeshramachandran, you don't have to use the script when using pods, can you share the XCode and swift version here.

**Comment by ratheeshramachandran** [comment]
Xcode 11.6
Swift version 5

**Comment by Nautiyalsachin** [comment]
@ratheeshramachandran, it looks like you have changed some settings in your project which is not allowing it to create a release build. 

I would suggest to try our [sample app](https://github.com/razorpay/react-native-razorpay/tree/master/example/SampleProject) and compare the build settings options. 

Also, please try removing the above script.

**Comment by rutul089** [comment]
@ratheeshramachandran  I am also getting the same type of error any solution?  I am not using the above script too.
![razrorpay](https://user-images.githubusercontent.com/13690583/101975536-52972c80-3c63-11eb-9c9d-476243ec151b.PNG)

**Comment by Nautiyalsachin** [comment]
Hey @rutul089, @ratheeshramachandran Please try with the latest updated SDK v2.2.2. Let us know how that went for you. Closing the issue for now. Feel free to comment or open a new issue if it's still persists.

**Comment by rutul089** [comment]
Hey @Nautiyalsachin , 
Tried with the latest SDK but still facing the same issue. In the simulator, it's working fine

**Comment by Nautiyalsachin** [comment]
@rutul089, as mentioned above, please try downloading our [sample app](https://github.com/razorpay/react-native-razorpay/tree/master/example/SampleProject) and try to compile it locally. Also, suggest you to go through our [FAQ section](https://github.com/razorpay/react-native-razorpay/wiki/FAQ's).

**Comment by bishalinkoop** [comment]
Ios signed build is not working, tried sample app it's also raising same error
Xcode version -> 12.2
react-native-razorpay -> 2.2.2
`
![Screenshot 2021-01-21 at 1 01 30 PM](https://user-images.githubusercontent.com/73817418/105318175-509d8300-5baa-11eb-8918-a93456656e77.png)
`

**Comment by HemanthSurimani** [comment]
hi @Nautiyalsachin Iam also facing same issue

using versions:
"react": "16.13.1",
"react-native": "0.63.3",
"react-native-razorpay": "^2.2.4",
 
Version 11.5 (11E608c)
Shift5

**Comment by Nautiyalsachin** [comment]
@HemanthSurimani Please upgrade your XCode to the latest version as replied on https://github.com/razorpay/react-native-razorpay/issues/328

**Comment by HemanthSurimani** [comment]
Hi @Nautiyalsachin 
After updating my Xcode Version 11.5 to 12.4 issue got resolved 

Thanks @Nautiyalsachin
