### ISSUE TITLE
 'RazorpayCheckout' has different definitions in different modules

### ISSUE THREAD

**Issue by kharsuanoop** [razorpay/react-native-razorpay#308]
Razorpay Package Version - 2.2.1

Xcode Version - 12.2

React Native - 0.61.5

error comes when building iOS app 
**(** /Users/userName/Desktop/app/node_modules/react-native-razorpay/ios/RazorpayCheckout.h:11:12: 'RazorpayCheckout' has different definitions in different modules; first difference is defined here found 1 referenced protocol **)**

![Untitled](https://user-images.githubusercontent.com/75444620/101071120-2d028700-35c2-11eb-890f-2d49b7a7e1ef.png)

**Comment by Nautiyalsachin** [comment]
Hi @kharsuanoop, this is a repeated issue of https://github.com/razorpay/react-native-razorpay/issues/292, Please find the workaround mentioned there, we are also releasing a new version soon. Thanks.

**Comment by musadiq123** [comment]
I wasted 2 days for this issue in Xcode 12.4. finally resolved by this link. check out 
https://github.com/razorpay/react-native-razorpay/pull/297/files/ea490ff7669c629010a74f41de6c4d61a74c1c05

**Comment by sachin-blinkdigital** [comment]
> I wasted 2 days for this issue in Xcode 12.4. finally resolved by this link. check out https://github.com/razorpay/react-native-razorpay/pull/297/files/ea490ff7669c629010a74f41de6c4d61a74c1c05

Thanks for saving my day. It works.
