### ISSUE TITLE
Android: Payment view got dismissed on App enters background.

### ISSUE THREAD

**Issue by sivakumar-cf** [razorpay/react-native-razorpay#31]
I initiated payment view , and put my app in background to view the sms OTP code. when I return back, Payment view got dismissed. This issue is happening on latest release.

**Comment by akshaybhalotia** [comment]
@sivakumar-cf Is this for iOS or Android?

**Comment by sivakumar-cf** [comment]
@akshaybhalotia  closing this issue, it was a mistake on my side, added launchMode as SingleTask in MainActivity
