### ISSUE TITLE
RazorpayCheckout.m normal x86_64 objective-c com.apple.compilers.llvm.clang.1_0.compiler (1 failure)

### ISSUE THREAD

**Issue by hackrx** [razorpay/react-native-razorpay#310]
## Description
Ios build failed with an error:
```
CompileC /Users/hackrx/Library/Developer/Xcode/DerivedData/myapp-cmdzqollezpksnebxpzzqyfmgiqn/Build/Intermediates.noindex/Pods.build/Debug-iphonesimulator/react-native-razorpay.build/Objects-normal/x86_64/RazorpayCheckout.o /Volumes/removeDisk/myapp/node_modules/react-native-razorpay/ios/RazorpayCheckout.m normal x86_64 objective-c com.apple.compilers.llvm.clang.1_0.compiler
(1 failure)
```
* **Specific to iOS Users :-**
- [x] I have tried updating Razorpay pod to the latest version by using 'pod update'.

## Razorpay Package Version :
Open `Package.json`. > Copy `react-native-razorpay` 2.2.1. 

## Xcode Version (iOS) :
Open Xcode > Go to `About Xcode` > copy the Xcode: Version 12.1 (12A7403)

## Razorpay-pod version (iOS) :
Go to your project path > Go to folder named `ios`  > open 'podfile.lock' file > search for 'razorpay-pod' > 
  - razorpay-pod (1.1.10)
- react-native-razorpay (2.2.1):
    - razorpay-pod
    - React

### What you did:
`yarn add react-native-razorpay`
`cd ios && pod install`
`yarn react-native run-ios`

It is working fine on android.

**Comment by Nautiyalsachin** [comment]
Hey @hackrx, we have released a new package version v2.2.2. Please update to the latest version, it should fix the issue.

**Comment by hackrx** [comment]
Hey @Nautiyalsachin , after upgrading to `2.2.2` version I am getting this error
```$ react-native run-ios
error React Native CLI uses autolinking for native dependencies, but the following modules are linked manually: 
  - react-native-razorpay (to unlink run: "react-native unlink react-native-razorpay")
This is likely happening when upgrading React Native from below 0.60 to 0.60 or above. Going forward, you can unlink this dependency via "react-native unlink <dependency>" and it will be included in your app automatically. If a library isn't compatible with autolinking, disregard this message and notify the library maintainers.```

**Comment by Nautiyalsachin** [comment]
@hackrx Which react-native version are you using?

**Comment by hackrx** [comment]
```
    "react-native": "0.63.0",

```

**Comment by Nautiyalsachin** [comment]
Try removing the plugin and adding it again. @hackrx

**Comment by hackrx** [comment]
[link](https://firebasestorage.googleapis.com/v0/b/hostel-life-70814.appspot.com/o/example%2Fcat.jpg?alt=media&token=743f799d-19e8-4464-b67d-a29e3ca93e08)
this is the image link
