### ISSUE TITLE
Unable to Build IOS app using react-native-razorpay

### ISSUE THREAD

**Issue by asagta** [razorpay/react-native-razorpay#311]
## Description
I am facing below issue while building a react native iOS app having razorpay as a dependency :+1: 
The following build commands failed:
	CompileC /Users/anurag/Library/Developer/Xcode/DerivedData/crc-fxakiqkgzdgasjfaudknzthgqkku/Build/Intermediates.noindex/Pods.build/Debug-iphonesimulator/react-native-razorpay.build/Objects-normal/x86_64/RazorpayCheckout.o /Users/anurag/Documents/Archive\ 2/node_modules/react-native-razorpay/ios/RazorpayCheckout.m normal x86_64 objective-c com.apple.compilers.llvm.clang.1_0.compiler

Node-Modules : "react": "16.13.1",
    "react-native": "0.63.3","react-native-razorpay": "^2.2.1"
PODS : - react-native-razorpay (2.2.1):
    - razorpay-pod
    - React
razorpay-pod (1.1.10)

* **Specific to iOS Users :-**
- I have tried updating Razorpay pod to the latest version by using 'pod update'.

## Razorpay Package Version :
Open `Package.json`. > "react-native-razorpay": "^2.2.1"

## Xcode Version (iOS) :
Open Xcode > Go to `About Xcode` > 12.2

## Razorpay-pod version (iOS) :
Go to your project path > Go to folder named `ios`  > open 'podfile.lock' file > search for 'razorpay-pod' > 2.2.1 

## Java and Gradle Version (android) : Android Works Fine
Specify your Java and Gradle version.

### What you did:
Ran react-native run-ios

### What happened:
Faced below issue : 
The following build commands failed:
	CompileC /Users/anurag/Library/Developer/Xcode/DerivedData/crc-fxakiqkgzdgasjfaudknzthgqkku/Build/Intermediates.noindex/Pods.build/Debug-iphonesimulator/react-native-razorpay.build/Objects-normal/x86_64/RazorpayCheckout.o /Users/anurag/Documents/Archive\ 2/node_modules/react-native-razorpay/ios/RazorpayCheckout.m normal x86_64 objective-c com.apple.compilers.llvm.clang.1_0.compiler

## Steps To Reproduce
Provide a detailed list of steps that reproduce the issue.

1. Build the app in xcode or use react-native run-ios. Make sure razor pay module is imported in your code.
2. Faced issue

**Comment by Nautiyalsachin** [comment]
Hi @asagta, Can you try updating to the latest react native plugin and let me know if it works for you. The latest version is 2.2.2. 

Regards, 
Sachin
