### ISSUE TITLE
Feature Request: Intent Flow for UPI payments in custom checkout implementation(react-native-customui)

### ISSUE THREAD

**Issue by mprem1204** [razorpay/react-native-razorpay#312]
Currently Intent flow for UPI Payments is not available for React_native(react-native-customui),the intent upi flow is very important feature for the customers who dont remember the upi number while doing a payment.
Your team right now is providing a custom checkout ui for react native with react-native-customui SDK but it does not contain intent UPI flow.
Intent UPI flow is available in all the custom checkout implementations(like Android Sdk,Web etc) but it is not available for react-native custom checkout SDK.
With react-native being the best hybrid mobile application framework have the intent UPI flow to react-native-customui package will be a greate Addition

**Comment by Nautiyalsachin** [comment]
Hey @mprem1204, Definitely we will consider your thoughts on this in future releases. This will definitely take some time to roll out as we want to give you a bug-free integration experience 😊. we will update you on the same issue soon.

**Comment by mprem1204** [comment]
Hii @Nautiyalsachin. Any update regarding the Intent Flow in react-native-customui feature.

**Comment by Nautiyalsachin** [comment]
Hi @mprem1204, We are working on this feature right now, we will be releasing it soon, I'll give you an update here. Thanks.

**Comment by Nautiyalsachin** [comment]
Hi @mprem1204, this feature is released. You can see our updated docs on the react-native plugin. Closing this issue now, if you still have any query then feel free to add more comments here or create a new issue. Thanks.

**Comment by CHANDRAMOHANnegi** [comment]
use this Doc

https://razorpay.com/docs/payment-gateway/react-native-integration/custom/

**Comment by rvuyyuru1** [comment]
no proper documentation or how to use Intent Flow in react-native-customui

**Comment by anshul0410** [comment]
Hi @Nautiyalsachin thanks for introducing UPI intent flow in custom checkout flow.
Currently in React Native Custom Checkout documentation, it is not clear how to make use of UPI intent flow since i don't see any section pertaining to it. Can i refer some url which contains detailed information on how to use UPI Intent in custom checkout.
Thanks

**Comment by ashishtwr314** [comment]
https://www.npmjs.com/package/react-native-customui#:~:text=%7D%7D%3E-,UPI%20Intent%20flow,-For%20using%20UPI

Use this doc
