### ISSUE TITLE
React Native Custom UI - framework not found Razorpay

### ISSUE THREAD

**Issue by sathishkrishnan20** [razorpay/react-native-razorpay#319]
Getting "framework not found Razorpay"  error. while integrating React-native-customui

Steps followed
 1. Added the Razropay.xcodeproj into Project Libraries
 2. Added libRazorPay.a into **Frameworks, Libraries and Embeded Content**
 3. Added RazorPay.framework into **Frameworks, Libraries and Embeded Content**
 4. Added `$(SRCROOT)/../react-native/React and $(SRCROOT)/../../React` into **Header Search Path**

**Comment by Nautiyalsachin** [comment]
Hey @sathishkrishnan20, can you share the details here like Xcode Version, SDK version, Swift version, etc.

**Comment by sathishkrishnan20** [comment]
Hi @Nautiyalsachin , thanks for the response, and sharing the details here
Xcode Version: 11.4
Swift Version: 5
SDK:  iphoneos13.7

**Comment by Nautiyalsachin** [comment]
@sathishkrishnan20 Can you try downloading [this SDK](https://rzp-mobile.s3.amazonaws.com/ios/customui/1.3.9/Razorpay.xcframework.zip) and replace existing one. Please follow above steps again.

**Comment by sathishkrishnan20** [comment]
Can you give me the steps Replace this SDK?  i see two or three foldrs when i exctract the Zip

**Comment by Nautiyalsachin** [comment]
You have to replace the whole .xcframework with .framework in your code. Just search for Razorpay.framework and replace it with Razorpay.xcframework file. All the process and steps will be the same.

**Comment by sathishkrishnan20** [comment]
Getting Below Error after replacing the Razorpay.xcframework file.
Undefined symbol: _OBJC_CLASS_$__TtC8Razorpay8Razorpay

**Comment by sathishkrishnan20** [comment]
It is failing for Android as well

Getting Below Error on Android 
```
 Could not determine the dependencies of task ':app:mergeDebugAssets'.
> Could not resolve all task dependencies for configuration ':app:debugRuntimeClasspath'.
   > Could not find :razorpay-android:.
     Required by:
         project :app > project :react-native-customui

```

**Comment by Nautiyalsachin** [comment]
@sathishkrishnan20 Please wait for some days, I'll be updating the existing plugin so that you don't face these issues.

**Comment by sathishkrishnan20** [comment]
thanks, please try adding the auto Linking podspec file if possible. so that we can avoid the Manual linking process. and it helps for long run

**Comment by Nautiyalsachin** [comment]
We are thinking about it, we will be releasing a pod for Razorpay Custom UI. Will update you on the same here. For now, closing this issue.

**Comment by CHANDRAMOHANnegi** [comment]
use this Doc
https://razorpay.com/docs/payment-gateway/react-native-integration/custom/
