### ISSUE TITLE
Exception '-[Razorpay setExternalWalletSelectionDelegate:]: unrecognized selector sent to instance 0x7ff38a6ea620'

### ISSUE THREAD

**Issue by AliHasnainRizvi** [razorpay/react-native-razorpay#32]
In iOS , when the button is clicked, this error shows up. Though i've removed the external wallet support , its working fine with both iOS and android. But paytm / externat wallet is needed! 
Thanks!

**Comment by Mayur-Wadpalliwar** [comment]
https://docs.razorpay.com/v1/page/listing-external-wallets#listing-external-wallet-on-ios-sdk

**Comment by paritosh-yadav** [comment]
can't figure out the solution for this, Please help...
