### ISSUE TITLE
App crash due to NullPointerException at com.razorpay.AutoReadOtpHelper.onReceive

### ISSUE THREAD

**Issue by ketan1062** [razorpay/react-native-razorpay#321]
`03-03 18:37:11.967 E/AndroidRuntime( 9181): FATAL EXCEPTION: main`
`03-03 18:37:11.967 E/AndroidRuntime( 9181): Process: com.myapp, PID: 9181`
`03-03 18:37:11.967 E/AndroidRuntime( 9181): java.lang.RuntimeException: Error receiving broadcast Intent { act=com.google.android.gms.auth.api.phone.SMS_RETRIEVED flg=0x200010 pkg=com.myapp (has extras) } in com.razorpay.AutoReadOtpHelper@15d83da`
`03-03 18:37:11.967 E/AndroidRuntime( 9181): 	at android.app.LoadedApk$ReceiverDispatcher$Args.lambda$getRunnable$0$LoadedApk$ReceiverDispatcher$Args(LoadedApk.java:1566)`
`03-03 18:37:11.967 E/AndroidRuntime( 9181): 	at android.app.-$$Lambda$LoadedApk$ReceiverDispatcher$Args$_BumDX2UKsnxLVrE6UJsJZkotuA.run(Unknown Source:2)`
`03-03 18:37:11.967 E/AndroidRuntime( 9181): 	at android.os.Handler.handleCallback(Handler.java:883)`
`03-03 18:37:11.967 E/AndroidRuntime( 9181): 	at android.os.Handler.dispatchMessage(Handler.java:100)`
`03-03 18:37:11.967 E/AndroidRuntime( 9181): 	at android.os.Looper.loop(Looper.java:224)`
`03-03 18:37:11.967 E/AndroidRuntime( 9181): 	at android.app.ActivityThread.main(ActivityThread.java:7592)`
`03-03 18:37:11.967 E/AndroidRuntime( 9181): 	at java.lang.reflect.Method.invoke(Native Method)`
`03-03 18:37:11.967 E/AndroidRuntime( 9181): 	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:539)`
`03-03 18:37:11.967 E/AndroidRuntime( 9181): 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:950)`
`03-03 18:37:11.967 E/AndroidRuntime( 9181): Caused by: java.lang.NullPointerException`
`03-03 18:37:11.967 E/AndroidRuntime( 9181): 	at java.util.Objects.requireNonNull(Objects.java:203)`
`03-03 18:37:11.967 E/AndroidRuntime( 9181): 	at com.razorpay.AutoReadOtpHelper.onReceive(Unknown Source:52)`
`03-03 18:37:11.967 E/AndroidRuntime( 9181): 	at android.app.LoadedApk$ReceiverDispatcher$Args.lambda$getRunnable$0$LoadedApk$ReceiverDispatcher$Args(LoadedApk.java:1556)`
`03-03 18:37:11.967 E/AndroidRuntime( 9181): 	... 8 more`

**Comment by sumedht** [comment]
@ketan1062 we have fixed this. Looking to release in early next week

**Comment by rameshsambu-dev** [comment]
I am also facing the same issue in the production app

**Comment by sumedht** [comment]
@ketan1062 @rameshsambu-dev we have fixed this issue in a newer version of SDK.
