### ISSUE TITLE
Unknown type name 'RazorpayCheckout'

### ISSUE THREAD

**Issue by themanojk** [razorpay/react-native-razorpay#323]
### What happened:
When building the app through Xcode it is throwing error :
`Unknown type name 'RazorpayCheckout'; did you mean 'RNRazorpayCheckout'`

## Steps To Reproduce

1. Intsall the package
2. change the ios version in podfile to 10.0
3. pod install
4. Build the app

Screenshot Link for the same: [https://ibb.co/7W1nkDz](url)

**Comment by Nautiyalsachin** [comment]
Hi @themanojk, can you share a screenshot showing this issue. Thanks.

**Comment by themanojk** [comment]
@Nautiyalsachin i have added the screenshot link in the description..

**Comment by Nautiyalsachin** [comment]
Have you tried` pod update` from your ios folder?

**Comment by themanojk** [comment]
Yes i have... Pod version is already 2.2.4..

**Comment by Nautiyalsachin** [comment]
Can you try with XCode 12.3 or with any earlier XCode's?

**Comment by Nautiyalsachin** [comment]
I would also suggest you remove the plugin and also referencing this warning from official docs, you can also try the same. 

`If you previously installed a global react-native-cli package, please remove it as it may cause unexpected issues.
`

**Comment by themanojk** [comment]
Its working with 11.4 XCode version..

**Comment by Nautiyalsachin** [comment]
Closing the issue in that case, feel free to add more comments here.

**Comment by niyatiArunk** [comment]
![image](https://user-images.githubusercontent.com/60418567/118385131-05602200-b62a-11eb-8001-f70b7a1e9d27.png)
Check this image, i got this error, please let me know how to get it resolved

**Comment by sourav-singh-rawat** [comment]
Did anyone found solution for this?

**Comment by deepakverma4** [comment]
@Nautiyalsachin Everyone is not on 11.4 XCode version. So please suggest some global fix for this issue.

**Comment by shivamvk** [comment]
@Nautiyalsachin Why is this issue closed? I don't see downgrading to older version of Xcode as a solution to this. I need to fix this on the latest Xcode Version. Let me know if you can get on a call with me to resolve this.

**Comment by devanshsadhotra25** [comment]
facing this issue even now, any solution for anyone?

**Comment by ramprasadAnand** [comment]
@devanshsadhotra25 are you facing this issue on Apple M1 chip MacBook ?

**Comment by devanshsadhotra25** [comment]
> @devanshsadhotra25 are you facing this issue on Apple M1 chip MacBook ?

@ramprasadAnand  no, its an Intel one

**Comment by ramprasadAnand** [comment]
We are able to compile without any errors, with below versions. 

"dependencies": {
    "@react-native-community/cli": "^5.0.1",
    "react": "17.0.1",
    "react-native": "0.64.2",
    "react-native-base64": "^0.2.1",
    "react-native-eject": "^0.1.2",
    "react-native-elements": "^3.4.2",
    "react-native-razorpay": "^2.2.7",
    "typescript": "^4.3.4"
  },

Can you try with the latest versions of react-native and razorpay libraries and let us know if you still face the errors ?
