### ISSUE TITLE
Open method not working in iOS react native 

### ISSUE THREAD

**Issue by pareekkVipin** [razorpay/react-native-razorpay#324]
[TypeError: null is not an object (evaluating '_reactNative.NativeModules.RazorpayCheckout.open')]

already read all issue an pull request and also follow your #164 solutions but still error is coming please help me

**Comment by pareekkVipin** [comment]
ok sorry but issue resolved thank you

**Comment by vishvadavra** [comment]
how you solved this error? can you help me with this error?

[TypeError: null is not an object (evaluating '_reactNative.NativeModules.RazorpayCheckout.open')]
