### ISSUE TITLE
Razor Pay Not invoking Success Handler in React Native Webview

### ISSUE THREAD

**Issue by themanojk** [razorpay/react-native-razorpay#325]
I am using Expo for my react native app, I have integrated razor pay in webview, which is working on the web properly. The problem is occurring in webview after payment happens.. I can see on the webpage it is written the browser doesn't have javascript enabled, and after that, the success handler is not being invoked. I am able to do other javascript operations from the webpage like API call using fetch and other stuff.
Is there anything which I am not doing properly. Here is my code for webview.

`<WebView
        source={{ uri: this.state.url }}
        style={{ flex: 1, margin: 20 }}
        javaScriptEnabled={true}
        domStorageEnabled={true} />`

**Comment by sumedht** [comment]
@razorpay/techpgintegrations Can u check with webview integration here.

**Comment by AnoopRz** [comment]
@themanojk Please refer to this doc and make sure you are following the steps as mentioned here https://razorpay.com/docs/payment-gateway/web-integration/standard/webview/
