### ISSUE TITLE
Code signing "Razorpay.framework" failed

### ISSUE THREAD

**Issue by williemccool** [razorpay/react-native-razorpay#327]
Hi,

This error is again persistent even if we have used the solution mentioned in #213.
This in xcode 11.6 and react native 0.63

Please help us with this.

**Comment by jotkohlisegwitz** [comment]
have you find any solution @williemccool?

**Comment by Nautiyalsachin** [comment]
Hey @williemccool @jotkohlisegwitz, Please try using the latest XCode as every XCode has there owned internal dependencies. I would also recommend you remove the existing package and try adding it again. Let me know if it works for you.

**Comment by jotkohlisegwitz** [comment]
after re adding package issue fixed.

**Comment by Nautiyalsachin** [comment]
Closing this issue now. Feel free to add more comments here if this persists or create a new issue. Thanks.
