### ISSUE TITLE
Unable to generate ipa (iOS Signed Build) file

### ISSUE THREAD

**Issue by HemanthSurimani** [razorpay/react-native-razorpay#328]
ipatool failed with an exception: #<CmdSpec::NonZeroExitException: $ /Applications/Xcode-11.5.app/Contents/Developer/usr/bin/python3 /Applications/Xcode-11.5.app/Contents/Developer/usr/bin/bitcode-build-tool -v -t /Applications/Xcode-11.5.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin -L /var/folders/fq/lrgvk89s27nfw_x5rndb5j1r0000gs/T/ipatool20210425-7738-zcb34f/thinned-out/arm64/Payload/Devotee.app/Frameworks --sdk /Applications/Xcode-11.5.app/Contents/Developer/Platforms/iPhoneOS.platform/Developer/SDKs/iPhoneOS13.5.sdk -o /var/folders/fq/lrgvk89s27nfw_x5rndb5j1r0000gs/T/ipatool20210425-7738-zcb34f/thinned-out/arm64/Payload/Devotee.app/Frameworks/Razorpay.framework/Razorpay --generate-dsym /var/folders/fq/lrgvk89s27nfw_x5rndb5j1r0000gs/T/ipatool20210425-7738-zcb34f/thinned-out/arm64/Payload/Devotee.app/Frameworks/Razorpay.framework/Razorpay.dSYM --strip-swift-symbols /var/folders/fq/lrgvk89s27nfw_x5rndb5j1r0000gs/T/ipatool20210425-7738-zcb34f/thinned-in/arm64/Payload/Devotee.app/Frameworks/Razorpay.framework/Razorpay
Status: pid 9522 exit 1
Stdout:

    "react": "16.13.1",
    "react-native": "0.63.3",
    "react-native-razorpay": "^2.2.4",
     
    Version 11.5 (11E608c)
    Shift5
   - razorpay-pod (1.1.12)

### What you did:
While debugging mode it is working fine but generating ipa (iOS Signed Build) getting issue

![Screenshot from 2021-04-25 19-31-25](https://user-images.githubusercontent.com/40192235/115996932-e1975680-a5fe-11eb-9f1c-2ac11cffb6ea.png)

Thanks

**Comment by Nautiyalsachin** [comment]
Hi @HemanthSurimani, Please update your XCode to the latest, let me know if it persists.

**Comment by HemanthSurimani** [comment]
Hi @Nautiyalsachin  
After updating my Xcode Version 11.5 to 12.4 issue got resolved 

Thanks @Nautiyalsachin

**Comment by Nautiyalsachin** [comment]
Glad to hear that, closing this issue now.

**Comment by shivamKredX** [comment]
facing same issue with razorpay new version
