### ISSUE TITLE
RazoryPay Checkout Error Unknown Type

### ISSUE THREAD

**Issue by niyatiArunk** [razorpay/react-native-razorpay#333]
Check this image, I got this error, please let me know how to get it resolved using 
Razorpay, v2.2.5, 
Xcode v12.4, 
Razorpay-pod (Autolinking)(1.1.13) 
React-native v63.2, 
Works fine in Android only issue with Ios
![Untitled](https://user-images.githubusercontent.com/60418567/118385631-4ce8ad00-b62e-11eb-912b-88667dde5bac.png)

**Comment by vineeth-vk11** [comment]
@niyatiArunk are you using a M1 mac ?

**Comment by niyatiArunk** [comment]
> @niyatiArunk are you using a M1 mac ?
> 
> If yes please follow the below issue. We have a discussion going on there about this.
> 
> #331

I am using mac mini

**Comment by niyatiArunk** [comment]
it works fine now archive succeded, earlier I have changed the scheme to run as a release build that was causing the issue, now it working after reverting back.
