### ISSUE TITLE
[!] No podspec found for `react-native-customui` in `../node_modules/react-native-customui`

### ISSUE THREAD

**Issue by CHANDRAMOHANnegi** [razorpay/react-native-razorpay#335]
https://www.npmjs.com/package/react-native-customui

Version ---> 2.1.8
react native ---> .62.2

podspec file is not found in customui for any version ,

**Comment by CHANDRAMOHANnegi** [comment]
https://razorpay.com/docs/payment-gateway/react-native-integration/custom/

**Comment by Nautiyalsachin** [comment]
Closing this issue due to lack of information, please create a new issue with asked details.
