### ISSUE TITLE
Direct local .aar file dependencies are not supported when building an AAR.

### ISSUE THREAD

**Issue by CHANDRAMOHANnegi** [razorpay/react-native-razorpay#341]
> Task :react-native-customui:bundleReleaseAar FAILED

FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':react-native-customui:bundleReleaseAar'.
> Direct local .aar file dependencies are not supported when building an AAR. The resulting AAR would be broken because the classes and Android resources from any local .aar file dependencies would not be packaged in the resulting AAR. Previous versions of the Android Gradle Plugin produce broken AARs in this case too (despite not throwing this error). The following direct local .aar file dependencies of the :react-native-customui project caused this error: /Users/username/myapp/node_modules/react-native-customui/android/libs/razorpay-android-3.9.2.aar

    "react-native-customui": "^2.1.8"
    "react-native": "0.62.2"
        
     classpath('com.android.tools.build:gradle:4.0.1')
     distributionUrl=https\://services.gradle.org/distributions/gradle-6.5-all.zip

**Comment by vivekshindhe** [comment]
@CHANDRAMOHANnegi need more information on what you are trying to do here.

**Comment by CHANDRAMOHANnegi** [comment]
ran this command in android studio , trying to make apk 

./gradlew assembleRelease -x bundleReleaseJsAndAssets

**Comment by vivekshindhe** [comment]
@CHANDRAMOHANnegi Hey, so we did push our razorpay-android-customui .aar file to maven. It is reflected in the latest release. Closing the ticket. Thank you for pointing this out to us.
