### ISSUE TITLE
RazorPay Sample Project "Release" build fails - Xcode 12.5, RN:0.63.4, RP:2.2.7 (pod - 1.1.13)

### ISSUE THREAD

**Issue by zenjedi** [razorpay/react-native-razorpay#342]
We've been at it trying to migrate our project code base from Xcode 11 (where React Native Razorpay 2.2.1 works perfectly) to Xcode 12.5. The only failure is react-native-razorpay and that too only in the Release build. The errors are the same as the long discussed issues around 
`Unknown type name 'RazorpayCheckout'; did you mean 'RNRazorpayCheckout'?`

Even the razorpay sample project here fails to work! 

Machine: MacbookPro 2018 Intel processor
react-native: 0.63.4
react-native-razorpay: 2.2.7 (pod - 1.1.13)
razorpay-pod: 1.1.13
Xcode: 12.5

Our entire app team has gone through all issues and of course, all your documentation too. Need your urgent intervention as a loyal Razorpay customer (we don't have any alternate payment gateway in our app).

**Comment by zenjedi** [comment]
@Nautiyalsachin and team at Razorpay, please respond. Razorpay is the only pod which is not going through for our Xcode 12 ios 14 build. Your help will be much appreciated.

**Comment by Ansonmathew** [comment]
@zenjedi 
```
    post_install do |installer|
        installer.pods_project.build_configurations.each do |config|
            config.build_settings["EXCLUDED_ARCHS[sdk=iphonesimulator*]"] = "arm64"
        end
    end
```

Add the above in your Podfile.

**Comment by zenjedi** [comment]
@Ansonmathew , this seems to have worked. The build is currently on TestFlight undergoing testing. Will reach you if there are concerns, which might be unlikely. Thank you for your help and response. Cheers!

**Comment by vivekshindhe** [comment]
Closing the ticket due to inactivity. Please feel free to reopen, comment or create another issue for further assistance
