### ISSUE TITLE
Unknown type name 'RazorpayCheckout'; did you mean 'RNRazorpayCheckout'?

### ISSUE THREAD

**Issue by sourav-singh-rawat** [razorpay/react-native-razorpay#343]
<img width="1440" alt="Screenshot 2021-06-17 at 12 49 14 AM" src="https://user-images.githubusercontent.com/45400448/122279654-ed6c0e80-cf05-11eb-8643-dd18a58731cf.png">

### What happened:
When building the app through Xcode it is throwing error :
Unknown type name 'RazorpayCheckout'; did you mean 'RNRazorpayCheckout'?

### Steps To Reproduce:
Install the package
arch -x86_64 pod install
Build the app

**Working fine for the android build.
I am using M1**

**Comment by deepakverma4** [comment]
i'm also facing same issue

**Comment by vivekshindhe** [comment]
@sourav-singh-rawat , @deepakverma4 was right, here's a snippet of what's changed for M1 Xcode v12, 

> Xcode 11 used to automatically translate building for arm64 for the simulator into building for x86_64, but now that arm64 is a valid simulator architecture (it’s the Apple Silicon architecture), that translation no longer occurs.
So now whenever you try to build this test project under selected iOS 14 simulator, it will return you with the mentioned errors as the link target type will be an unknown type ‘arm64-apple-ios11.0-simulator’ which cause the build failed.

Here's the link to the reference site, [here](https://khushwanttanwar.medium.com/xcode-12-compilation-errors-while-running-with-ios-14-simulators-5731c91326e9)

Please try this and let us know if you are still facing the issue.

**Comment by vivekshindhe** [comment]
@sourav-singh-rawat Closing the issue due to inactivity. Please feel free to comment here to reopen. Thank you.

**Comment by devanshsadhotra25** [comment]
@sourav-singh-rawat  , can u please reopen it , or help me out , how did u resolve this?

**Comment by srinigk** [comment]
I have the same issue.
Environment:
MacBook Pro (14-inch, 2021)
Chip: Mac M1 Pro

System:
    OS: macOS 12.1
    CPU: (8) arm64 Apple M1 Pro
    Memory: 100.83 MB / 16.00 GB
    Shell: 5.8 - /bin/zsh
  Binaries:
    Node: 16.13.0 - /usr/local/bin/node
    Yarn: 1.22.17 - /opt/homebrew/bin/yarn
    npm: 8.1.0 - /opt/homebrew/bin/npm
    Watchman: 2021.11.15.00 - /opt/homebrew/bin/watchman
  Managers:
    CocoaPods: 1.11.2 - /opt/homebrew/bin/pod
  SDKs:
    iOS SDK:
      Platforms: DriverKit 21.2, iOS 15.2, macOS 12.1, tvOS 15.2, watchOS 8.3
    Android SDK: Not Found
  IDEs:
    Android Studio: 2020.3 AI-203.7717.56.2031.7784292
    Xcode: 13.2.1/13C100 - /usr/bin/xcodebuild
  Languages:
    Java: 11.0.10 - /usr/bin/javac
  npmPackages:
    @react-native-community/cli: Not Found
    react: 17.0.2 => 17.0.2 
    react-native: 0.66.4 => 0.66.4 
    react-native-macos: Not Found

I get the same error as shown below. 
I uninstalled, reinstsalled the react-native-razorpay package, 
De-integrated and updated pod
Cleaned the derived-data folder
Cleaned the build and tried rebuilding.

Still I get the same error
![Screenshot 2022-01-15 at 6 24 20 PM](https://user-images.githubusercontent.com/16533496/149622402-89877363-c9fc-423c-9a86-4567178681ce.png)
.
