### ISSUE TITLE
Razorpay checkout is not opening on IOS

### ISSUE THREAD

**Issue by akshaykatale99** [razorpay/react-native-razorpay#347]
Razorpay checkout is not opening on ios. throwing the following error when calling RazorpayCheckout.open.

![Screenshot 2021-07-16 at 3 38 14 PM](https://user-images.githubusercontent.com/12472207/125931702-56930ae7-7f3e-4d09-ae67-76f811368686.png)

![Screenshot 2021-07-16 at 3 41 37 PM](https://user-images.githubusercontent.com/12472207/125932240-b9e5a45a-89a9-45c4-9817-1929e5c69e1f.png)

React Native - ~0.63.3
react-native-razorpay - ^2.2.7
Xcode - 12.4

**Comment by ramprasadAnand** [comment]
@akshaykatale99 Can you share the sample payload you are passing to open checkout ?

**Comment by akshaykatale99** [comment]
Hi @ramprasadAnand , we are using this payload.

var options = {
            description: "Online Shopping",
            currency: "INR",
            key: "rzp_test_RziHitfzp10iKh",
            order_id: "order id recieved from razorpay",
            prefill: {
                email: checkoutData.customer.billing.email,
                contact: checkoutData.customer.billing.phone,
                name: `${checkoutData.customer?.billing.firstName} ${checkoutData.customer.billing.lastName}`
            },
            amount: "10000",
            name: "Brand Name",
            image: 'https://paxon.tech/wp-content/uploads/2021/06/Paxon-3-1.png',
            theme: {color: theme.COLOR_PRIMARY}
          }

**Comment by ramprasadAnand** [comment]
@akshaykatale99 Are you generating the order_id from your backend ?. And If you are showing a loader while calling the order_id API from the backed, can you try disabling the loader and try to open checkout ?

**Comment by akshaykatale99** [comment]
@ramprasadAnand Yes. we are generating order id from backend and showing loader while api call. when i disable loader as per your suggestion its opening now.
