### ISSUE TITLE
App Crashes on RazorpayCheckout.open API

### ISSUE THREAD

**Issue by ameenfarook** [razorpay/react-native-razorpay#393]
## Description
Android app is crashing when i invoke RazorpayCheckout.open API.

* **Specific to iOS Users :-**
- [x] I have tried updating Razorpay pod to the latest version by using 'pod update'.

## Razorpay Package Version :
**Razorpay 2.2.8 ("react-native-razorpay": "^2.2.8",)**
 
## Java and Gradle Version (android) :
**Gradle 6.9 (distributionUrl=https\://services.gradle.org/distributions/gradle-6.9-all.zip)**
**Java 15 (java version "15.0.1" 2020-10-20)**

### What you did:

I was invoking RazorpayCheckout.open API with key, name and order_id and then it crashes.

### What happened:

It is only happening to android, in ios it works fine. I cant even catch the error using basic try catch. But i got the stack trace from crashlytics which is attached below .

![Screenshot 2022-02-14 231620](https://user-images.githubusercontent.com/38003780/153920127-0be95b0d-48e8-4f06-8bc0-dadc284cbad1.png)

## Code example, screenshot, or link to a repository:
Please provide a link to a repository on GitHub, or provide a minimal code example that reproduces the problem.
You may provide a screenshot of the application if you think it is relevant to your bug report.
Here are some tips for providing a minimal example: https://stackoverflow.com/help/mcve

**Comment by vivekshindhe** [comment]
Okay, I was able to reproduce the issue. It is happening because of the color value that is passed in the options payload. 
Here is the payload that I was using when I was able to reproduce the issue, 

`var options = {
                  description: 'Credits towards consultation',
                  image: 'https://i.imgur.com/3g7nmJC.png',
                  currency: 'INR',
                  key: 'rzp_test_1DP5mmOlF5G5ag', // Your api key
                  amount: '5000',
                  name: 'foo',
                  prefill: {
                    email: 'void@razorpay.com',
                    contact: '9191919191',
                    name: 'Razorpay Software',
                  },
                  theme: {color: '#000'},
                };`

If you see the color it is considered as the right value, but android doesn't parse it. But will parse something like this 

`#000000`. Please re-check this option and let us know if that resolves the problem for you. Thank you

**Comment by ameenfarook8** [comment]
But i thought theme and color is an optional parameter. Are you saying i must provide theme and color?

**Comment by ameenfarook8** [comment]
I actually implemented this a month ago, it was working fine till today. All of a sudden this color issue?

**Comment by vivekshindhe** [comment]
I was trying to reproduce the issue and was able to do it with this one parameter change. Could you please send us the payload you are sending so that its easy for me to reproduce it? That would be very helpful

**Comment by ameenfarook8** [comment]
I am only passing three parameters

key
name
order_id

**Comment by vivekshindhe** [comment]
vivek.shindhe@razorpay.com this is my email. Could you please send the key you are trying this with? Even the test key works. I'll try to reproduce it on my end with the key. Also please add an order_id a sample one. This information would be instrumental in reproducing the issue. Also, did this happen on release or debug version? And you couldn't see the logs in android studio? Another thing, did you upgrade the react-native-razorpay version recently?

**Comment by bijeesraj007** [comment]
@vivekshindhe  - I have shared the requested information via email.

**Comment by sahukanishka** [comment]
Razorpay sdk crashes when we call  RazorpayCheckout.open(options) method and pass the options
Sometimes the method works fine and easily opens the razorpay window.

But other times, it does not open and the app immediately crashes. Also, There is no crash logs found in the console.

**Comment by ameenfarook8** [comment]
> Razorpay sdk crashes when we call RazorpayCheckout.open(options) method and pass the options Sometimes the method works fine and easily opens the razorpay window.
> 
> But other times, it does not open and the app immediately crashes. Also, There is no crash logs found in the console.

Make sure to pass theme and color parameter to RazorpayCheckout.open API. This prevents my app to crash.

**Comment by sahukanishka** [comment]
One more point if your app still crashes.
You have to pass both image and theme.
RazorpayCheckout.open({
      key: <public-key>,
      name: <name>,
      order_id: <order-id>,
      theme: {
        color: <some-color>,
      }
      image: 'https://i.imgur.com/3g7nmJC.png'
    });

**Comment by rahulnikam2002** [comment]
Did anyone found the solution!

**Comment by vivekshindhe** [comment]
@rahulnikam2002 Can you share any logs related to the crash? Is it happening on android or iOS?  It would be helpful for us to try to get to the bottom of the issue. I wasn't able to reproduce this.

**Comment by rahulnikam2002** [comment]
> @rahulnikam2002 Can you share any logs related to the crash? Is it happening on android or iOS? It would be helpful for us to try to get to the bottom of the issue. I wasn't able to reproduce this.

Heyy!! it worked for me 😁

**Comment by SiDDhartharG** [comment]
Hi Guys
My problem was solved

I was not sending key  in payload which solve my problem and my app stopped crashing

`RazorpayCheckout.open({ key: <public-key>, name: <name>, order_id: <order-id>, theme: { color: <some-color>, } image: 'https://i.imgur.com/3g7nmJC.png' }); `
