### ISSUE TITLE
Can not link customui sdk in ios

### ISSUE THREAD

**Issue by avinashRathod02** [razorpay/react-native-razorpay#397]
## Description
Can not link customui sdk in ios
no Razorpay.framework while Link SDK(automatic).
note : working fine in android

* **I have tried updating Razorpay pod to the latest version by using 'pod update**

### I was following the step given instruction below
https://razorpay.com/docs/payments/payment-gateway/react-native-integration/custom/build-integration/#automatic

### Then Razorpay.framework not found :
![Screenshot 2022-03-14 at 3 46 59 PM](https://user-images.githubusercontent.com/68007690/158312229-f859df2a-93b0-42fe-92cc-d618160f2b30.png)

## You can check code in this repo :
https://github.com/avinashRathod02/razorpay-customui

## Razorpay Package Version :
`"react-native-customui": "^2.1.9",`

## Other informations :

 

> System:
>     OS: macOS 11.4
>     CPU: (4) x64 Intel(R) Core(TM) i3-8100B CPU @ 3.60GHz
>     Memory: 97.25 MB / 8.00 GB
>     Shell: 5.8 - /bin/zsh
>   Binaries:
>     Node: 14.17.4 - /usr/local/opt/node@14/bin/node
>     Yarn: 1.22.17 - /usr/local/bin/yarn
>     npm: 6.14.14 - /usr/local/opt/node@14/bin/npm
>     Watchman: 2021.11.15.00 - /usr/local/bin/watchman
>   Managers:
>     CocoaPods: 1.11.2 - /usr/local/bin/pod
>   SDKs:
>     iOS SDK:
>       Platforms: iOS 14.5, DriverKit 20.4, macOS 11.3, tvOS 14.5, watchOS 7.4
>     Android SDK:
>       API Levels: 25, 29, 30, 31
>       Build Tools: 28.0.3, 29.0.2, 30.0.2, 31.0.0
>       System Images: android-30 | Google APIs Intel x86 Atom
>       Android NDK: Not Found
>   IDEs:
>     Android Studio: 2020.3 AI-203.7717.56.2031.7583922
>     Xcode: 12.5.1/12E507 - /usr/bin/xcodebuild
>   Languages:
>     Java: 1.8.0_292 - /usr/bin/javac
>   npmPackages:
>     @react-native-community/cli: Not Found
>     react: 17.0.2 => 17.0.2
>     react-native: 0.67.3 => 0.67.3
>     react-native-macos: Not Found
>   npmGlobalPackages:
>     *react-native*: Not Found
>

**Comment by komelabbbas** [comment]
same. issue occurs.

**Comment by kartikMygoldkart** [comment]
did it get resolved?

**Comment by vivekshindhe** [comment]
Hey folks. We have resolved this. And put customui to a pod as well. Please update to the latest version and check. Closing this ticket. Please comment here or open another ticket if you have any queries. Thank you for your patience.
