### ISSUE TITLE
FRAMEWORK not required

### ISSUE THREAD

**Issue by CHANDRAMOHANnegi** [razorpay/react-native-razorpay#401]
`{
	"error": {
		"code": "BAD_REQUEST_ERROR",
		"description": "FRAMEWORK is\/are not required and should not be sent",
		"source": "provider",
		"step": "payment_authorization",
		"reason": "extra_field_sent",
		"metadata": {}
	},
	"http_status_code": 400
}`

    "react-native-customui": "^2.2.0",
    "react-native": "0.67.4",
    "react": "17.0.2",

**Comment by vivekshindhe** [comment]
@CHANDRAMOHANnegi can you specify the version of react-native-razorpay you are using?

**Comment by CHANDRAMOHANnegi** [comment]
> @CHANDRAMOHANnegi can you specify the version of react-native-razorpay you are using?

"react-native-customui": "^2.2.0",
"react-native": "0.67.4",
"react": "17.0.2",

**Comment by vivekshindhe** [comment]
which payment method is this happening for? @CHANDRAMOHANnegi

**Comment by CHANDRAMOHANnegi** [comment]
[](url
<img width="1440" alt="Screenshot 2022-04-13 at 1 47 39 PM" src="https://user-images.githubusercontent.com/32297380/163132023-26f58549-e51e-4788-8c71-faf3951aadc0.png">
)

> which payment method is this happening for? @CHANDRAMOHANnegi

UPI

**Comment by CHANDRAMOHANnegi** [comment]
> which payment method is this happening for? @CHANDRAMOHANnegi

All payment methods

**Comment by vivekshindhe** [comment]
@CHANDRAMOHANnegi you can use that for now. We'll make a fix for this by tomorrow. It'd be great if you can wait till tomorrow though. Will update here when done.

**Comment by CHANDRAMOHANnegi** [comment]
> @CHANDRAMOHANnegi you can use that for now. We'll make a fix for this by tomorrow. It'd be great if you can wait till tomorrow though. Will update here when done.

This issue is with other versions also , changes are not backward compatible.
existing users are getting affected heavily.

**Comment by vivekshindhe** [comment]
This was released with 2.2.0. It should not affect existing users.

**Comment by CHANDRAMOHANnegi** [comment]
it is affecting other version also

v2.1.8 ,v2.1.9

**Comment by vivekshindhe** [comment]
was it released with the caret symbol? ^2.1.9? I'm guessing it picked 2.2.0 when it was built. We've identified the issue. Will update this by EOD today.

**Comment by CHANDRAMOHANnegi** [comment]
> was it released with the caret symbol? ^2.1.9? I'm guessing it picked 2.2.0 when it was built. We've identified the issue. Will update this by EOD today.

yes

**Comment by vivekshindhe** [comment]
@CHANDRAMOHANnegi please use version 2.2.1. This has been resolved.

**Comment by shubhambuccha** [comment]
Can't we handle this on the API end? Else will have to make a new release to the playstore. 

Please look into it.

**Comment by vivekshindhe** [comment]
@shubhambuccha Will look into it. But it doesn't seem feasible at the moment. Will update here if i find anything
