### ISSUE TITLE
RazorPay screen blank in apk release[ works fine in debug mode]

### ISSUE THREAD

**Issue by rakeshuce1990** [razorpay/react-native-razorpay#411]
## Description
I am using react-native-razorpay version 2.2.9. When I am opening the RazorPay interface, it shows a blank white screen. 

## Razorpay Package Version :
react-native-razorpay: 2.2.9. 

## Java and Gradle Version (android) :
Gradle - 6.7
OpenJDK 11

### What you did:

Built android apk and tried opening RazorPay interface to initiate transaction

### What happened:

RazorPay went blank with complete white screen

## Steps To Reproduce
Provide a detailed list of steps that reproduce the issue.

1. Generate signed android bundle
2. Open RazorPay sdk using RazorpayCheckout.open() method

## Code example, screenshot, or link to a repository:
`const options = {
            amount: payload.amount.toString(),
            currency: 'INR',
            image: 'https://i.imgur.com/3g7nmJC.png',
            key: razorpayKey,
            order_id: payload.id,
            prefill: { contact: phone, email, name },
            theme: { color: colors.theme }
}
RazorpayCheckout.open(options)`

**Comment by vinutatibil** [comment]
Hi,

Is this issue got resolved.I'm also facing the same issue. We have used capacitor SDK integration . It works fine in debug mode. When it goes to release mode it is showing blank white screen with back button. Any help/input to resolve this issue

**Comment by vivekshindhe** [comment]
Hey @vinutatibil Please ensure that you've added the proguard rules required for android in the proguard-config. You can find them [here](https://razorpay.com/docs/payments/payment-gateway/android-integration/standard/build-integration#proguard-rules)

**Comment by vivekshindhe** [comment]
@vinutatibil Please create a ticket on the Razorpay Dashboard. This allows us to help you more closely and close the ticket fairly quickly than over Github. 
Thanks
