### ISSUE TITLE
Choose  Razorpay, select UPI App(GPay), once (GPay) open and close it and do not make the payment, but it returns razorpay_payment_id. When checking in the Razorpay dashboard the amount gets added. How is it possible.??

### ISSUE THREAD

**Issue by joseprakash1990** [razorpay/react-native-razorpay#415]
Amount added in Razorpay when opening and closing the UPI apps. Choose up pay in Razorpay, select UPI App(GPay), once (GPay) open and close it and do not make the payment, but it returns razorpay_payment_id. When checking in the Razorpay dashboard the amount gets added. How is it possible.??

System:
    OS: Windows 10 10.0.19044
    CPU: (8) x64 Intel(R) Core(TM) i7-2600 CPU @ 3.40GHz
    Memory: 1.34 GB / 7.88 GB
  Binaries:
    Node: 16.14.2 - C:\Program Files\nodejs\node.EXE
    Yarn: 1.22.19 - ~\AppData\Roaming\npm\yarn.CMD
    npm: 8.5.0 - C:\Program Files\nodejs\npm.CMD
    Watchman: Not Found
  SDKs:
    Android SDK: Not Found
    Windows SDK:
      AllowDevelopmentWithoutDevLicense: Disabled
      AllowAllTrustedApps: Disabled
  IDEs:
    Android Studio: Version     2021.1.0.0 AI-211.7628.21.2111.8309675
    Visual Studio: Not Found
  Languages:
    Java: 11.0.14 - /c/Program Files/Common Files/Oracle/Java/javapath/javac
  npmPackages:
    @react-native-community/cli: Not Found
    react: 17.0.2 => 17.0.2
    react-native: 0.68.2 => 0.68.2
    react-native-windows: Not Found
  npmGlobalPackages:
    *react-native*: Not Found

**Comment by vivekshindhe** [comment]
@joseprakash1990 can you please send the payload you are using? Also, please confirm if you are using test key or live keys.

**Comment by joseprakash1990** [comment]
@vivekshindhe I'm using the test key.

**Comment by vivekshindhe** [comment]
UPI intent doesn't work on test keys. @joseprakash1990

**Comment by joseprakash1990** [comment]
@vivekshindhe Thank you so much.
