### ISSUE TITLE
With the new RBI guidelines, how does tokenization work?

### ISSUE THREAD

**Issue by KamyabWebelight** [razorpay/react-native-razorpay#418]
To be used as a reference 
https://razorpay.com/card-tokenisation/

Additionally, I have followed the below link for adding tokenization to my project, but I am getting an error message.

Link: [https://levelup.gitconnected.com/card-tokenisation-with-razorpay-cfa7d5f315d0](https://levelup.gitconnected.com/card-tokenisation-with-razorpay-cfa7d5f315d0)
Error: **“BAD_REQUEST_ERROR - The id provided does not exist”**
Also tested with live key

**Comment by vivekshindhe** [comment]
@KamyabWebelight please raise a ticket in the Help & Support in your Razorpay Dashboard. They'll be able to help you out regarding this issue faster.
