### ISSUE TITLE
 Duplicate class com.razorpay.Y_$B$ found in modules jetified-checkout-1.6.26-runtime (com.razorpay:checkout:1.6.26) and jetified-customui-3.9.9-runtime (com.razorpay:customui:3.9.9)

### ISSUE THREAD

**Issue by prajeesh-splendre** [razorpay/react-native-razorpay#427]
I was using react-native-customui for the past few months for UPI intent flow, now i need to integrate react-native-razorpay for multiple payment methods, when i installed  react-native-razorpay and run using npx react-native run-android in went into these stacktrace

<img width="1438" alt="image" src="https://user-images.githubusercontent.com/86819567/200986025-ece2ccc2-a52b-47b4-b585-82cfb7120596.png">

**Comment by prajeesh-splendre** [comment]
Is there any workaround ?

**Comment by vivekshindhe** [comment]
@prajeesh-splendre no sir.

**Comment by iamromec** [comment]
@vivekshindhe if we use this, could you please explain how can we get all available (active) payment methods? Is there any API available for that? 

I looked into it but didn't see it. So how does this plugin works?

**Comment by iamromec** [comment]
I'm thinking of switching to react-native-customui as react-native-razorpay doesn't work properly with test keys and development.

**Comment by iamromec** [comment]
I think this one, right: https://razorpay.com/docs/payments/third-party-validation/s2s-integration/methods-api/#next-steps

**Comment by vivekshindhe** [comment]
@iamromec We still aren't able to reproduce the error you're seeing on test keys. But let me assure you, it works correctly with both test and live keys for us. Regardless, if you want to switch to customui, please contact Razorpay's Help Desk and they should be able to help take this forward. 
Closing this ticket for now.
