### ISSUE TITLE
RazorpayCheckout.open() is Crashing the Android Application

### ISSUE THREAD

**Issue by rupam999** [razorpay/react-native-razorpay#430]
When I try to make a payment my android application is crashing on RazorpayCheckout.open(options). I'm using MacBook M1. On IOS it is working fine.

What is the issue? Do I need to do any other steps after npm I react-native-razorpay

Version: react-native-razorpay: 2.3.0

```
RazorpayCheckout.open(options)
                .then(async (data: any) => {
                  // handle success
                  console.log(`Success: ${data.razorpay_payment_id}`);
                })
                .catch((err: any) => {
                  // handle failure
                  Alert.alert('Error', 'Something went wrong!', [
                    {text: 'OK', onPress: () => null},
                  ]);
                  console.log(`Error: ${err.code} | ${err.description}`);
                  setLoading(false);
                });
```

**Comment by VJNoCode** [comment]
Our development team is also facing the same issue - Has this issue been resolved?

**Comment by rupam999** [comment]
No, the issue is still there

**Comment by vivekshindhe** [comment]
@VJNoCode @rupam999 Is it happening on android? Have you folks added the proguard rules if so?

**Comment by VJNoCode** [comment]
@vivekshindhe - Our development team have added the proguard rules and the issue is still happening on only Android. any help to resolve this will be greatly appreciated. thank you.

**Comment by vivekshindhe** [comment]
@VJNoCode Can you share any error log that you're seeing in android logs?

**Comment by KrushnaNaghate** [comment]
this. the issue is with the latest version of the package, this issue was earlier in the 2019 version of package, I just downgraded the package version, for now, npm i react-native-razorpay@2.2.8

**Comment by rifad4u** [comment]
It might be due some additional parameters passing to checkout API , comment the parameters and check again by uncommenting the parameters one by one.
