### ISSUE TITLE
Intent redirection vulnerability for com.razorpay.x2.onReceive

### ISSUE THREAD

**Issue by shahidtumbi** [razorpay/react-native-razorpay#438]
## Description
Please provide a clear and concise description of what the bug is. Include screenshots if needed.
Please test using the latest React Native Razorpay plugin release to make sure your issue has not already been fixed. 

* **Specific to iOS Users :-**
- [ ] I have tried updating Razorpay pod to the latest version by using 'pod update'.

## Razorpay Package Version :
Open `Package.json`. > Copy `react-native-razorpay` version here. 

## Xcode Version (iOS) :
Open Xcode > Go to `About Xcode` > copy the Xcode version here.

## Razorpay-pod version (iOS) :
Go to your project path > Go to folder named `ios`  > open 'podfile.lock' file > search for 'razorpay-pod' > copy the line here 

## Java and Gradle Version (android) :
Specify your Java and Gradle version.

## Steps To Reproduce
Provide a detailed list of steps that reproduce the issue.

1. update the package to 2.3.0 
2. run the build.
3. submit the build to play store. You will recieve the mail as attached 

## Code example, screenshot, or link to a repository:
Please provide a link to a repository on GitHub, or provide a minimal code example that reproduces the problem.
You may provide a screenshot of the application if you think it is relevant to your bug report.
Here are some tips for providing a minimal example: https://stackoverflow.com/help/mcve

![Screenshot 2023-01-28 at 7 10 38 PM](https://user-images.githubusercontent.com/36243783/215269603-3805d62e-d4ad-49e1-b28d-88585334ab86.png)

**Comment by rajeshde** [comment]
I have also faced the same issue today. Using razorpay version 2.3.0

**Comment by vivekshindhe** [comment]
Hey folks, we are currently looking into this. The fix will be made live by Monday morning. Will update here once done. Thank you for your patience.

**Comment by rajeshde** [comment]
Thanks @vivekshindhe

**Comment by shahidtumbi** [comment]
Thanks @vivekshindhe

**Comment by iamromec** [comment]
+1 (also this issue has affected the razorpay-capacitor).

**Comment by Nirav444Educase** [comment]
> ## Description
> Please provide a clear and concise description of what the bug is. Include screenshots if needed. Please test using the latest React Native Razorpay plugin release to make sure your issue has not already been fixed.
> 
> * **Specific to iOS Users :-**
> 
> * [ ]  I have tried updating Razorpay pod to the latest version by using 'pod update'.
> 
> ## Razorpay Package Version :
> Open `Package.json`. > Copy `react-native-razorpay` version here.
> 
> ## Xcode Version (iOS) :
> Open Xcode > Go to `About Xcode` > copy the Xcode version here.
> 
> ## Razorpay-pod version (iOS) :
> Go to your project path > Go to folder named `ios` > open 'podfile.lock' file > search for 'razorpay-pod' > copy the line here
> 
> ## Java and Gradle Version (android) :
> Specify your Java and Gradle version.
> 
> ### What you did:
> ### What happened:
> ## Steps To Reproduce
> Provide a detailed list of steps that reproduce the issue.
> 
> 1. update the package to 2.3.0
> 2. run the build.
> 3. submit the build to play store. You will recieve the mail as attached
> 
> ### Suggested solution:
> ## Code example, screenshot, or link to a repository:
> Please provide a link to a repository on GitHub, or provide a minimal code example that reproduces the problem. You may provide a screenshot of the application if you think it is relevant to your bug report. Here are some tips for providing a minimal example: https://stackoverflow.com/help/mcve
> 
> ![Screenshot 2023-01-28 at 7 10 38 PM](https://user-images.githubusercontent.com/36243783/215269603-3805d62e-d4ad-49e1-b28d-88585334ab86.png)

same issue

**Comment by Nirav444Educase** [comment]
I have also same issue
![Screenshot 2023-01-30 at 9 33 01 AM](https://user-images.githubusercontent.com/110712295/215385071-f69c72f6-9657-45b2-88bf-daf5555514bc.png)

**Comment by vivekshindhe** [comment]
Hey folks, apologies for the delay on this. A new version has been pushed to maven for android SDK. Please ensure the older version isn't cached and reinstall again. When uploading to play store please ensure that the version which was throwing this error from google is out of the track so this issue doesn't crop up again. Thank you for your support.

**Comment by rajeshde** [comment]
@vivekshindhe Can you please share the steps to use the updated version correctly?

**Comment by vivekshindhe** [comment]
@rajeshde The package is set to receive the latest version whenever available. Reinstalling the package should do the trick.

**Comment by nb-immosnapp** [comment]
> @rajeshde The package is set to receive the latest version whenever available. Reinstalling the package should do the trick.

Still same issue even if i deleted node_modules. all lock file and also reinstall whole package and uploaded new .aab file

**Comment by nb-immosnapp** [comment]
Hello @vivekshindhe any update?

**Comment by nirav-infostretch** [comment]
hi @vivekshindhe,

We are using 
react-native-razorpay : 2.2.9
react-native : 0.64.4
com.razorpay:checkout : 1.6.28

We have uploaded new bundle. But still it rejected by play store. Can you please help us ?

**Comment by malikzype** [comment]
Reinstalling doesn't solve the issue. @vivekshindhe Can you please help us update the package?

**Comment by Nirav1432** [comment]
@vivekshindhe i also got the same issue. and google is giving warning to remove app from playstore
![image](https://user-images.githubusercontent.com/52786520/215761860-f9754ea6-3d1e-4157-8951-428d395449d5.png)

i tried all ways. upgrading and reinstall react-native-razorpday. nothing is working. 
Please help!

**Comment by vivekshindhe** [comment]
Hey guys, apologies for the delay. Had to combine two of the remedies together for it to work. Please reinstall the razorpay package and try uploading. I'm gonna attach a screenshot of the working sample as well. 
![Screenshot 2023-01-31 at 7 05 03 PM](https://user-images.githubusercontent.com/57621906/215774910-d44f9672-46e7-4285-9126-d9226b2e193a.png)

**Comment by Nirav1432** [comment]
> 
okay let me check

**Comment by iamromec** [comment]
The npm package is showing "3 months ago"...the latest version on NPM is "2.3.0 • Public • Published 3 months ago"

Is there any direct GitHub URL we can use to install it?

**Comment by iamromec** [comment]
FYI: https://www.npmjs.com/package/react-native-razorpay

**Comment by vivekshindhe** [comment]
@iamromec the package automatically picks up the latest Android SDK even if the package remains the same. So you don't have to worry about the package update as of right now.

**Comment by Nirav1432** [comment]
> @iamromec the package automatically picks up the latest Android SDK even if the package remains the same. So you don't have to worry about the package update as of right now.

Yes @vivekshindhe . Now working fine i did't get any mail now. Thanks a lot!

**Comment by mashish584** [comment]
@vivekshindhe  Also facing the same issue. Have upgraded the version from 2.2.9 to 2.3.0.

React Native : 0.64.4
React: 17.0.1

**Comment by vivekshindhe** [comment]
@mashish584 In the retained bundles, if you see a version that gets affected by this, that can also cause this error to pop up. Please ensure to remove it from the retained bundle list. I'd also suggest talking with google directly regarding this because this did not happen in the app I pushed.

**Comment by eshantbist** [comment]
> Hey guys, apologies for the delay. Had to combine two of the remedies together for it to work. Please reinstall the razorpay package and try uploading. I'm gonna attach a screenshot of the working sample as well.
> 
> That said, we apologize for this issue. We'll see why it happened and how we can ensure this doesn't happen again. ![Screenshot 2023-01-31 at 7 05 03 PM](https://user-images.githubusercontent.com/57621906/215774910-d44f9672-46e7-4285-9126-d9226b2e193a.png)

@vivekshindhe 
I am still facing the same issue, even though I reinstalled the package and uploaded again .

And how critical is this warning?

**Comment by vivekshindhe** [comment]
It's not critical. The test basically includes looking for a broadcast receiver and then ensuring that the activity that is triggering it is safe. Doesn't really apply to us, but we still have to follow the guideline.

**Comment by rajeshde** [comment]
Just an update

I have uninstalled and installed react-native-razorpay package -> Update my app version -> Clean -> Generate Signed aab
Now the updated version is approved by Google.

**Comment by vivekshindhe** [comment]
For the folks who are still facing the issue, please raise a support ticket on the Razorpay Dashboard. Our support team will help you sort out the issue the best we can.

Closing the ticket with this.
