### ISSUE TITLE
Vulnerability APK Version(s) Deadline to fix Intent Redirection  Your app(s) are vulnerable to Intent Redirection.

### ISSUE THREAD

**Issue by kishanpatelstrauss** [razorpay/react-native-razorpay#439]
## Description
Please provide a clear and concise description of what the bug is. Include screenshots if needed.
Please test using the latest React Native Razorpay plugin release to make sure your issue has not already been fixed. 

* **Specific to iOS Users :-**
- [ ] I have tried updating Razorpay pod to the latest version by using 'pod update'.

## Razorpay Package Version :
Open `Package.json`. > Copy `react-native-razorpay` version here. 

## Xcode Version (iOS) :
Open Xcode > Go to `About Xcode` > copy the Xcode version here.

## Razorpay-pod version (iOS) :
Go to your project path > Go to folder named `ios`  > open 'podfile.lock' file > search for 'razorpay-pod' > copy the line here 

## Java and Gradle Version (android) :
Specify your Java and Gradle version.

## Steps To Reproduce
Provide a detailed list of steps that reproduce the issue.

1.
2.

## Code example, screenshot, or link to a repository:
Please provide a link to a repository on GitHub, or provide a minimal code example that reproduces the problem.
You may provide a screenshot of the application if you think it is relevant to your bug report.
Here are some tips for providing a minimal example: https://stackoverflow.com/help/mcve

**Comment by vivekshindhe** [comment]
@kishanpatelstrauss Hey, thanks for reaching out regarding this. This is already being tracked in another issue, [here](https://github.com/razorpay/react-native-razorpay/issues/438). Please follow that thread for updates. A new version has been released as well. Closing this ticket.

**Comment by kishanpatelstrauss** [comment]
ok. i will reinstall react-native-razorpay and then after publish Android App Bundle on play store.

**Comment by vivekshindhe** [comment]
@kishanpatelstrauss do remember to remove the version which threw this error out of the track. Else it will throw the same error again.

**Comment by rajeshde** [comment]
@vivekshindhe I understand that this is out of the topic of this issue thread, but can you mention how to remove the previous version out of the track before submitting an updated version. I couldn't find any way to delete/remove the track.

**Comment by vivekshindhe** [comment]
@rajeshde Hey, looks like due the new changes that is not possible anymore. Tried looking at multiple things. In any case, try uploading the newer aab with the updated version.

**Comment by rajeshde** [comment]
@vivekshindhe I have actually updated with a new aab with an updated version, but I still got the error from Google.

**Comment by nb-immosnapp** [comment]
Any update here?? @vivekshindhe

**Comment by vivekshindhe** [comment]
@nb-immosnapp We have covered the vulnerability in the SDK and followed the steps from Google remedy page. Could you please reach out to their help desk and see what the issue is? We are looking from our end as well.

**Comment by nb-immosnapp** [comment]
> @nb-immosnapp We have covered the vulnerability in the SDK and followed the steps from Google remedy page. Could you please reach out to their help desk and see what the issue is? We are looking from our end as well.

okay let me check from their as well. i will ask for help
Thanks!

**Comment by nirav-infostretch** [comment]
hi @vivekshindhe,

We are using 
react-native-razorpay : 2.2.9
react-native : 0.64.4
com.razorpay:checkout : 1.6.28

We have uploaded new bundle. But still it rejected by play store. Can you please help us ?

**Comment by vivekshindhe** [comment]
@nirav-infostretch hey, the issue has been fixed. Please reinstall the razorpay package and upload to play store l

**Comment by kishanpatelstrauss** [comment]
Hi @vivekshindhe,

**react-native : 0.67.2
react-native-razorpay : 2.3.0**

Reinstall the razorpay package and upload to play store .aab file. my app is publish but i got this msg(**Vulnerability APK Version(s) Deadline to fix Intent Redirection. Your app(s) are vulnerable to Intent Redirection.**)

**Comment by vivekshindhe** [comment]
Hey @kishanpatelstrauss. Looks like the SDK version internally being used in android isn't updated yet. Can you please remove the package, run 
`cd android && ./gradlew build`
install the razorpay package again
update the version of aab
ensure you aren't making a release for older versions in Play store as well, and check? This is resolved issues for everybody
