### ISSUE TITLE
Latest iOS SDK has missing ExternalWalletSelectionProtocol.h

### ISSUE THREAD

**Issue by ProiOSDeveloper** [razorpay/react-native-razorpay#44]
As per your documentation when I replaced the existing framework in RazorpayCheckout.xcodeproj, it gives following error:
'Razorpay/ExternalWalletSelectionProtocol.h' file not found
I think the iOS SDK and react native project are not in sync. It would be great if you could provide link to last react-native-razorpay compatible framework.

**Comment by Mayur-Wadpalliwar** [comment]
Please refer this: https://docs.razorpay.com/v1/page/listing-external-wallets#listing-external-wallet-on-ios-sdk

**Comment by ProiOSDeveloper** [comment]
@Mayur-Wadpalliwar Thanks for sharing the reference. But I think you were not able to get the exact issue. The problem is entirely related to the latest iOS framework. I think that the 'ExternalWalletSelectionProtocol' has been deprecated from iOS framework which required some sort of changes on react-native-razorpay module as well. And this updation has not yet been made. Anyways I was able to fix the issue by following the `additional steps` section using the razorpay framework contained in `node_modules` instead of downloading latest one.

**Comment by singhnitin88** [comment]
@ProiOSDeveloper You are absolutely spot on. We have migrated our SDK to Swift and the react wrapper has changed a bit. We highly recommend that you use the latest SDK.

We will be pushing an update to the react-native wrapper for our SDK (react-native-razorpay) soon. In the mean time you can use the latest SDK by replacing the following file in your local node_modules.

Replace the content of 
`node_modules/react-native-razorpay/ios/RazorpayCheckout.m `

with the content available here:
`https://github.com/razorpay/react-native-razorpay/blob/swift_wrapper/ios/RazorpayCheckout.m`

Do let us know if you face any issues there.

**Comment by chaitu87** [comment]
@ProiOSDeveloper I've used the '.framework' from node_modules but the build failed with `
framework not found Razorpay`. How did you manage to fix?

@singhnitin88 Replacing the content didn't help either. I might be missing some step, could you detail out the steps to fix this issue. Thanks.

**Comment by singhnitin88** [comment]
@chaitu87 Please ensure that you are following the steps listed here carefully:
https://github.com/razorpay/react-native-razorpay#additional-steps-for-linking-ios-sdk

**Comment by ProiOSDeveloper** [comment]
@chaitu87 You will have to set the framework search path build setting to '../node_modules/react-native-razorpay/ios'

**Comment by Mayur-Wadpalliwar** [comment]
Fixed with the update
