### ISSUE TITLE
Unable to build react native customUi after xcode update to 14.3

### ISSUE THREAD

**Issue by rifad4u** [razorpay/react-native-razorpay#448]
## Description

Getting "Unsupported Swift architecture" and "Could not build module Razorpay" error messages after xcode update to 14.3.

* **Specific to iOS Users :-**
- [ ] I have tried updating Razorpay pod to the latest version by using 'pod update'.

## Razorpay Package Version :
 "react-native-customui": "^2.2.3",

## Xcode Version (iOS) :
14.3

## Razorpay-pod version (iOS) :
2.0.3

## Java and Gradle Version (android) :
Specify your Java and Gradle version.

### What you did:

Updated macOS to 13.3 and xcode 14.3

### What happened:

Getting "Unsupported Swift architecture" and "Could not build module Razorpay" error messages.

## Steps To Reproduce
Provide a detailed list of steps that reproduce the issue.

1. Just build the project

## Code example, screenshot, or link to a repository:

<img width="1440" alt="Screenshot 2023-04-03 at 12 02 39 PM" src="https://user-images.githubusercontent.com/37132763/229430647-7c30ac41-ae6f-419c-a08c-fd9ae11ff32f.png">

<img width="1439" alt="Screenshot 2023-04-03 at 12 24 37 PM" src="https://user-images.githubusercontent.com/37132763/229433777-29eadb3d-b07f-46c0-88b7-1b084eaba412.png">

**Comment by GeVic** [comment]
@rifad4u were to able to resolve this? I'm facing the same issue.

**Comment by rifad4u** [comment]
> @rifad4u were to able to resolve this? I'm facing the same issue.

You can build your application if you change architecture to rosetta instead of apple silicon architecture.
Anyway react native razopay team to update the package inorder to support apple silicon architecture.

**Comment by chzappsinc** [comment]
for me its working, Installed cocapods vai `arch -x86_64 pod install`

**Comment by pratikdonda** [comment]
Getting same error after updating Xcode 15

Can anybody help me???

**Comment by pratikdonda** [comment]
@ramprasadAnand added but not working

**Comment by pratikdonda** [comment]
@ramprasadAnand added but not working

**Comment by rifad4u** [comment]
> @ramprasadAnand added but not working

Xcode --> Product -- > Destination --> Destination Architectures -- > Show Rosetta Destinations , Then do build and check.

**Comment by pratikdonda** [comment]
@ramprasadAnand Thanks for your quick replay, Appreciate..
