### ISSUE TITLE
UI breaks while focusing on TextInput

### ISSUE THREAD

**Issue by TheMarsGuy** [razorpay/react-native-razorpay#46]
react-native: 0.51.0
Android: 6.0.0, API 23

Using Genymotion Emulator. 

You can see the disturbance in the UI when focusing on the text input.
![screenshot](https://user-images.githubusercontent.com/10371003/34477591-3b01c220-efc1-11e7-9108-dcae6ba5d3c3.gif)

**Comment by pronav** [comment]
Does it happen only in genymotion or real device? Looks like emulator is not being able to provide gpu capability to webview in which checkout form is running.

**Comment by TheMarsGuy** [comment]
I just observed that it works fine on a real device. Thanks.
