### ISSUE TITLE
How to use Turbo UPI functionality with the current react native SDK?

### ISSUE THREAD

**Issue by numadashwa** [razorpay/react-native-razorpay#466]
### Describe the feature you'd like:
I would like to use the Turbo UPI feature. Is there any documentation to enable Turbo UPI using the SDK.

### Suggested implementation:
There should be a wiki or any documentation for enabling the Turbo UPI feature using this SDK.
> Reference: https://razorpay.com/docs/payments/payment-methods/upi/turbo-upi/

**Comment by vivekshindhe** [comment]
@numadashwa We do not support Turbo UPI on react-native currently. Hence there is no documentation regarding the same. Requesting you to raise it as a ticket on Razorpay Dashboard to get the timelines for the implementation. Thank you. Closing the ticket.
