### ISSUE TITLE
Error : This payment has failed due ti a issue with the merchant.

### ISSUE THREAD

**Issue by ajitborude** [razorpay/react-native-razorpay#467]
## Description
Whenever I am opening checkout page I am facing this error **This payment has failed due to an issue with the merchant. Do get in touch with site/app admin regarding this issue.**. I have attached the screenshot for reference.
Order is getting created successfully on the server and I can see it on the Razorpay dashboard as well, once I get order_id & pass it to RazorpayCheckout.open(), checkout page opens & shows the said error.
I am not getting error in console as well, after this when i click on Back, I get an error that payment has been cancelled by user.

## Razorpay Package Version :
Open `Package.json`. > 2.3.0 

## Java and Gradle Version (android) :
Specify your Java and Gradle version. Java 17.09 & gradle 7.5.1

### What happened:

Getting a message as **This payment has failed due to an issue with the merchant. Do get in touch with site/app admin regarding this issue.**

![Razorpay Error](https://github.com/razorpay/react-native-razorpay/assets/58566372/fa1f114a-93ac-4054-ab07-410105d14295)

## Steps To Reproduce
No special steps are required. Normal React Native Integration steps are followed

**Comment by vivekshindhe** [comment]
@ajitborude Can you please share your MID?

**Comment by ajitborude** [comment]
Sure @vivekshindhe . This is the Merchant Id FLyUlwNVrQEwza

**Comment by vivekshindhe** [comment]
@ajitborude, looks like your account is blocked, please raise a support request on the Razorpay Dashboard who will help sort this issue out for you.

**Comment by ajitborude** [comment]
I did not see any info about account being deactivated on the dashboard
Thank You @vivekshindhe. I'll check with Razorpay.
