### ISSUE TITLE
Turbo UPI not showing google pay

### ISSUE THREAD

**Issue by vikasatappinlay** [razorpay/react-native-razorpay#470]
## Description
```
<key>LSApplicationQueriesSchemes</key>
  	<array>
		<string>paytm</string>
		<string>phonepe</string>
		<string>paytmmp</string>
		<string>freecharge</string>
		<string>gpay</string>
		<string>lotza</string>
		<string>upi</string>
		<string>paypal</string>
		<string>whatsapp</string>
		<string>googlepay</string>
		<string>google_pay</string>
  	</array>
```

i think we are not getting LSApplicationQueriesSchemes string for gpay.
i have tried all possible string but still not getting

on call of 
`Razorpay.getAppsWhichSupportUPI()`
working fine with android 
expected : it should return gpay for payment as paytm,phone pay

issue : it returns phone pay and paytm **but not gpay**

**Comment by vivekshindhe** [comment]
@vikasatappinlay the scheme for google pay  is **tez** as mentioned [here](https://razorpay.com/docs/payments/payment-methods/upi/upi-intent/ios#ios-standard-checkout)

**Comment by vikasatappinlay** [comment]
thank you @vivekshindhe
