### ISSUE TITLE
how to save card details using  react-native-customui

### ISSUE THREAD

**Issue by zoxicorp** [razorpay/react-native-razorpay#471]
i cannot able to find any doc regarding how to save card details using react-native-customui we have tried the below code,.. 
this is a test code with test card details 

for this below code the payment is successfully done but the card details are not getting saved?

var options2 = {
            "description": "testing",
            "currency": "INR",
            "key_id": ${RAZORPAY_KEY_ID},
            "amount": "200020",
            "method": "card",
            email: 'void@razorpay.com',
            contact: '9999999123',
            card:{
                number:4111111111111111,
                name:'test name',
                expiry_month:11,
                expiry_year:34,
                cvv:118,
            },
            "order_id": "order_Ncd5pT4IPwuLNI",
            "customer_id": "cust_Na3LLYcqO4cdJk",
            // save_card:1
        };
        Razorpay.open(options2).then((data) => {
            // handle success
            alert(Success: ${data.razorpay_payment_id});
        }).catch((error) => {
            // handle failure
            console.log(Error: ${error.code} | ${error.description})
            alert(Error: ${error.code} | ${error.description});
        });

**Comment by vivekshindhe** [comment]
@zoxicorp Saved cards on Checkout is a on-demand feature provided by Razorpay. Please raise a Support ticket from your Razorpay Dashboard. They should be able to help you resolve this issue. Also, [attaching a doc](https://razorpay.com/docs/payments/payment-gateway/web-integration/custom/features/saved-cards/) which states the process of using saved cards in Checkout. 

Closing this ticket.
