### ISSUE TITLE
Android app crashes after the successful payment

### ISSUE THREAD

**Issue by siddharth9470** [razorpay/react-native-razorpay#472]
Below is the exception tracked by Sentry

Unable to start receiver com.rnsmsretriever.SmsBroadcastReceiver: java.lang.NullPointerException: null cannot be cast to non-null type kotlin.String

react-native version: 0.73.4

**Comment by vivekshindhe** [comment]
@siddharth9470 The class com.rnsmsretriever.SmsBroadcastReceiver is not a class from Razorpay react-native package. SMS Retreiver used by react-native-razorpay has been implemented on the Android Native side directly with the SMS retriever API and not through react-native. Closing this ticket for now. But please feel free to reopen or create another issue if you find that more details of the crash are related to the Razorpay's react-native package. Thanks.
