### ISSUE TITLE
Razorpay is not working for android

### ISSUE THREAD

**Issue by anantkamat** [razorpay/react-native-razorpay#48]
I have tried manual installation also. i am not able to build the app.
gives error like this.
A problem occurred configuring project ':app'.
> Could not resolve all dependencies for configuration ':app:_debugApk'.
   > Configuration with name 'default' not found.

**Comment by hariramsvnit** [comment]
@anantkamat Can you please try https://github.com/razorpay/react-native-razorpay/tree/master/example
