### ISSUE TITLE
Could not resolve com.razorpay:checkout:1.6.+.

### ISSUE THREAD

**Issue by Surajsharma1502** [razorpay/react-native-razorpay#486]
![Screenshot 2024-12-19 122225](https://github.com/user-attachments/assets/41d02727-ba8f-468e-847a-d51312b1fb55)
I have Used 
**React native 0.75.3**
**react-native-razorpay: 2.3.0** 
FAILURE: Build failed with an exception.

* What went wrong:
Could not determine the dependencies of task ':app:processDebugResources'.
> Could not resolve all dependencies for configuration ':app:debugRuntimeClasspath'.
   > Could not resolve com.razorpay:checkout:1.6.+.
     Required by:
         project :app > project :react-native-razorpay
      > Failed to list versions for com.razorpay:checkout.
         > Unable to load Maven meta-data from https://www.jitpack.io/com/razorpay/checkout/maven-metadata.xml.
            > Could not GET 'https://www.jitpack.io/com/razorpay/checkout/maven-metadata.xml'. Received status code 521 from server:

* Try:
> Run with --stacktrace option to get the stack trace.
> Run with --info or --debug option to get more log output.
> Run with --scan to get full insights.
> Get more help at https://help.gradle.org.

BUILD FAILED in 42s
error Failed to install the app. Command failed with exit code 1: gradlew.bat app:installDebug -PreactNativeDevServerPort=8081 FAILURE: Build failed with an exception. * What went wrong: Could not determine the dependencies of task ':app:processDebugResources'. > Could not resolve all dependencies for configuration ':app:debugRuntimeClasspath'. > Could not resolve com.razorpay:checkout:1.6.+. Required by: project :app > project :react-native-razorpay > Failed to list versions for com.razorpay:checkout. > Unable to load Maven meta-data from https://www.jitpack.io/com/razorpay/checkout/maven-metadata.xml. > Could not GET 'https://www.jitpack.io/com/razorpay/checkout/maven-metadata.xml'. Received status code 521 from server: * Try: > Run with --stacktrace option to get the stack trace. > Run with --info or --debug option to get more log output. > Run with --scan to get full insights. > Get more help at https://help.gradle.org. BUILD FAILED in 42s.
info Run CLI with --verbose flag for more details.

**Comment by ayanWappnet** [comment]
i also get same error     

         project :app > project :react-native-razorpay
      > Failed to list versions for com.razorpay:checkout.

**Comment by pranitalohakare** [comment]
I am also getting the same error.
react-native: 0.74.4
react-native-razorpay: 2.3.0

FAILURE: Build failed with an exception.

* What went wrong:
Could not determine the dependencies of task ':app:lintVitalReportRelease'.
> Could not resolve all task dependencies for configuration ':app:releaseRuntimeClasspath'.
   > Could not resolve com.razorpay:checkout:1.6.+.
     Required by:
         project :app > project :react-native-razorpay
      > Failed to list versions for com.razorpay:checkout.
         > Unable to load Maven meta-data from https://www.jitpack.io/com/razorpay/checkout/maven-metadata.xml.
            > Could not GET 'https://www.jitpack.io/com/razorpay/checkout/maven-metadata.xml'. Received status code 521 from server: 
            
Deprecated Gradle features were used in this build, making it incompatible with Gradle 9.0.

For more on this, please refer to https://docs.gradle.org/8.6/userguide/command_line_interface.html#sec:command_line_warnings in the Gradle documentation.

**Comment by Atss007** [comment]
getting same problem is anyone got the solution?

**Comment by Surajsharma1502** [comment]
Guys, I think it might have been a server issue for the past few days. I installed it today, and it built successfully without any errors.
