### ISSUE TITLE
iOS Pay button does not work & Project does not build in xcode

### ISSUE THREAD

**Issue by jparekh** [razorpay/react-native-razorpay#50]
When we build it and run it using react-native run-ios, the pay button does not open up the payment window.

When we build it in xcode, below error happens:
ld: framework not found Razorpay
clang: error: linker command failed with exit code 1 (use -v to see invocation)

**Comment by AbhinavArora95** [comment]
Please check your project structure - the razorpay framework must be available in the ios directory and under razorpay's react native modules. Please refer to the example in this repo - https://github.com/razorpay/react-native-razorpay/tree/master/example/ios.

**Comment by salilbajaj** [comment]
I was facing the same issue.,. Did What you said.. Copied framework in ios directory. Now project was compiled but getting this error.

dyld: Library not loaded: @rpath/Razorpay.framework/Razorpay
  Referenced from: /Users/salilbajaj/Library/Developer/CoreSimulator/Devices/27DBD252-D2E1-4E11-ABAD-B11C8C60330F/data/Containers/Bundle/Application/F2092B6B-6107-4217-8940-BF0ADA58300C/GoVioletWhite.app/GoVioletWhite
  Reason: image not found

**Comment by AbhinavArora95** [comment]
Make sure the framework is added in both the Embeded Binaries and Linked Frameworks and Libraries under Target settings - General.

**Comment by salilbajaj** [comment]
It was not there in Embeded Binaries. Did that .. Still getting the same error.

**Comment by AbhinavArora95** [comment]
Check if you have added it in the target you are building. Make sure you Clean the project and rebuild it. If you still face the issue, email us at integrations@razorpay.com and I will arrange a team viewer session for you to resolve the issue. As far as the issue is considered, it's not an error in the framework.

**Comment by salilbajaj** [comment]
It was working fine with the previous version. I upgraded npm package and now its almost a week that am unable to resolve razorpay issue. Earlier link was dead, then framework not found and now this :/ .. Please review and update documentation. Its my third app where I am using razorpay  and no other node modules has given me more pain than this. Earlier Akshay was there . He helped in integrating this 1 year back.

**Comment by salilbajaj** [comment]
Cool .. Will mail you.. Thanks

**Comment by malangaveuday** [comment]
Xcode, debug show...

dyld: Library not loaded: @rpath/Razorpay.framework/Razorpay
  Referenced from: /var/containers/Bundle/Application/67D9B176-F087-4141-83B7-DE4A00DC3D6F/ios.app/ios
  Reason: image not found

I am facing this issue after removing node_modules and then execute npm install.

**Comment by Mayur-Wadpalliwar** [comment]
@malangaveuday Make sure the framework is added in both the Embeded Binaries and Linked Frameworks and Libraries under Target settings - General and it shall work

**Comment by malangaveuday** [comment]
Hey I did but new error occurs

Library not loaded: @rpath/libswiftCore.dylib
  Referenced from: /private/var/containers/Bundle/Application/640C4207-D86E-47E8-BA06-37E16257179C/ios.app/Frameworks/Razorpay.framework/Razorpay
  Reason: image not found

**Comment by dlucidone** [comment]
@Mayur-Wadpalliwar throwing same error for me too

**Comment by AbhinavArora95** [comment]
As mentioned in our docs - razorpay.com/docs/ios/, make sure the following is true,
- Go to Project Settings.
- Select Build Settings - All and Combined from the Menu of the project settings.
- Under Build Options set Always Embed Swift Standard Libraries option to TRUE.

**Comment by malangaveuday** [comment]
It is working now. 
Thank you

**Comment by dlucidone** [comment]
@AbhinavArora95 Thanks! Got it working :)

**Comment by shonsaoji** [comment]
Now I am facing 
dyld: Symbol not found: _$SBOWV
