### ISSUE TITLE
com.razorpay.rn does not exist

### ISSUE THREAD

**Issue by ggarg2** [razorpay/react-native-razorpay#55]
I am able to see this package in android folder in node modules but still getting this error

> Task :app:compileDebugJavaWithJavac
E:\dev\finalMobileApp\android\app\src\main\java\com\bag2bag\MainApplication.java:6: error: package com.razorpay.rn does not exist
import com.razorpay.rn.RazorpayPackage;
                      ^
E:\dev\finalMobileApp\android\app\src\main\java\com\bag2bag\MainApplication.java:38: error: cannot find symbol
            new RazorpayPackage(),
                ^
  symbol: class RazorpayPackage
2 errors

**Comment by vijay2330** [comment]
I am facing this issue.... Any solutions?
