### ISSUE TITLE
Having ssl problem and sdk download link not working. 

### ISSUE THREAD

**Issue by himanshuverma09** [razorpay/react-native-razorpay#56]
![simulator screen shot - iphone 6 - 2018-02-18 at 21 10 06](https://user-images.githubusercontent.com/5091359/36364993-67356b22-156d-11e8-98f9-91d618257512.png)

**Comment by AbhinavArora95** [comment]
What is the link you are trying to download the sdk ?

**Comment by himanshuverma09** [comment]
This one http://downloads.razorpay.com/Razorpay.framework-0.14.1.zip


Given on documentation here: https://docs.razorpay.com/v1/page/ios-integration

**Comment by AbhinavArora95** [comment]
@himanshuverma09 Please refer to the latest documentation - razorpay.com/docs/ios

**Comment by himanshuverma09** [comment]
OKay and this ssl thing shown in image ?

**Comment by AbhinavArora95** [comment]
The ssl error you are getting is probably because of your antivirus running on your mac. I will suggest you to try this on a physical device or turn of the web shield in your antivirus if you want to run it on simulator.

**Comment by himanshuverma09** [comment]
Tried on physical device same problem...
Device: iPhone SE 
iOS Version: 11.2.5

**Comment by AbhinavArora95** [comment]
Ensure that you have followed this step - https://razorpay.com/docs/ios/#ios-9-update

**Comment by himanshuverma09** [comment]
Ok solved it by adding this in info.plist:

<key>NSAppTransportSecurity</key>
<dict>
    <key>NSAllowsArbitraryLoads</key>
    <true/>
</dict>
