### ISSUE TITLE
Question: Is this production ready? 

### ISSUE THREAD

**Issue by pranjaltech** [razorpay/react-native-razorpay#6]
We are considering using this bridge for a React-Native iOS app. Are there any caveats?

**Comment by akshaybhalotia** [comment]
Yes @pranjaltech , this module is absolutely ready for production use 💯

**Comment by Anujmoglix** [comment]
How to use it in production , I am only getting Screen
![Selection_156](https://user-images.githubusercontent.com/26056096/66470602-8c8d0180-eaa7-11e9-8c16-cfb5aa397cf3.png)

**Comment by pronav** [comment]
@Anujmoglix you need to put razorpay live key instead of test key. you can generate live key from dashboard after razorpay account activation

**Comment by Anujmoglix** [comment]
yes . i have checked that in https://github.com/razorpay/react-native-razorpay/issues/107 as well, Btw thanks for quick response.

**Comment by Anujmoglix** [comment]
For production live key app is crashing in emulator but for Testing atleast UI is showing properly .
