### ISSUE TITLE
Improvement: Please Update Documentation for iOS Integration

### ISSUE THREAD

**Issue by bhavukjain1** [razorpay/react-native-razorpay#62]
I spent so much time integrating it and every time I got this error: `framework not found Razorpay for architecture x86_64`.
After spending numerous hours, I found I need to add `Razorpay.framework` in my project as well (Actually need to do all the steps mentioned in the Objective-C integration: https://razorpay.com/docs/ios/)
Also, `react-native link` didn't work for me. Had to manually link it.
Can you please update your documentation, so it's a hassle-free integration.

**Comment by AbhinavArora95** [comment]
@bhavukjain1 Thank you for informing us. We will update the Readme. In practise, referring to documentation of iOS and Android is recommended. The README only covers the concepts which are focussed on react-native wrapper. I will add a note which will refer to the respective documentations of iOS and Android in Readme.
