### ISSUE TITLE
How to integrate paytm wallet option with latest sdk

### ISSUE THREAD

**Issue by rajaishwary** [razorpay/react-native-razorpay#64]
Does the latest RN lib support this feature that is listed in following link ?

https://docs.razorpay.com/v1/page/listing-external-wallets

**Comment by AbhinavArora95** [comment]
Yes. Please refer to the index.js within the example directory of this repo.

https://github.com/razorpay/react-native-razorpay/tree/master/example
https://github.com/razorpay/react-native-razorpay/blob/master/example/index.js

**Comment by GaneshSaiKumar** [comment]
@rajaishwary @AbhinavArora95 

this isn't returning the control to handler function in external wallets.
Do you have any working solution?

**Comment by AbhishekRn96** [comment]
Is the react-native-razorpay integration working for you @AbhinavArora95 ..??

**Comment by rizwan92** [comment]
I have integrated external wallet paytm  in my checkout like example
when I check out in my app. SDK lists the paytm wallet but did not check out it. 
when I click on paytm wallet then checkout process sudden stops it did not give any response or error

**Comment by Mayur-Wadpalliwar** [comment]
@rizwan92 Razorpay will just give you the control in the handler function where you would need to write your own logic to perform any action. You may refer this: https://razorpay.com/docs/payment-methods/wallets/external-wallets/ for more info
