### ISSUE TITLE
Something went wrong while linking. Error: Cannot read property 'buildConfigurationList' of undefined

### ISSUE THREAD

**Issue by ankitkumarsahu** [razorpay/react-native-razorpay#68]
Steps to recreate the issue:

1. react-native init
2. npm i react-native-razorpay --save
3. react-native link react-native-razorpay

Full issue:
Scanning folders for symlinks in ~/node_modules (19ms)
rnpm-install info Linking react-native-razorpay ios dependency
rnpm-install ERR! Something went wrong while linking. Error: Cannot read property 'buildConfigurationList' of undefined
Please file an issue here: https://github.com/facebook/react-native/issues

Cannot read property 'buildConfigurationList' of undefined

**Comment by iThink32** [comment]
Hey the auto linking step using react-native command 'link' does not seem to work as expected at times , please follow the manual linking procedure given in the readme :

https://github.com/razorpay/react-native-razorpay/wiki/Manual-Installation

**Comment by iThink32** [comment]
closing this issue , please reopen if you still face this issue.

**Comment by kashishgrover** [comment]
I think you should reopen this because `react-native link` command is still not working. I obviously don't mind doing manual linking but shouldn't this be fixed?

**Comment by iThink32** [comment]
@kashishgrover ideally speaking , react-native-link should also work if manual linking is working , many clients have actually used it and on the other hand there are a few who were not able to do so.
I guess we have to research more on this and is on our roadmap but is not a priority right now , you can reopen it if you feel so.

**Comment by nirjack** [comment]
still facing the issue

**Comment by getinfyKiranreddy** [comment]
I am also getting same issues please help me out

**Comment by pronav** [comment]
Please provide plugin version, XCode version and react-native version.

We can have a screen-sharing session to help with modules linking, if needed.

**Comment by getinfyKiranreddy** [comment]
Xcode version: 10
React-native version: 0.57.8
Yes I need help

**Comment by pronav** [comment]
Is it xcode 10.1 or 10.2, or version 10?

**Comment by getinfyKiranreddy** [comment]
10.2.1

**Comment by getinfyKiranreddy** [comment]
I got another issue that is 
framework not found Razorpay
I have added in framework also but I am getting this error 
Could you help me out ?

**Comment by rkbansal** [comment]
Hi Everyone, installing and linking using rnpm instead of react-native solved this issue.
Steps,
1. Install rnpm globally by `npm install -g rnpm`
2. Then install packages by `rnpm install`
3. Then link packages by `rnpm link`
