### ISSUE TITLE
`npm install` is not working 

### ISSUE THREAD

**Issue by pranjaltech** [razorpay/react-native-razorpay#7]
Even accessing `https://registry.npmjs.org/react-native-razorpay/-/react-native-razorpay-1.0.0.tgz` throws a 503: 
<img width="799" alt="screen shot 2016-11-07 at 2 31 33 pm" src="https://cloud.githubusercontent.com/assets/71014/20051812/ee8bca5a-a4f6-11e6-8b30-8b7792c61f1e.png">

**Comment by selvagsz** [comment]
@pranjaltech Sounds like a problem with npm. Got the same error while installing other packages as well

<img width="747" alt="screen shot 2016-11-07 at 2 48 14 pm" src="https://cloud.githubusercontent.com/assets/2162441/20052471/29076cb8-a4fa-11e6-8d75-a3bd081dd463.png">

**Comment by pranjaltech** [comment]
@selvagsz You're right. NPM just updated their status, they're seeing elevated 503s.  http://status.npmjs.org/history

Closing this issue.
