### ISSUE TITLE
Xcode 9.3 error but it is working in Xcode 9.2

### ISSUE THREAD

**Issue by malangaveuday** [razorpay/react-native-razorpay#70]
**Error :- Library not loaded: @rpath/libswiftCore.dylib**

This manual [installation steps](https://github.com/razorpay/react-native-razorpay/wiki/Manual-Installation) is working for Xcode 9.2 but failing in Xcode 9.3

**Comment by iThink32** [comment]
which version of the the framework are you using? 
Please note that the new framework will not work on Xcode 9.2 , it will work only on Xcode 9.3 so please update your framework and try again.
Regarding this issue please add the razorpay framework from node_modules/react-native-razorypay/ios to your main projects embebed binaries phase and also make sure the build setting AlwaysEmbedSwiftLibraries is set to yes.

**Comment by sivakumar-cf** [comment]
Facing the same issue, I added the razorpay.framework in both linked libraries and embedded libraries.
Enabled Always embedded swift libraries under main Project settings.
Also added Runpath search paths "@executable_path/Frameworks"
Cleaned many times still facing runtime crash
"Error :- Library not loaded: .dylib"

**Comment by kc-curefit** [comment]
Please get this resolved, this is a blocking issue for us.

**Comment by AbhinavArora95** [comment]
@sivakumar-cf @kc-curefit Which xcode version are you using ?

**Comment by TheMarsGuy** [comment]
Facing a similar issue. Not working on Xcode 9.3.1
Build succeeds. While running it on Xcode I get the following:  

<img width="890" alt="razorpay" src="https://user-images.githubusercontent.com/10371003/39992976-03ffc568-5792-11e8-8509-c2dc18c7da7b.png">

**Comment by TheMarsGuy** [comment]
The issue is solved for me. I followed what @iThink32 had mentioned:

1. Add the razorpay framework from node_modules/react-native-razorypay/ios to your main projects embebed binaries phase.
2. Make sure the build setting `Always Embed Swift Standard Libraries` is set to yes.
