### ISSUE TITLE
Getting architechtural issues

### ISSUE THREAD

**Issue by thejasreem** [razorpay/react-native-razorpay#75]
Hi, Can anyone help me out with this issue
While uploading iOS build into test flight getting architectural issues for react-native-razorpay.

react-native version:0.51
react-native-razorpay version: 2.0.3

**Comment by iThink32** [comment]
Hey , 
Our framework is shipped with simulator architectures to enable you to run it on a simulator.
Please follow this link which will help you strip the simulator architectures before an archive.

http://ikennd.ac/blog/2015/02/stripping-unwanted-architectures-from-dynamic-libraries-in-xcode/

**Comment by thejasreem** [comment]
Hey, the architectural issue was resolved.
Thank you!

**Comment by iThink32** [comment]
your welcome
