### ISSUE TITLE
Does it support Paytm wallet ?

### ISSUE THREAD

**Issue by amitbravo** [razorpay/react-native-razorpay#85]
## IDE Specs 
Xcode Version : 9.3
Gradle version : 4.4
Razorpay :  2.0.6

I do not see paytm wallet into the wallet's list .

**Comment by iThink32** [comment]
No we do not support paytm wallet

**Comment by amitbravo** [comment]
what about now ?

**Comment by iThink32** [comment]
@amitbravo no because Paytm has no provided support to payment aggregators yet.
