### ISSUE TITLE
Is there a way to prevent bounces effect in iOS

### ISSUE THREAD

**Issue by guggume** [razorpay/react-native-razorpay#86]
It's not an issue, just wanted to know whether I can disable the bounce effect

**Comment by iThink32** [comment]
which bounce effect?

**Comment by guggume** [comment]
![ezgif com-video-to-gif](https://user-images.githubusercontent.com/30231895/41248635-45e274b4-6dcf-11e8-8994-25ed4ffab6c4.gif)

**Comment by guggume** [comment]
I'd like to disable ovescroll/bounce from razorpay, so that my background screen will not be visible.

**Comment by iThink32** [comment]
The way I see it the problem is not with the bouncing effect , it is with the background being transparent.There is no provision to enable this in the current release but we will take this into consideration for the next sprint.

**Comment by guggume** [comment]
Thank you for very prompt response. Closing this issue as it was a feature request.
