### ISSUE TITLE
The SDK Build Tools revision (24.0.0) is too low for project ':react-native-razorpay'. Minimum required is 25.0.0

### ISSUE THREAD

**Issue by km16** [razorpay/react-native-razorpay#92]
* **Common to Both platforms :-**

  - [x] I have gone through the README (https://github.com/razorpay/react-native-razorpay)
  - [x] I have searched for a similar issue (https://github.com/razorpay/react-native-razorpay/issues)
  - [ ] I am using the latest version of our framework (https://github.com/razorpay/react-native-razorpay/releases)
  - [x] I have cleaned my project.

Upgraded my project to 0.56. So my build.gradle had the config like so
```
ext {
    buildToolsVersion = "26.0.3"
    minSdkVersion = 16
    compileSdkVersion = 26
    targetSdkVersion = 26
    supportLibVersion = "26.1.0"
}
```

## IDE Specs
Razorpay Package Version: 2.0.5

## Retro Steps
`react-native start`
`react-native run-android`

## Screenshots 
<img width="1005" alt="razorpay" src="https://user-images.githubusercontent.com/41142904/42620178-d393a704-85d7-11e8-934c-e4af8897fc30.png">

**Comment by hariramsvnit** [comment]
@km16 Can you please check https://github.com/oblador/react-native-keychain/issues/68 and see if it solves your issue?
