### ISSUE TITLE
Need it working with Older version of RN -0.45, what changes I need to make ?

### ISSUE THREAD

**Issue by krunalFlexiLoans** [razorpay/react-native-razorpay#98]
I have completed my project with 0.45 version of RN, and it is completed. Now I need to integrate Payment Gateway, please help me what changes I need to make with RazorPay in order to integrate it with 0.45 version.
Please help. Really Stuck.

**Comment by iThink32** [comment]
Im sorry but we do not have any sdk supporting RN 0.45 as of now.

**Comment by iThink32** [comment]
Closing this issue now , please reopen if you need any further assistance.
